/*
 * DummyCommands.java
 *
 * Copyright (C) 2022 by Posit Software, PBC
 *
 * Unless you have received this program directly from Posit Software pursuant
 * to the terms of a commercial license agreement with Posit Software, then
 * this program is licensed to you under the terms of version 3 of the
 * GNU Affero General Public License. This program is distributed WITHOUT
 * ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
 * AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
 *
 */
package org.rstudio.studio.client.workbench.commands;

/**
 * Marker class for generating a dummy Commands implementation.
 * Use GWT.create(DummyCommands.class) to get an instance where all
 * AppCommand methods return an AppCommand with a valid ImageResource
 * and menu methods have empty bodies.
 *
 * The implementation is generated by DummyCommandsGenerator.
 */
public abstract class DummyCommands extends Commands
{
}
