/*
 * Copyright 2012 Google Inc.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package elemental.js.css;
import elemental.css.CSSValue;
import elemental.css.CSSStyleDeclaration;
import elemental.css.CSSRule;

import com.google.gwt.core.client.GWT;
import com.google.gwt.core.client.JavaScriptObject;

import elemental.events.*;
import elemental.util.*;
import elemental.dom.*;
import elemental.html.*;
import elemental.css.*;
import elemental.js.stylesheets.*;
import elemental.js.events.*;
import elemental.js.util.*;
import elemental.js.dom.*;
import elemental.js.html.*;
import elemental.js.css.*;
import elemental.js.stylesheets.*;

import java.util.Date;

public class JsCSSStyleDeclaration extends JsElementalMixinBase  implements CSSStyleDeclaration {
  protected JsCSSStyleDeclaration() {}

  public final native String getCssText() /*-{
    return this.cssText;
  }-*/;

  public final native void setCssText(String param_cssText) /*-{
    this.cssText = param_cssText;
  }-*/;

  public final native int getLength() /*-{
    return this.length;
  }-*/;

  public final native JsCSSRule getParentRule() /*-{
    return this.parentRule;
  }-*/;

  public final native JsCSSValue getPropertyCSSValue(String propertyName) /*-{
    return this.getPropertyCSSValue(propertyName);
  }-*/;

  public final native String getPropertyPriority(String propertyName) /*-{
    return this.getPropertyPriority(propertyName);
  }-*/;

  public final native String getPropertyShorthand(String propertyName) /*-{
    return this.getPropertyShorthand(propertyName);
  }-*/;

  public final native String getPropertyValue(String propertyName) /*-{
    return this.getPropertyValue(propertyName);
  }-*/;

  public final native boolean isPropertyImplicit(String propertyName) /*-{
    return this.isPropertyImplicit(propertyName);
  }-*/;

  public final native String item(int index) /*-{
    return this.item(index);
  }-*/;

  public final native String removeProperty(String propertyName) /*-{
    return this.removeProperty(propertyName);
  }-*/;

  public final native void setProperty(String propertyName, String value) /*-{
    this.setProperty(propertyName, value);
  }-*/;

  public final native void setProperty(String propertyName, String value, String priority) /*-{
    this.setProperty(propertyName, value, priority);
  }-*/;

public final native String getColor() /*-{ return this.color; }-*/;
public final native void setColor(String value) /*-{ this.color = value; }-*/;
public final native void clearColor() /*-{ this.color = ""; }-*/;
public final native String getDirection() /*-{ return this.direction; }-*/;
public final native void setDirection(String value) /*-{ this.direction = value; }-*/;
public final native void clearDirection() /*-{ this.direction = ""; }-*/;
public final native String getDisplay() /*-{ return this.display; }-*/;
public final native void setDisplay(String value) /*-{ this.display = value; }-*/;
public final native void clearDisplay() /*-{ this.display = ""; }-*/;
public final native String getFont() /*-{ return this.font; }-*/;
public final native void setFont(String value) /*-{ this.font = value; }-*/;
public final native void clearFont() /*-{ this.font = ""; }-*/;
public final native String getFontFamily() /*-{ return this.fontFamily; }-*/;
public final native void setFontFamily(String value) /*-{ this.fontFamily = value; }-*/;
public final native void clearFontFamily() /*-{ this.fontFamily = ""; }-*/;
public final native String getFontSize() /*-{ return this.fontSize; }-*/;
public final native void setFontSize(String value) /*-{ this.fontSize = value; }-*/;
public final native void clearFontSize() /*-{ this.fontSize = ""; }-*/;
public final native void setFontSize(double value, String unit) /*-{ this.fontSize = value + unit; }-*/;
public final native String getFontStyle() /*-{ return this.fontStyle; }-*/;
public final native void setFontStyle(String value) /*-{ this.fontStyle = value; }-*/;
public final native void clearFontStyle() /*-{ this.fontStyle = ""; }-*/;
public final native String getFontWeight() /*-{ return this.fontWeight; }-*/;
public final native void setFontWeight(String value) /*-{ this.fontWeight = value; }-*/;
public final native void clearFontWeight() /*-{ this.fontWeight = ""; }-*/;
public final native String getFontVariant() /*-{ return this.fontVariant; }-*/;
public final native void setFontVariant(String value) /*-{ this.fontVariant = value; }-*/;
public final native void clearFontVariant() /*-{ this.fontVariant = ""; }-*/;
public final native String getTextRendering() /*-{ return this.textRendering; }-*/;
public final native void setTextRendering(String value) /*-{ this.textRendering = value; }-*/;
public final native void clearTextRendering() /*-{ this.textRendering = ""; }-*/;
public final native String getWebkitFontFeatureSettings() /*-{ return this.webkitFontFeatureSettings; }-*/;
public final native void setWebkitFontFeatureSettings(String value) /*-{ this.webkitFontFeatureSettings = value; }-*/;
public final native void clearWebkitFontFeatureSettings() /*-{ this.webkitFontFeatureSettings = ""; }-*/;
public final native String getWebkitFontKerning() /*-{ return this.webkitFontKerning; }-*/;
public final native void setWebkitFontKerning(String value) /*-{ this.webkitFontKerning = value; }-*/;
public final native void clearWebkitFontKerning() /*-{ this.webkitFontKerning = ""; }-*/;
public final native String getWebkitFontSmoothing() /*-{ return this.webkitFontSmoothing; }-*/;
public final native void setWebkitFontSmoothing(String value) /*-{ this.webkitFontSmoothing = value; }-*/;
public final native void clearWebkitFontSmoothing() /*-{ this.webkitFontSmoothing = ""; }-*/;
public final native String getWebkitFontVariantLigatures() /*-{ return this.webkitFontVariantLigatures; }-*/;
public final native void setWebkitFontVariantLigatures(String value) /*-{ this.webkitFontVariantLigatures = value; }-*/;
public final native void clearWebkitFontVariantLigatures() /*-{ this.webkitFontVariantLigatures = ""; }-*/;
public final native String getWebkitLocale() /*-{ return this.webkitLocale; }-*/;
public final native void setWebkitLocale(String value) /*-{ this.webkitLocale = value; }-*/;
public final native void clearWebkitLocale() /*-{ this.webkitLocale = ""; }-*/;
public final native String getWebkitTextOrientation() /*-{ return this.webkitTextOrientation; }-*/;
public final native void setWebkitTextOrientation(String value) /*-{ this.webkitTextOrientation = value; }-*/;
public final native void clearWebkitTextOrientation() /*-{ this.webkitTextOrientation = ""; }-*/;
public final native String getWebkitTextSizeAdjust() /*-{ return this.webkitTextSizeAdjust; }-*/;
public final native void setWebkitTextSizeAdjust(String value) /*-{ this.webkitTextSizeAdjust = value; }-*/;
public final native void clearWebkitTextSizeAdjust() /*-{ this.webkitTextSizeAdjust = ""; }-*/;
public final native String getWebkitWritingMode() /*-{ return this.webkitWritingMode; }-*/;
public final native void setWebkitWritingMode(String value) /*-{ this.webkitWritingMode = value; }-*/;
public final native void clearWebkitWritingMode() /*-{ this.webkitWritingMode = ""; }-*/;
public final native String getZoom() /*-{ return this.zoom; }-*/;
public final native void setZoom(String value) /*-{ this.zoom = value; }-*/;
public final native void clearZoom() /*-{ this.zoom = ""; }-*/;
public final native String getLineHeight() /*-{ return this.lineHeight; }-*/;
public final native void setLineHeight(String value) /*-{ this.lineHeight = value; }-*/;
public final native void clearLineHeight() /*-{ this.lineHeight = ""; }-*/;
public final native String getBackground() /*-{ return this.background; }-*/;
public final native void setBackground(String value) /*-{ this.background = value; }-*/;
public final native void clearBackground() /*-{ this.background = ""; }-*/;
public final native String getBackgroundAttachment() /*-{ return this.backgroundAttachment; }-*/;
public final native void setBackgroundAttachment(String value) /*-{ this.backgroundAttachment = value; }-*/;
public final native void clearBackgroundAttachment() /*-{ this.backgroundAttachment = ""; }-*/;
public final native String getBackgroundClip() /*-{ return this.backgroundClip; }-*/;
public final native void setBackgroundClip(String value) /*-{ this.backgroundClip = value; }-*/;
public final native void clearBackgroundClip() /*-{ this.backgroundClip = ""; }-*/;
public final native String getBackgroundColor() /*-{ return this.backgroundColor; }-*/;
public final native void setBackgroundColor(String value) /*-{ this.backgroundColor = value; }-*/;
public final native void clearBackgroundColor() /*-{ this.backgroundColor = ""; }-*/;
public final native String getBackgroundImage() /*-{ return this.backgroundImage; }-*/;
public final native void setBackgroundImage(String value) /*-{ this.backgroundImage = value; }-*/;
public final native void clearBackgroundImage() /*-{ this.backgroundImage = ""; }-*/;
public final native String getBackgroundOrigin() /*-{ return this.backgroundOrigin; }-*/;
public final native void setBackgroundOrigin(String value) /*-{ this.backgroundOrigin = value; }-*/;
public final native void clearBackgroundOrigin() /*-{ this.backgroundOrigin = ""; }-*/;
public final native String getBackgroundPosition() /*-{ return this.backgroundPosition; }-*/;
public final native void setBackgroundPosition(String value) /*-{ this.backgroundPosition = value; }-*/;
public final native void clearBackgroundPosition() /*-{ this.backgroundPosition = ""; }-*/;
public final native String getBackgroundPositionX() /*-{ return this.backgroundPositionX; }-*/;
public final native void setBackgroundPositionX(String value) /*-{ this.backgroundPositionX = value; }-*/;
public final native void clearBackgroundPositionX() /*-{ this.backgroundPositionX = ""; }-*/;
public final native String getBackgroundPositionY() /*-{ return this.backgroundPositionY; }-*/;
public final native void setBackgroundPositionY(String value) /*-{ this.backgroundPositionY = value; }-*/;
public final native void clearBackgroundPositionY() /*-{ this.backgroundPositionY = ""; }-*/;
public final native String getBackgroundRepeat() /*-{ return this.backgroundRepeat; }-*/;
public final native void setBackgroundRepeat(String value) /*-{ this.backgroundRepeat = value; }-*/;
public final native void clearBackgroundRepeat() /*-{ this.backgroundRepeat = ""; }-*/;
public final native String getBackgroundRepeatX() /*-{ return this.backgroundRepeatX; }-*/;
public final native void setBackgroundRepeatX(String value) /*-{ this.backgroundRepeatX = value; }-*/;
public final native void clearBackgroundRepeatX() /*-{ this.backgroundRepeatX = ""; }-*/;
public final native String getBackgroundRepeatY() /*-{ return this.backgroundRepeatY; }-*/;
public final native void setBackgroundRepeatY(String value) /*-{ this.backgroundRepeatY = value; }-*/;
public final native void clearBackgroundRepeatY() /*-{ this.backgroundRepeatY = ""; }-*/;
public final native String getBackgroundSize() /*-{ return this.backgroundSize; }-*/;
public final native void setBackgroundSize(String value) /*-{ this.backgroundSize = value; }-*/;
public final native void clearBackgroundSize() /*-{ this.backgroundSize = ""; }-*/;
public final native String getBorder() /*-{ return this.border; }-*/;
public final native void setBorder(String value) /*-{ this.border = value; }-*/;
public final native void clearBorder() /*-{ this.border = ""; }-*/;
public final native String getBorderBottom() /*-{ return this.borderBottom; }-*/;
public final native void setBorderBottom(String value) /*-{ this.borderBottom = value; }-*/;
public final native void clearBorderBottom() /*-{ this.borderBottom = ""; }-*/;
public final native String getBorderBottomColor() /*-{ return this.borderBottomColor; }-*/;
public final native void setBorderBottomColor(String value) /*-{ this.borderBottomColor = value; }-*/;
public final native void clearBorderBottomColor() /*-{ this.borderBottomColor = ""; }-*/;
public final native String getBorderBottomLeftRadius() /*-{ return this.borderBottomLeftRadius; }-*/;
public final native void setBorderBottomLeftRadius(String value) /*-{ this.borderBottomLeftRadius = value; }-*/;
public final native void clearBorderBottomLeftRadius() /*-{ this.borderBottomLeftRadius = ""; }-*/;
public final native String getBorderBottomRightRadius() /*-{ return this.borderBottomRightRadius; }-*/;
public final native void setBorderBottomRightRadius(String value) /*-{ this.borderBottomRightRadius = value; }-*/;
public final native void clearBorderBottomRightRadius() /*-{ this.borderBottomRightRadius = ""; }-*/;
public final native String getBorderBottomStyle() /*-{ return this.borderBottomStyle; }-*/;
public final native void setBorderBottomStyle(String value) /*-{ this.borderBottomStyle = value; }-*/;
public final native void clearBorderBottomStyle() /*-{ this.borderBottomStyle = ""; }-*/;
public final native String getBorderBottomWidth() /*-{ return this.borderBottomWidth; }-*/;
public final native void setBorderBottomWidth(String value) /*-{ this.borderBottomWidth = value; }-*/;
public final native void clearBorderBottomWidth() /*-{ this.borderBottomWidth = ""; }-*/;
public final native String getBorderCollapse() /*-{ return this.borderCollapse; }-*/;
public final native void setBorderCollapse(String value) /*-{ this.borderCollapse = value; }-*/;
public final native void clearBorderCollapse() /*-{ this.borderCollapse = ""; }-*/;
public final native String getBorderColor() /*-{ return this.borderColor; }-*/;
public final native void setBorderColor(String value) /*-{ this.borderColor = value; }-*/;
public final native void clearBorderColor() /*-{ this.borderColor = ""; }-*/;
public final native String getBorderImage() /*-{ return this.borderImage; }-*/;
public final native void setBorderImage(String value) /*-{ this.borderImage = value; }-*/;
public final native void clearBorderImage() /*-{ this.borderImage = ""; }-*/;
public final native String getBorderImageOutset() /*-{ return this.borderImageOutset; }-*/;
public final native void setBorderImageOutset(String value) /*-{ this.borderImageOutset = value; }-*/;
public final native void clearBorderImageOutset() /*-{ this.borderImageOutset = ""; }-*/;
public final native String getBorderImageRepeat() /*-{ return this.borderImageRepeat; }-*/;
public final native void setBorderImageRepeat(String value) /*-{ this.borderImageRepeat = value; }-*/;
public final native void clearBorderImageRepeat() /*-{ this.borderImageRepeat = ""; }-*/;
public final native String getBorderImageSlice() /*-{ return this.borderImageSlice; }-*/;
public final native void setBorderImageSlice(String value) /*-{ this.borderImageSlice = value; }-*/;
public final native void clearBorderImageSlice() /*-{ this.borderImageSlice = ""; }-*/;
public final native String getBorderImageSource() /*-{ return this.borderImageSource; }-*/;
public final native void setBorderImageSource(String value) /*-{ this.borderImageSource = value; }-*/;
public final native void clearBorderImageSource() /*-{ this.borderImageSource = ""; }-*/;
public final native String getBorderImageWidth() /*-{ return this.borderImageWidth; }-*/;
public final native void setBorderImageWidth(String value) /*-{ this.borderImageWidth = value; }-*/;
public final native void clearBorderImageWidth() /*-{ this.borderImageWidth = ""; }-*/;
public final native String getBorderLeft() /*-{ return this.borderLeft; }-*/;
public final native void setBorderLeft(String value) /*-{ this.borderLeft = value; }-*/;
public final native void clearBorderLeft() /*-{ this.borderLeft = ""; }-*/;
public final native String getBorderLeftColor() /*-{ return this.borderLeftColor; }-*/;
public final native void setBorderLeftColor(String value) /*-{ this.borderLeftColor = value; }-*/;
public final native void clearBorderLeftColor() /*-{ this.borderLeftColor = ""; }-*/;
public final native String getBorderLeftStyle() /*-{ return this.borderLeftStyle; }-*/;
public final native void setBorderLeftStyle(String value) /*-{ this.borderLeftStyle = value; }-*/;
public final native void clearBorderLeftStyle() /*-{ this.borderLeftStyle = ""; }-*/;
public final native String getBorderLeftWidth() /*-{ return this.borderLeftWidth; }-*/;
public final native void setBorderLeftWidth(String value) /*-{ this.borderLeftWidth = value; }-*/;
public final native void clearBorderLeftWidth() /*-{ this.borderLeftWidth = ""; }-*/;
public final native String getBorderRadius() /*-{ return this.borderRadius; }-*/;
public final native void setBorderRadius(String value) /*-{ this.borderRadius = value; }-*/;
public final native void clearBorderRadius() /*-{ this.borderRadius = ""; }-*/;
public final native String getBorderRight() /*-{ return this.borderRight; }-*/;
public final native void setBorderRight(String value) /*-{ this.borderRight = value; }-*/;
public final native void clearBorderRight() /*-{ this.borderRight = ""; }-*/;
public final native String getBorderRightColor() /*-{ return this.borderRightColor; }-*/;
public final native void setBorderRightColor(String value) /*-{ this.borderRightColor = value; }-*/;
public final native void clearBorderRightColor() /*-{ this.borderRightColor = ""; }-*/;
public final native String getBorderRightStyle() /*-{ return this.borderRightStyle; }-*/;
public final native void setBorderRightStyle(String value) /*-{ this.borderRightStyle = value; }-*/;
public final native void clearBorderRightStyle() /*-{ this.borderRightStyle = ""; }-*/;
public final native String getBorderRightWidth() /*-{ return this.borderRightWidth; }-*/;
public final native void setBorderRightWidth(String value) /*-{ this.borderRightWidth = value; }-*/;
public final native void clearBorderRightWidth() /*-{ this.borderRightWidth = ""; }-*/;
public final native String getBorderSpacing() /*-{ return this.borderSpacing; }-*/;
public final native void setBorderSpacing(String value) /*-{ this.borderSpacing = value; }-*/;
public final native void clearBorderSpacing() /*-{ this.borderSpacing = ""; }-*/;
public final native String getBorderStyle() /*-{ return this.borderStyle; }-*/;
public final native void setBorderStyle(String value) /*-{ this.borderStyle = value; }-*/;
public final native void clearBorderStyle() /*-{ this.borderStyle = ""; }-*/;
public final native String getBorderTop() /*-{ return this.borderTop; }-*/;
public final native void setBorderTop(String value) /*-{ this.borderTop = value; }-*/;
public final native void clearBorderTop() /*-{ this.borderTop = ""; }-*/;
public final native String getBorderTopColor() /*-{ return this.borderTopColor; }-*/;
public final native void setBorderTopColor(String value) /*-{ this.borderTopColor = value; }-*/;
public final native void clearBorderTopColor() /*-{ this.borderTopColor = ""; }-*/;
public final native String getBorderTopLeftRadius() /*-{ return this.borderTopLeftRadius; }-*/;
public final native void setBorderTopLeftRadius(String value) /*-{ this.borderTopLeftRadius = value; }-*/;
public final native void clearBorderTopLeftRadius() /*-{ this.borderTopLeftRadius = ""; }-*/;
public final native String getBorderTopRightRadius() /*-{ return this.borderTopRightRadius; }-*/;
public final native void setBorderTopRightRadius(String value) /*-{ this.borderTopRightRadius = value; }-*/;
public final native void clearBorderTopRightRadius() /*-{ this.borderTopRightRadius = ""; }-*/;
public final native String getBorderTopStyle() /*-{ return this.borderTopStyle; }-*/;
public final native void setBorderTopStyle(String value) /*-{ this.borderTopStyle = value; }-*/;
public final native void clearBorderTopStyle() /*-{ this.borderTopStyle = ""; }-*/;
public final native String getBorderTopWidth() /*-{ return this.borderTopWidth; }-*/;
public final native void setBorderTopWidth(String value) /*-{ this.borderTopWidth = value; }-*/;
public final native void clearBorderTopWidth() /*-{ this.borderTopWidth = ""; }-*/;
public final native String getBorderWidth() /*-{ return this.borderWidth; }-*/;
public final native void setBorderWidth(String value) /*-{ this.borderWidth = value; }-*/;
public final native void clearBorderWidth() /*-{ this.borderWidth = ""; }-*/;
public final native void setBorderWidth(double value, String unit) /*-{ this.borderWidth = value + unit; }-*/;
public final native String getBottom() /*-{ return this.bottom; }-*/;
public final native void setBottom(String value) /*-{ this.bottom = value; }-*/;
public final native void clearBottom() /*-{ this.bottom = ""; }-*/;
public final native void setBottom(double value, String unit) /*-{ this.bottom = value + unit; }-*/;
public final native String getBoxShadow() /*-{ return this.boxShadow; }-*/;
public final native void setBoxShadow(String value) /*-{ this.boxShadow = value; }-*/;
public final native void clearBoxShadow() /*-{ this.boxShadow = ""; }-*/;
public final native String getBoxSizing() /*-{ return this.boxSizing; }-*/;
public final native void setBoxSizing(String value) /*-{ this.boxSizing = value; }-*/;
public final native void clearBoxSizing() /*-{ this.boxSizing = ""; }-*/;
public final native String getCaptionSide() /*-{ return this.captionSide; }-*/;
public final native void setCaptionSide(String value) /*-{ this.captionSide = value; }-*/;
public final native void clearCaptionSide() /*-{ this.captionSide = ""; }-*/;
public final native String getClear() /*-{ return this.clear; }-*/;
public final native void setClear(String value) /*-{ this.clear = value; }-*/;
public final native void clearClear() /*-{ this.clear = ""; }-*/;
public final native String getClip() /*-{ return this.clip; }-*/;
public final native void setClip(String value) /*-{ this.clip = value; }-*/;
public final native void clearClip() /*-{ this.clip = ""; }-*/;
public final native String getContent() /*-{ return this.content; }-*/;
public final native void setContent(String value) /*-{ this.content = value; }-*/;
public final native void clearContent() /*-{ this.content = ""; }-*/;
public final native String getCounterIncrement() /*-{ return this.counterIncrement; }-*/;
public final native void setCounterIncrement(String value) /*-{ this.counterIncrement = value; }-*/;
public final native void clearCounterIncrement() /*-{ this.counterIncrement = ""; }-*/;
public final native String getCounterReset() /*-{ return this.counterReset; }-*/;
public final native void setCounterReset(String value) /*-{ this.counterReset = value; }-*/;
public final native void clearCounterReset() /*-{ this.counterReset = ""; }-*/;
public final native String getCursor() /*-{ return this.cursor; }-*/;
public final native void setCursor(String value) /*-{ this.cursor = value; }-*/;
public final native void clearCursor() /*-{ this.cursor = ""; }-*/;
public final native String getEmptyCells() /*-{ return this.emptyCells; }-*/;
public final native void setEmptyCells(String value) /*-{ this.emptyCells = value; }-*/;
public final native void clearEmptyCells() /*-{ this.emptyCells = ""; }-*/;
public final native String getFloat() /*-{ return this['float']; }-*/;
public final native void setFloat(String value) /*-{ this['float'] = value; }-*/;
public final native void clearFloat() /*-{ this['float'] = ""; }-*/;
public final native String getFontStretch() /*-{ return this.fontStretch; }-*/;
public final native void setFontStretch(String value) /*-{ this.fontStretch = value; }-*/;
public final native void clearFontStretch() /*-{ this.fontStretch = ""; }-*/;
public final native String getHeight() /*-{ return this.height; }-*/;
public final native void setHeight(String value) /*-{ this.height = value; }-*/;
public final native void clearHeight() /*-{ this.height = ""; }-*/;
public final native void setHeight(double value, String unit) /*-{ this.height = value + unit; }-*/;
public final native String getImageRendering() /*-{ return this.imageRendering; }-*/;
public final native void setImageRendering(String value) /*-{ this.imageRendering = value; }-*/;
public final native void clearImageRendering() /*-{ this.imageRendering = ""; }-*/;
public final native String getLeft() /*-{ return this.left; }-*/;
public final native void setLeft(String value) /*-{ this.left = value; }-*/;
public final native void clearLeft() /*-{ this.left = ""; }-*/;
public final native void setLeft(double value, String unit) /*-{ this.left = value + unit; }-*/;
public final native String getLetterSpacing() /*-{ return this.letterSpacing; }-*/;
public final native void setLetterSpacing(String value) /*-{ this.letterSpacing = value; }-*/;
public final native void clearLetterSpacing() /*-{ this.letterSpacing = ""; }-*/;
public final native String getListStyle() /*-{ return this.listStyle; }-*/;
public final native void setListStyle(String value) /*-{ this.listStyle = value; }-*/;
public final native void clearListStyle() /*-{ this.listStyle = ""; }-*/;
public final native String getListStyleType() /*-{ return this.listStyleType; }-*/;
public final native void setListStyleType(String value) /*-{ this.listStyleType = value; }-*/;
public final native void clearListStyleType() /*-{ this.listStyleType = ""; }-*/;
public final native String getListStyleImage() /*-{ return this.listStyleImage; }-*/;
public final native void setListStyleImage(String value) /*-{ this.listStyleImage = value; }-*/;
public final native void clearListStyleImage() /*-{ this.listStyleImage = ""; }-*/;
public final native String getListStylePosition() /*-{ return this.listStylePosition; }-*/;
public final native void setListStylePosition(String value) /*-{ this.listStylePosition = value; }-*/;
public final native void clearListStylePosition() /*-{ this.listStylePosition = ""; }-*/;
public final native String getMargin() /*-{ return this.margin; }-*/;
public final native void setMargin(String value) /*-{ this.margin = value; }-*/;
public final native void clearMargin() /*-{ this.margin = ""; }-*/;
public final native void setMargin(double value, String unit) /*-{ this.margin = value + unit; }-*/;
public final native String getMarginBottom() /*-{ return this.marginBottom; }-*/;
public final native void setMarginBottom(String value) /*-{ this.marginBottom = value; }-*/;
public final native void clearMarginBottom() /*-{ this.marginBottom = ""; }-*/;
public final native void setMarginBottom(double value, String unit) /*-{ this.marginBottom = value + unit; }-*/;
public final native String getMarginLeft() /*-{ return this.marginLeft; }-*/;
public final native void setMarginLeft(String value) /*-{ this.marginLeft = value; }-*/;
public final native void clearMarginLeft() /*-{ this.marginLeft = ""; }-*/;
public final native void setMarginLeft(double value, String unit) /*-{ this.marginLeft = value + unit; }-*/;
public final native String getMarginRight() /*-{ return this.marginRight; }-*/;
public final native void setMarginRight(String value) /*-{ this.marginRight = value; }-*/;
public final native void clearMarginRight() /*-{ this.marginRight = ""; }-*/;
public final native void setMarginRight(double value, String unit) /*-{ this.marginRight = value + unit; }-*/;
public final native String getMarginTop() /*-{ return this.marginTop; }-*/;
public final native void setMarginTop(String value) /*-{ this.marginTop = value; }-*/;
public final native void clearMarginTop() /*-{ this.marginTop = ""; }-*/;
public final native void setMarginTop(double value, String unit) /*-{ this.marginTop = value + unit; }-*/;
public final native String getMaxHeight() /*-{ return this.maxHeight; }-*/;
public final native void setMaxHeight(String value) /*-{ this.maxHeight = value; }-*/;
public final native void clearMaxHeight() /*-{ this.maxHeight = ""; }-*/;
public final native String getMaxWidth() /*-{ return this.maxWidth; }-*/;
public final native void setMaxWidth(String value) /*-{ this.maxWidth = value; }-*/;
public final native void clearMaxWidth() /*-{ this.maxWidth = ""; }-*/;
public final native String getMinHeight() /*-{ return this.minHeight; }-*/;
public final native void setMinHeight(String value) /*-{ this.minHeight = value; }-*/;
public final native void clearMinHeight() /*-{ this.minHeight = ""; }-*/;
public final native String getMinWidth() /*-{ return this.minWidth; }-*/;
public final native void setMinWidth(String value) /*-{ this.minWidth = value; }-*/;
public final native void clearMinWidth() /*-{ this.minWidth = ""; }-*/;
public final native double getOpacity() /*-{ return this.opacity; }-*/;
public final native void setOpacity(double value) /*-{ this.opacity = value; }-*/;
public final native void clearOpacity() /*-{ this.opacity = ""; }-*/;
public final native String getOrphans() /*-{ return this.orphans; }-*/;
public final native void setOrphans(String value) /*-{ this.orphans = value; }-*/;
public final native void clearOrphans() /*-{ this.orphans = ""; }-*/;
public final native String getOutline() /*-{ return this.outline; }-*/;
public final native void setOutline(String value) /*-{ this.outline = value; }-*/;
public final native void clearOutline() /*-{ this.outline = ""; }-*/;
public final native String getOutlineColor() /*-{ return this.outlineColor; }-*/;
public final native void setOutlineColor(String value) /*-{ this.outlineColor = value; }-*/;
public final native void clearOutlineColor() /*-{ this.outlineColor = ""; }-*/;
public final native String getOutlineOffset() /*-{ return this.outlineOffset; }-*/;
public final native void setOutlineOffset(String value) /*-{ this.outlineOffset = value; }-*/;
public final native void clearOutlineOffset() /*-{ this.outlineOffset = ""; }-*/;
public final native String getOutlineStyle() /*-{ return this.outlineStyle; }-*/;
public final native void setOutlineStyle(String value) /*-{ this.outlineStyle = value; }-*/;
public final native void clearOutlineStyle() /*-{ this.outlineStyle = ""; }-*/;
public final native String getOutlineWidth() /*-{ return this.outlineWidth; }-*/;
public final native void setOutlineWidth(String value) /*-{ this.outlineWidth = value; }-*/;
public final native void clearOutlineWidth() /*-{ this.outlineWidth = ""; }-*/;
public final native String getOverflow() /*-{ return this.overflow; }-*/;
public final native void setOverflow(String value) /*-{ this.overflow = value; }-*/;
public final native void clearOverflow() /*-{ this.overflow = ""; }-*/;
public final native String getOverflowX() /*-{ return this.overflowX; }-*/;
public final native void setOverflowX(String value) /*-{ this.overflowX = value; }-*/;
public final native void clearOverflowX() /*-{ this.overflowX = ""; }-*/;
public final native String getOverflowY() /*-{ return this.overflowY; }-*/;
public final native void setOverflowY(String value) /*-{ this.overflowY = value; }-*/;
public final native void clearOverflowY() /*-{ this.overflowY = ""; }-*/;
public final native String getPadding() /*-{ return this.padding; }-*/;
public final native void setPadding(String value) /*-{ this.padding = value; }-*/;
public final native void clearPadding() /*-{ this.padding = ""; }-*/;
public final native void setPadding(double value, String unit) /*-{ this.padding = value + unit; }-*/;
public final native String getPaddingBottom() /*-{ return this.paddingBottom; }-*/;
public final native void setPaddingBottom(String value) /*-{ this.paddingBottom = value; }-*/;
public final native void clearPaddingBottom() /*-{ this.paddingBottom = ""; }-*/;
public final native void setPaddingBottom(double value, String unit) /*-{ this.paddingBottom = value + unit; }-*/;
public final native String getPaddingLeft() /*-{ return this.paddingLeft; }-*/;
public final native void setPaddingLeft(String value) /*-{ this.paddingLeft = value; }-*/;
public final native void clearPaddingLeft() /*-{ this.paddingLeft = ""; }-*/;
public final native void setPaddingLeft(double value, String unit) /*-{ this.paddingLeft = value + unit; }-*/;
public final native String getPaddingRight() /*-{ return this.paddingRight; }-*/;
public final native void setPaddingRight(String value) /*-{ this.paddingRight = value; }-*/;
public final native void clearPaddingRight() /*-{ this.paddingRight = ""; }-*/;
public final native void setPaddingRight(double value, String unit) /*-{ this.paddingRight = value + unit; }-*/;
public final native String getPaddingTop() /*-{ return this.paddingTop; }-*/;
public final native void setPaddingTop(String value) /*-{ this.paddingTop = value; }-*/;
public final native void clearPaddingTop() /*-{ this.paddingTop = ""; }-*/;
public final native void setPaddingTop(double value, String unit) /*-{ this.paddingTop = value + unit; }-*/;
public final native String getPage() /*-{ return this.page; }-*/;
public final native void setPage(String value) /*-{ this.page = value; }-*/;
public final native void clearPage() /*-{ this.page = ""; }-*/;
public final native String getPageBreakAfter() /*-{ return this.pageBreakAfter; }-*/;
public final native void setPageBreakAfter(String value) /*-{ this.pageBreakAfter = value; }-*/;
public final native void clearPageBreakAfter() /*-{ this.pageBreakAfter = ""; }-*/;
public final native String getPageBreakBefore() /*-{ return this.pageBreakBefore; }-*/;
public final native void setPageBreakBefore(String value) /*-{ this.pageBreakBefore = value; }-*/;
public final native void clearPageBreakBefore() /*-{ this.pageBreakBefore = ""; }-*/;
public final native String getPageBreakInside() /*-{ return this.pageBreakInside; }-*/;
public final native void setPageBreakInside(String value) /*-{ this.pageBreakInside = value; }-*/;
public final native void clearPageBreakInside() /*-{ this.pageBreakInside = ""; }-*/;
public final native String getPointerEvents() /*-{ return this.pointerEvents; }-*/;
public final native void setPointerEvents(String value) /*-{ this.pointerEvents = value; }-*/;
public final native void clearPointerEvents() /*-{ this.pointerEvents = ""; }-*/;
public final native String getPosition() /*-{ return this.position; }-*/;
public final native void setPosition(String value) /*-{ this.position = value; }-*/;
public final native void clearPosition() /*-{ this.position = ""; }-*/;
public final native String getQuotes() /*-{ return this.quotes; }-*/;
public final native void setQuotes(String value) /*-{ this.quotes = value; }-*/;
public final native void clearQuotes() /*-{ this.quotes = ""; }-*/;
public final native String getResize() /*-{ return this.resize; }-*/;
public final native void setResize(String value) /*-{ this.resize = value; }-*/;
public final native void clearResize() /*-{ this.resize = ""; }-*/;
public final native String getRight() /*-{ return this.right; }-*/;
public final native void setRight(String value) /*-{ this.right = value; }-*/;
public final native void clearRight() /*-{ this.right = ""; }-*/;
public final native void setRight(double value, String unit) /*-{ this.right = value + unit; }-*/;
public final native String getSize() /*-{ return this.size; }-*/;
public final native void setSize(String value) /*-{ this.size = value; }-*/;
public final native void clearSize() /*-{ this.size = ""; }-*/;
public final native String getSrc() /*-{ return this.src; }-*/;
public final native void setSrc(String value) /*-{ this.src = value; }-*/;
public final native void clearSrc() /*-{ this.src = ""; }-*/;
public final native String getSpeak() /*-{ return this.speak; }-*/;
public final native void setSpeak(String value) /*-{ this.speak = value; }-*/;
public final native void clearSpeak() /*-{ this.speak = ""; }-*/;
public final native String getTableLayout() /*-{ return this.tableLayout; }-*/;
public final native void setTableLayout(String value) /*-{ this.tableLayout = value; }-*/;
public final native void clearTableLayout() /*-{ this.tableLayout = ""; }-*/;
public final native String getTabSize() /*-{ return this.tabSize; }-*/;
public final native void setTabSize(String value) /*-{ this.tabSize = value; }-*/;
public final native void clearTabSize() /*-{ this.tabSize = ""; }-*/;
public final native String getTextAlign() /*-{ return this.textAlign; }-*/;
public final native void setTextAlign(String value) /*-{ this.textAlign = value; }-*/;
public final native void clearTextAlign() /*-{ this.textAlign = ""; }-*/;
public final native String getTextDecoration() /*-{ return this.textDecoration; }-*/;
public final native void setTextDecoration(String value) /*-{ this.textDecoration = value; }-*/;
public final native void clearTextDecoration() /*-{ this.textDecoration = ""; }-*/;
public final native String getTextIndent() /*-{ return this.textIndent; }-*/;
public final native void setTextIndent(String value) /*-{ this.textIndent = value; }-*/;
public final native void clearTextIndent() /*-{ this.textIndent = ""; }-*/;
public final native String getTextLineThrough() /*-{ return this.textLineThrough; }-*/;
public final native void setTextLineThrough(String value) /*-{ this.textLineThrough = value; }-*/;
public final native void clearTextLineThrough() /*-{ this.textLineThrough = ""; }-*/;
public final native String getTextLineThroughColor() /*-{ return this.textLineThroughColor; }-*/;
public final native void setTextLineThroughColor(String value) /*-{ this.textLineThroughColor = value; }-*/;
public final native void clearTextLineThroughColor() /*-{ this.textLineThroughColor = ""; }-*/;
public final native String getTextLineThroughMode() /*-{ return this.textLineThroughMode; }-*/;
public final native void setTextLineThroughMode(String value) /*-{ this.textLineThroughMode = value; }-*/;
public final native void clearTextLineThroughMode() /*-{ this.textLineThroughMode = ""; }-*/;
public final native String getTextLineThroughStyle() /*-{ return this.textLineThroughStyle; }-*/;
public final native void setTextLineThroughStyle(String value) /*-{ this.textLineThroughStyle = value; }-*/;
public final native void clearTextLineThroughStyle() /*-{ this.textLineThroughStyle = ""; }-*/;
public final native String getTextLineThroughWidth() /*-{ return this.textLineThroughWidth; }-*/;
public final native void setTextLineThroughWidth(String value) /*-{ this.textLineThroughWidth = value; }-*/;
public final native void clearTextLineThroughWidth() /*-{ this.textLineThroughWidth = ""; }-*/;
public final native String getTextOverflow() /*-{ return this.textOverflow; }-*/;
public final native void setTextOverflow(String value) /*-{ this.textOverflow = value; }-*/;
public final native void clearTextOverflow() /*-{ this.textOverflow = ""; }-*/;
public final native String getTextOverline() /*-{ return this.textOverline; }-*/;
public final native void setTextOverline(String value) /*-{ this.textOverline = value; }-*/;
public final native void clearTextOverline() /*-{ this.textOverline = ""; }-*/;
public final native String getTextOverlineColor() /*-{ return this.textOverlineColor; }-*/;
public final native void setTextOverlineColor(String value) /*-{ this.textOverlineColor = value; }-*/;
public final native void clearTextOverlineColor() /*-{ this.textOverlineColor = ""; }-*/;
public final native String getTextOverlineMode() /*-{ return this.textOverlineMode; }-*/;
public final native void setTextOverlineMode(String value) /*-{ this.textOverlineMode = value; }-*/;
public final native void clearTextOverlineMode() /*-{ this.textOverlineMode = ""; }-*/;
public final native String getTextOverlineStyle() /*-{ return this.textOverlineStyle; }-*/;
public final native void setTextOverlineStyle(String value) /*-{ this.textOverlineStyle = value; }-*/;
public final native void clearTextOverlineStyle() /*-{ this.textOverlineStyle = ""; }-*/;
public final native String getTextOverlineWidth() /*-{ return this.textOverlineWidth; }-*/;
public final native void setTextOverlineWidth(String value) /*-{ this.textOverlineWidth = value; }-*/;
public final native void clearTextOverlineWidth() /*-{ this.textOverlineWidth = ""; }-*/;
public final native String getTextShadow() /*-{ return this.textShadow; }-*/;
public final native void setTextShadow(String value) /*-{ this.textShadow = value; }-*/;
public final native void clearTextShadow() /*-{ this.textShadow = ""; }-*/;
public final native String getTextTransform() /*-{ return this.textTransform; }-*/;
public final native void setTextTransform(String value) /*-{ this.textTransform = value; }-*/;
public final native void clearTextTransform() /*-{ this.textTransform = ""; }-*/;
public final native String getTextUnderline() /*-{ return this.textUnderline; }-*/;
public final native void setTextUnderline(String value) /*-{ this.textUnderline = value; }-*/;
public final native void clearTextUnderline() /*-{ this.textUnderline = ""; }-*/;
public final native String getTextUnderlineColor() /*-{ return this.textUnderlineColor; }-*/;
public final native void setTextUnderlineColor(String value) /*-{ this.textUnderlineColor = value; }-*/;
public final native void clearTextUnderlineColor() /*-{ this.textUnderlineColor = ""; }-*/;
public final native String getTextUnderlineMode() /*-{ return this.textUnderlineMode; }-*/;
public final native void setTextUnderlineMode(String value) /*-{ this.textUnderlineMode = value; }-*/;
public final native void clearTextUnderlineMode() /*-{ this.textUnderlineMode = ""; }-*/;
public final native String getTextUnderlineStyle() /*-{ return this.textUnderlineStyle; }-*/;
public final native void setTextUnderlineStyle(String value) /*-{ this.textUnderlineStyle = value; }-*/;
public final native void clearTextUnderlineStyle() /*-{ this.textUnderlineStyle = ""; }-*/;
public final native String getTextUnderlineWidth() /*-{ return this.textUnderlineWidth; }-*/;
public final native void setTextUnderlineWidth(String value) /*-{ this.textUnderlineWidth = value; }-*/;
public final native void clearTextUnderlineWidth() /*-{ this.textUnderlineWidth = ""; }-*/;
public final native String getTop() /*-{ return this.top; }-*/;
public final native void setTop(String value) /*-{ this.top = value; }-*/;
public final native void clearTop() /*-{ this.top = ""; }-*/;
public final native void setTop(double value, String unit) /*-{ this.top = value + unit; }-*/;
public final native String getUnicodeBidi() /*-{ return this.unicodeBidi; }-*/;
public final native void setUnicodeBidi(String value) /*-{ this.unicodeBidi = value; }-*/;
public final native void clearUnicodeBidi() /*-{ this.unicodeBidi = ""; }-*/;
public final native String getUnicodeRange() /*-{ return this.unicodeRange; }-*/;
public final native void setUnicodeRange(String value) /*-{ this.unicodeRange = value; }-*/;
public final native void clearUnicodeRange() /*-{ this.unicodeRange = ""; }-*/;
public final native String getVerticalAlign() /*-{ return this.verticalAlign; }-*/;
public final native void setVerticalAlign(String value) /*-{ this.verticalAlign = value; }-*/;
public final native void clearVerticalAlign() /*-{ this.verticalAlign = ""; }-*/;
public final native String getVisibility() /*-{ return this.visibility; }-*/;
public final native void setVisibility(String value) /*-{ this.visibility = value; }-*/;
public final native void clearVisibility() /*-{ this.visibility = ""; }-*/;
public final native String getWhiteSpace() /*-{ return this.whiteSpace; }-*/;
public final native void setWhiteSpace(String value) /*-{ this.whiteSpace = value; }-*/;
public final native void clearWhiteSpace() /*-{ this.whiteSpace = ""; }-*/;
public final native String getWidows() /*-{ return this.widows; }-*/;
public final native void setWidows(String value) /*-{ this.widows = value; }-*/;
public final native void clearWidows() /*-{ this.widows = ""; }-*/;
public final native String getWidth() /*-{ return this.width; }-*/;
public final native void setWidth(String value) /*-{ this.width = value; }-*/;
public final native void clearWidth() /*-{ this.width = ""; }-*/;
public final native void setWidth(double value, String unit) /*-{ this.width = value + unit; }-*/;
public final native String getWordBreak() /*-{ return this.wordBreak; }-*/;
public final native void setWordBreak(String value) /*-{ this.wordBreak = value; }-*/;
public final native void clearWordBreak() /*-{ this.wordBreak = ""; }-*/;
public final native String getWordSpacing() /*-{ return this.wordSpacing; }-*/;
public final native void setWordSpacing(String value) /*-{ this.wordSpacing = value; }-*/;
public final native void clearWordSpacing() /*-{ this.wordSpacing = ""; }-*/;
public final native String getWordWrap() /*-{ return this.wordWrap; }-*/;
public final native void setWordWrap(String value) /*-{ this.wordWrap = value; }-*/;
public final native void clearWordWrap() /*-{ this.wordWrap = ""; }-*/;
public final native int getZIndex() /*-{ return this.zIndex; }-*/;
public final native void setZIndex(int value) /*-{ this.zIndex = value; }-*/;
public final native void clearZIndex() /*-{ this.zIndex = ""; }-*/;
public final native String getWebkitAnimation() /*-{ return this.webkitAnimation; }-*/;
public final native void setWebkitAnimation(String value) /*-{ this.webkitAnimation = value; }-*/;
public final native void clearWebkitAnimation() /*-{ this.webkitAnimation = ""; }-*/;
public final native String getWebkitAnimationDelay() /*-{ return this.webkitAnimationDelay; }-*/;
public final native void setWebkitAnimationDelay(String value) /*-{ this.webkitAnimationDelay = value; }-*/;
public final native void clearWebkitAnimationDelay() /*-{ this.webkitAnimationDelay = ""; }-*/;
public final native String getWebkitAnimationDirection() /*-{ return this.webkitAnimationDirection; }-*/;
public final native void setWebkitAnimationDirection(String value) /*-{ this.webkitAnimationDirection = value; }-*/;
public final native void clearWebkitAnimationDirection() /*-{ this.webkitAnimationDirection = ""; }-*/;
public final native String getWebkitAnimationDuration() /*-{ return this.webkitAnimationDuration; }-*/;
public final native void setWebkitAnimationDuration(String value) /*-{ this.webkitAnimationDuration = value; }-*/;
public final native void clearWebkitAnimationDuration() /*-{ this.webkitAnimationDuration = ""; }-*/;
public final native String getWebkitAnimationFillMode() /*-{ return this.webkitAnimationFillMode; }-*/;
public final native void setWebkitAnimationFillMode(String value) /*-{ this.webkitAnimationFillMode = value; }-*/;
public final native void clearWebkitAnimationFillMode() /*-{ this.webkitAnimationFillMode = ""; }-*/;
public final native String getWebkitAnimationIterationCount() /*-{ return this.webkitAnimationIterationCount; }-*/;
public final native void setWebkitAnimationIterationCount(String value) /*-{ this.webkitAnimationIterationCount = value; }-*/;
public final native void clearWebkitAnimationIterationCount() /*-{ this.webkitAnimationIterationCount = ""; }-*/;
public final native String getWebkitAnimationName() /*-{ return this.webkitAnimationName; }-*/;
public final native void setWebkitAnimationName(String value) /*-{ this.webkitAnimationName = value; }-*/;
public final native void clearWebkitAnimationName() /*-{ this.webkitAnimationName = ""; }-*/;
public final native String getWebkitAnimationPlayState() /*-{ return this.webkitAnimationPlayState; }-*/;
public final native void setWebkitAnimationPlayState(String value) /*-{ this.webkitAnimationPlayState = value; }-*/;
public final native void clearWebkitAnimationPlayState() /*-{ this.webkitAnimationPlayState = ""; }-*/;
public final native String getWebkitAnimationTimingFunction() /*-{ return this.webkitAnimationTimingFunction; }-*/;
public final native void setWebkitAnimationTimingFunction(String value) /*-{ this.webkitAnimationTimingFunction = value; }-*/;
public final native void clearWebkitAnimationTimingFunction() /*-{ this.webkitAnimationTimingFunction = ""; }-*/;
public final native String getWebkitAppearance() /*-{ return this.webkitAppearance; }-*/;
public final native void setWebkitAppearance(String value) /*-{ this.webkitAppearance = value; }-*/;
public final native void clearWebkitAppearance() /*-{ this.webkitAppearance = ""; }-*/;
public final native String getWebkitAspectRatio() /*-{ return this.webkitAspectRatio; }-*/;
public final native void setWebkitAspectRatio(String value) /*-{ this.webkitAspectRatio = value; }-*/;
public final native void clearWebkitAspectRatio() /*-{ this.webkitAspectRatio = ""; }-*/;
public final native String getWebkitBackfaceVisibility() /*-{ return this.webkitBackfaceVisibility; }-*/;
public final native void setWebkitBackfaceVisibility(String value) /*-{ this.webkitBackfaceVisibility = value; }-*/;
public final native void clearWebkitBackfaceVisibility() /*-{ this.webkitBackfaceVisibility = ""; }-*/;
public final native String getWebkitBackgroundClip() /*-{ return this.webkitBackgroundClip; }-*/;
public final native void setWebkitBackgroundClip(String value) /*-{ this.webkitBackgroundClip = value; }-*/;
public final native void clearWebkitBackgroundClip() /*-{ this.webkitBackgroundClip = ""; }-*/;
public final native String getWebkitBackgroundComposite() /*-{ return this.webkitBackgroundComposite; }-*/;
public final native void setWebkitBackgroundComposite(String value) /*-{ this.webkitBackgroundComposite = value; }-*/;
public final native void clearWebkitBackgroundComposite() /*-{ this.webkitBackgroundComposite = ""; }-*/;
public final native String getWebkitBackgroundOrigin() /*-{ return this.webkitBackgroundOrigin; }-*/;
public final native void setWebkitBackgroundOrigin(String value) /*-{ this.webkitBackgroundOrigin = value; }-*/;
public final native void clearWebkitBackgroundOrigin() /*-{ this.webkitBackgroundOrigin = ""; }-*/;
public final native String getWebkitBackgroundSize() /*-{ return this.webkitBackgroundSize; }-*/;
public final native void setWebkitBackgroundSize(String value) /*-{ this.webkitBackgroundSize = value; }-*/;
public final native void clearWebkitBackgroundSize() /*-{ this.webkitBackgroundSize = ""; }-*/;
public final native String getWebkitBorderAfter() /*-{ return this.webkitBorderAfter; }-*/;
public final native void setWebkitBorderAfter(String value) /*-{ this.webkitBorderAfter = value; }-*/;
public final native void clearWebkitBorderAfter() /*-{ this.webkitBorderAfter = ""; }-*/;
public final native String getWebkitBorderAfterColor() /*-{ return this.webkitBorderAfterColor; }-*/;
public final native void setWebkitBorderAfterColor(String value) /*-{ this.webkitBorderAfterColor = value; }-*/;
public final native void clearWebkitBorderAfterColor() /*-{ this.webkitBorderAfterColor = ""; }-*/;
public final native String getWebkitBorderAfterStyle() /*-{ return this.webkitBorderAfterStyle; }-*/;
public final native void setWebkitBorderAfterStyle(String value) /*-{ this.webkitBorderAfterStyle = value; }-*/;
public final native void clearWebkitBorderAfterStyle() /*-{ this.webkitBorderAfterStyle = ""; }-*/;
public final native String getWebkitBorderAfterWidth() /*-{ return this.webkitBorderAfterWidth; }-*/;
public final native void setWebkitBorderAfterWidth(String value) /*-{ this.webkitBorderAfterWidth = value; }-*/;
public final native void clearWebkitBorderAfterWidth() /*-{ this.webkitBorderAfterWidth = ""; }-*/;
public final native String getWebkitBorderBefore() /*-{ return this.webkitBorderBefore; }-*/;
public final native void setWebkitBorderBefore(String value) /*-{ this.webkitBorderBefore = value; }-*/;
public final native void clearWebkitBorderBefore() /*-{ this.webkitBorderBefore = ""; }-*/;
public final native String getWebkitBorderBeforeColor() /*-{ return this.webkitBorderBeforeColor; }-*/;
public final native void setWebkitBorderBeforeColor(String value) /*-{ this.webkitBorderBeforeColor = value; }-*/;
public final native void clearWebkitBorderBeforeColor() /*-{ this.webkitBorderBeforeColor = ""; }-*/;
public final native String getWebkitBorderBeforeStyle() /*-{ return this.webkitBorderBeforeStyle; }-*/;
public final native void setWebkitBorderBeforeStyle(String value) /*-{ this.webkitBorderBeforeStyle = value; }-*/;
public final native void clearWebkitBorderBeforeStyle() /*-{ this.webkitBorderBeforeStyle = ""; }-*/;
public final native String getWebkitBorderBeforeWidth() /*-{ return this.webkitBorderBeforeWidth; }-*/;
public final native void setWebkitBorderBeforeWidth(String value) /*-{ this.webkitBorderBeforeWidth = value; }-*/;
public final native void clearWebkitBorderBeforeWidth() /*-{ this.webkitBorderBeforeWidth = ""; }-*/;
public final native String getWebkitBorderEnd() /*-{ return this.webkitBorderEnd; }-*/;
public final native void setWebkitBorderEnd(String value) /*-{ this.webkitBorderEnd = value; }-*/;
public final native void clearWebkitBorderEnd() /*-{ this.webkitBorderEnd = ""; }-*/;
public final native String getWebkitBorderEndColor() /*-{ return this.webkitBorderEndColor; }-*/;
public final native void setWebkitBorderEndColor(String value) /*-{ this.webkitBorderEndColor = value; }-*/;
public final native void clearWebkitBorderEndColor() /*-{ this.webkitBorderEndColor = ""; }-*/;
public final native String getWebkitBorderEndStyle() /*-{ return this.webkitBorderEndStyle; }-*/;
public final native void setWebkitBorderEndStyle(String value) /*-{ this.webkitBorderEndStyle = value; }-*/;
public final native void clearWebkitBorderEndStyle() /*-{ this.webkitBorderEndStyle = ""; }-*/;
public final native String getWebkitBorderEndWidth() /*-{ return this.webkitBorderEndWidth; }-*/;
public final native void setWebkitBorderEndWidth(String value) /*-{ this.webkitBorderEndWidth = value; }-*/;
public final native void clearWebkitBorderEndWidth() /*-{ this.webkitBorderEndWidth = ""; }-*/;
public final native String getWebkitBorderFit() /*-{ return this.webkitBorderFit; }-*/;
public final native void setWebkitBorderFit(String value) /*-{ this.webkitBorderFit = value; }-*/;
public final native void clearWebkitBorderFit() /*-{ this.webkitBorderFit = ""; }-*/;
public final native String getWebkitBorderHorizontalSpacing() /*-{ return this.webkitBorderHorizontalSpacing; }-*/;
public final native void setWebkitBorderHorizontalSpacing(String value) /*-{ this.webkitBorderHorizontalSpacing = value; }-*/;
public final native void clearWebkitBorderHorizontalSpacing() /*-{ this.webkitBorderHorizontalSpacing = ""; }-*/;
public final native String getWebkitBorderImage() /*-{ return this.webkitBorderImage; }-*/;
public final native void setWebkitBorderImage(String value) /*-{ this.webkitBorderImage = value; }-*/;
public final native void clearWebkitBorderImage() /*-{ this.webkitBorderImage = ""; }-*/;
public final native String getWebkitBorderRadius() /*-{ return this.webkitBorderRadius; }-*/;
public final native void setWebkitBorderRadius(String value) /*-{ this.webkitBorderRadius = value; }-*/;
public final native void clearWebkitBorderRadius() /*-{ this.webkitBorderRadius = ""; }-*/;
public final native String getWebkitBorderStart() /*-{ return this.webkitBorderStart; }-*/;
public final native void setWebkitBorderStart(String value) /*-{ this.webkitBorderStart = value; }-*/;
public final native void clearWebkitBorderStart() /*-{ this.webkitBorderStart = ""; }-*/;
public final native String getWebkitBorderStartColor() /*-{ return this.webkitBorderStartColor; }-*/;
public final native void setWebkitBorderStartColor(String value) /*-{ this.webkitBorderStartColor = value; }-*/;
public final native void clearWebkitBorderStartColor() /*-{ this.webkitBorderStartColor = ""; }-*/;
public final native String getWebkitBorderStartStyle() /*-{ return this.webkitBorderStartStyle; }-*/;
public final native void setWebkitBorderStartStyle(String value) /*-{ this.webkitBorderStartStyle = value; }-*/;
public final native void clearWebkitBorderStartStyle() /*-{ this.webkitBorderStartStyle = ""; }-*/;
public final native String getWebkitBorderStartWidth() /*-{ return this.webkitBorderStartWidth; }-*/;
public final native void setWebkitBorderStartWidth(String value) /*-{ this.webkitBorderStartWidth = value; }-*/;
public final native void clearWebkitBorderStartWidth() /*-{ this.webkitBorderStartWidth = ""; }-*/;
public final native String getWebkitBorderVerticalSpacing() /*-{ return this.webkitBorderVerticalSpacing; }-*/;
public final native void setWebkitBorderVerticalSpacing(String value) /*-{ this.webkitBorderVerticalSpacing = value; }-*/;
public final native void clearWebkitBorderVerticalSpacing() /*-{ this.webkitBorderVerticalSpacing = ""; }-*/;
public final native String getWebkitBoxAlign() /*-{ return this.webkitBoxAlign; }-*/;
public final native void setWebkitBoxAlign(String value) /*-{ this.webkitBoxAlign = value; }-*/;
public final native void clearWebkitBoxAlign() /*-{ this.webkitBoxAlign = ""; }-*/;
public final native String getWebkitBoxDirection() /*-{ return this.webkitBoxDirection; }-*/;
public final native void setWebkitBoxDirection(String value) /*-{ this.webkitBoxDirection = value; }-*/;
public final native void clearWebkitBoxDirection() /*-{ this.webkitBoxDirection = ""; }-*/;
public final native String getWebkitBoxFlex() /*-{ return this.webkitBoxFlex; }-*/;
public final native void setWebkitBoxFlex(String value) /*-{ this.webkitBoxFlex = value; }-*/;
public final native void clearWebkitBoxFlex() /*-{ this.webkitBoxFlex = ""; }-*/;
public final native String getWebkitBoxFlexGroup() /*-{ return this.webkitBoxFlexGroup; }-*/;
public final native void setWebkitBoxFlexGroup(String value) /*-{ this.webkitBoxFlexGroup = value; }-*/;
public final native void clearWebkitBoxFlexGroup() /*-{ this.webkitBoxFlexGroup = ""; }-*/;
public final native String getWebkitBoxLines() /*-{ return this.webkitBoxLines; }-*/;
public final native void setWebkitBoxLines(String value) /*-{ this.webkitBoxLines = value; }-*/;
public final native void clearWebkitBoxLines() /*-{ this.webkitBoxLines = ""; }-*/;
public final native String getWebkitBoxOrdinalGroup() /*-{ return this.webkitBoxOrdinalGroup; }-*/;
public final native void setWebkitBoxOrdinalGroup(String value) /*-{ this.webkitBoxOrdinalGroup = value; }-*/;
public final native void clearWebkitBoxOrdinalGroup() /*-{ this.webkitBoxOrdinalGroup = ""; }-*/;
public final native String getWebkitBoxOrient() /*-{ return this.webkitBoxOrient; }-*/;
public final native void setWebkitBoxOrient(String value) /*-{ this.webkitBoxOrient = value; }-*/;
public final native void clearWebkitBoxOrient() /*-{ this.webkitBoxOrient = ""; }-*/;
public final native String getWebkitBoxPack() /*-{ return this.webkitBoxPack; }-*/;
public final native void setWebkitBoxPack(String value) /*-{ this.webkitBoxPack = value; }-*/;
public final native void clearWebkitBoxPack() /*-{ this.webkitBoxPack = ""; }-*/;
public final native String getWebkitBoxReflect() /*-{ return this.webkitBoxReflect; }-*/;
public final native void setWebkitBoxReflect(String value) /*-{ this.webkitBoxReflect = value; }-*/;
public final native void clearWebkitBoxReflect() /*-{ this.webkitBoxReflect = ""; }-*/;
public final native String getWebkitBoxShadow() /*-{ return this.webkitBoxShadow; }-*/;
public final native void setWebkitBoxShadow(String value) /*-{ this.webkitBoxShadow = value; }-*/;
public final native void clearWebkitBoxShadow() /*-{ this.webkitBoxShadow = ""; }-*/;
public final native String getWebkitColorCorrection() /*-{ return this.webkitColorCorrection; }-*/;
public final native void setWebkitColorCorrection(String value) /*-{ this.webkitColorCorrection = value; }-*/;
public final native void clearWebkitColorCorrection() /*-{ this.webkitColorCorrection = ""; }-*/;
public final native String getWebkitColumnAxis() /*-{ return this.webkitColumnAxis; }-*/;
public final native void setWebkitColumnAxis(String value) /*-{ this.webkitColumnAxis = value; }-*/;
public final native void clearWebkitColumnAxis() /*-{ this.webkitColumnAxis = ""; }-*/;
public final native String getWebkitColumnBreakAfter() /*-{ return this.webkitColumnBreakAfter; }-*/;
public final native void setWebkitColumnBreakAfter(String value) /*-{ this.webkitColumnBreakAfter = value; }-*/;
public final native void clearWebkitColumnBreakAfter() /*-{ this.webkitColumnBreakAfter = ""; }-*/;
public final native String getWebkitColumnBreakBefore() /*-{ return this.webkitColumnBreakBefore; }-*/;
public final native void setWebkitColumnBreakBefore(String value) /*-{ this.webkitColumnBreakBefore = value; }-*/;
public final native void clearWebkitColumnBreakBefore() /*-{ this.webkitColumnBreakBefore = ""; }-*/;
public final native String getWebkitColumnBreakInside() /*-{ return this.webkitColumnBreakInside; }-*/;
public final native void setWebkitColumnBreakInside(String value) /*-{ this.webkitColumnBreakInside = value; }-*/;
public final native void clearWebkitColumnBreakInside() /*-{ this.webkitColumnBreakInside = ""; }-*/;
public final native String getWebkitColumnCount() /*-{ return this.webkitColumnCount; }-*/;
public final native void setWebkitColumnCount(String value) /*-{ this.webkitColumnCount = value; }-*/;
public final native void clearWebkitColumnCount() /*-{ this.webkitColumnCount = ""; }-*/;
public final native String getWebkitColumnGap() /*-{ return this.webkitColumnGap; }-*/;
public final native void setWebkitColumnGap(String value) /*-{ this.webkitColumnGap = value; }-*/;
public final native void clearWebkitColumnGap() /*-{ this.webkitColumnGap = ""; }-*/;
public final native String getWebkitColumnRule() /*-{ return this.webkitColumnRule; }-*/;
public final native void setWebkitColumnRule(String value) /*-{ this.webkitColumnRule = value; }-*/;
public final native void clearWebkitColumnRule() /*-{ this.webkitColumnRule = ""; }-*/;
public final native String getWebkitColumnRuleColor() /*-{ return this.webkitColumnRuleColor; }-*/;
public final native void setWebkitColumnRuleColor(String value) /*-{ this.webkitColumnRuleColor = value; }-*/;
public final native void clearWebkitColumnRuleColor() /*-{ this.webkitColumnRuleColor = ""; }-*/;
public final native String getWebkitColumnRuleStyle() /*-{ return this.webkitColumnRuleStyle; }-*/;
public final native void setWebkitColumnRuleStyle(String value) /*-{ this.webkitColumnRuleStyle = value; }-*/;
public final native void clearWebkitColumnRuleStyle() /*-{ this.webkitColumnRuleStyle = ""; }-*/;
public final native String getWebkitColumnRuleWidth() /*-{ return this.webkitColumnRuleWidth; }-*/;
public final native void setWebkitColumnRuleWidth(String value) /*-{ this.webkitColumnRuleWidth = value; }-*/;
public final native void clearWebkitColumnRuleWidth() /*-{ this.webkitColumnRuleWidth = ""; }-*/;
public final native String getWebkitColumnSpan() /*-{ return this.webkitColumnSpan; }-*/;
public final native void setWebkitColumnSpan(String value) /*-{ this.webkitColumnSpan = value; }-*/;
public final native void clearWebkitColumnSpan() /*-{ this.webkitColumnSpan = ""; }-*/;
public final native String getWebkitColumnWidth() /*-{ return this.webkitColumnWidth; }-*/;
public final native void setWebkitColumnWidth(String value) /*-{ this.webkitColumnWidth = value; }-*/;
public final native void clearWebkitColumnWidth() /*-{ this.webkitColumnWidth = ""; }-*/;
public final native String getWebkitColumns() /*-{ return this.webkitColumns; }-*/;
public final native void setWebkitColumns(String value) /*-{ this.webkitColumns = value; }-*/;
public final native void clearWebkitColumns() /*-{ this.webkitColumns = ""; }-*/;
public final native String getWebkitFilter() /*-{ return this.webkitFilter; }-*/;
public final native void setWebkitFilter(String value) /*-{ this.webkitFilter = value; }-*/;
public final native void clearWebkitFilter() /*-{ this.webkitFilter = ""; }-*/;
public final native String getWebkitFlex() /*-{ return this.webkitFlex; }-*/;
public final native void setWebkitFlex(String value) /*-{ this.webkitFlex = value; }-*/;
public final native void clearWebkitFlex() /*-{ this.webkitFlex = ""; }-*/;
public final native String getWebkitFlexAlign() /*-{ return this.webkitFlexAlign; }-*/;
public final native void setWebkitFlexAlign(String value) /*-{ this.webkitFlexAlign = value; }-*/;
public final native void clearWebkitFlexAlign() /*-{ this.webkitFlexAlign = ""; }-*/;
public final native String getWebkitFlexDirection() /*-{ return this.webkitFlexDirection; }-*/;
public final native void setWebkitFlexDirection(String value) /*-{ this.webkitFlexDirection = value; }-*/;
public final native void clearWebkitFlexDirection() /*-{ this.webkitFlexDirection = ""; }-*/;
public final native String getWebkitFlexFlow() /*-{ return this.webkitFlexFlow; }-*/;
public final native void setWebkitFlexFlow(String value) /*-{ this.webkitFlexFlow = value; }-*/;
public final native void clearWebkitFlexFlow() /*-{ this.webkitFlexFlow = ""; }-*/;
public final native String getWebkitFlexItemAlign() /*-{ return this.webkitFlexItemAlign; }-*/;
public final native void setWebkitFlexItemAlign(String value) /*-{ this.webkitFlexItemAlign = value; }-*/;
public final native void clearWebkitFlexItemAlign() /*-{ this.webkitFlexItemAlign = ""; }-*/;
public final native String getWebkitFlexLinePack() /*-{ return this.webkitFlexLinePack; }-*/;
public final native void setWebkitFlexLinePack(String value) /*-{ this.webkitFlexLinePack = value; }-*/;
public final native void clearWebkitFlexLinePack() /*-{ this.webkitFlexLinePack = ""; }-*/;
public final native String getWebkitFlexOrder() /*-{ return this.webkitFlexOrder; }-*/;
public final native void setWebkitFlexOrder(String value) /*-{ this.webkitFlexOrder = value; }-*/;
public final native void clearWebkitFlexOrder() /*-{ this.webkitFlexOrder = ""; }-*/;
public final native String getWebkitFlexPack() /*-{ return this.webkitFlexPack; }-*/;
public final native void setWebkitFlexPack(String value) /*-{ this.webkitFlexPack = value; }-*/;
public final native void clearWebkitFlexPack() /*-{ this.webkitFlexPack = ""; }-*/;
public final native String getWebkitFlexWrap() /*-{ return this.webkitFlexWrap; }-*/;
public final native void setWebkitFlexWrap(String value) /*-{ this.webkitFlexWrap = value; }-*/;
public final native void clearWebkitFlexWrap() /*-{ this.webkitFlexWrap = ""; }-*/;
public final native String getWebkitFontSizeDelta() /*-{ return this.webkitFontSizeDelta; }-*/;
public final native void setWebkitFontSizeDelta(String value) /*-{ this.webkitFontSizeDelta = value; }-*/;
public final native void clearWebkitFontSizeDelta() /*-{ this.webkitFontSizeDelta = ""; }-*/;
public final native String getWebkitGridColumns() /*-{ return this.webkitGridColumns; }-*/;
public final native void setWebkitGridColumns(String value) /*-{ this.webkitGridColumns = value; }-*/;
public final native void clearWebkitGridColumns() /*-{ this.webkitGridColumns = ""; }-*/;
public final native String getWebkitGridRows() /*-{ return this.webkitGridRows; }-*/;
public final native void setWebkitGridRows(String value) /*-{ this.webkitGridRows = value; }-*/;
public final native void clearWebkitGridRows() /*-{ this.webkitGridRows = ""; }-*/;
public final native String getWebkitGridColumn() /*-{ return this.webkitGridColumn; }-*/;
public final native void setWebkitGridColumn(String value) /*-{ this.webkitGridColumn = value; }-*/;
public final native void clearWebkitGridColumn() /*-{ this.webkitGridColumn = ""; }-*/;
public final native String getWebkitGridRow() /*-{ return this.webkitGridRow; }-*/;
public final native void setWebkitGridRow(String value) /*-{ this.webkitGridRow = value; }-*/;
public final native void clearWebkitGridRow() /*-{ this.webkitGridRow = ""; }-*/;
public final native String getWebkitHighlight() /*-{ return this.webkitHighlight; }-*/;
public final native void setWebkitHighlight(String value) /*-{ this.webkitHighlight = value; }-*/;
public final native void clearWebkitHighlight() /*-{ this.webkitHighlight = ""; }-*/;
public final native String getWebkitHyphenateCharacter() /*-{ return this.webkitHyphenateCharacter; }-*/;
public final native void setWebkitHyphenateCharacter(String value) /*-{ this.webkitHyphenateCharacter = value; }-*/;
public final native void clearWebkitHyphenateCharacter() /*-{ this.webkitHyphenateCharacter = ""; }-*/;
public final native String getWebkitHyphenateLimitAfter() /*-{ return this.webkitHyphenateLimitAfter; }-*/;
public final native void setWebkitHyphenateLimitAfter(String value) /*-{ this.webkitHyphenateLimitAfter = value; }-*/;
public final native void clearWebkitHyphenateLimitAfter() /*-{ this.webkitHyphenateLimitAfter = ""; }-*/;
public final native String getWebkitHyphenateLimitBefore() /*-{ return this.webkitHyphenateLimitBefore; }-*/;
public final native void setWebkitHyphenateLimitBefore(String value) /*-{ this.webkitHyphenateLimitBefore = value; }-*/;
public final native void clearWebkitHyphenateLimitBefore() /*-{ this.webkitHyphenateLimitBefore = ""; }-*/;
public final native String getWebkitHyphenateLimitLines() /*-{ return this.webkitHyphenateLimitLines; }-*/;
public final native void setWebkitHyphenateLimitLines(String value) /*-{ this.webkitHyphenateLimitLines = value; }-*/;
public final native void clearWebkitHyphenateLimitLines() /*-{ this.webkitHyphenateLimitLines = ""; }-*/;
public final native String getWebkitHyphens() /*-{ return this.webkitHyphens; }-*/;
public final native void setWebkitHyphens(String value) /*-{ this.webkitHyphens = value; }-*/;
public final native void clearWebkitHyphens() /*-{ this.webkitHyphens = ""; }-*/;
public final native String getWebkitLineBoxContain() /*-{ return this.webkitLineBoxContain; }-*/;
public final native void setWebkitLineBoxContain(String value) /*-{ this.webkitLineBoxContain = value; }-*/;
public final native void clearWebkitLineBoxContain() /*-{ this.webkitLineBoxContain = ""; }-*/;
public final native String getWebkitLineAlign() /*-{ return this.webkitLineAlign; }-*/;
public final native void setWebkitLineAlign(String value) /*-{ this.webkitLineAlign = value; }-*/;
public final native void clearWebkitLineAlign() /*-{ this.webkitLineAlign = ""; }-*/;
public final native String getWebkitLineBreak() /*-{ return this.webkitLineBreak; }-*/;
public final native void setWebkitLineBreak(String value) /*-{ this.webkitLineBreak = value; }-*/;
public final native void clearWebkitLineBreak() /*-{ this.webkitLineBreak = ""; }-*/;
public final native String getWebkitLineClamp() /*-{ return this.webkitLineClamp; }-*/;
public final native void setWebkitLineClamp(String value) /*-{ this.webkitLineClamp = value; }-*/;
public final native void clearWebkitLineClamp() /*-{ this.webkitLineClamp = ""; }-*/;
public final native String getWebkitLineGrid() /*-{ return this.webkitLineGrid; }-*/;
public final native void setWebkitLineGrid(String value) /*-{ this.webkitLineGrid = value; }-*/;
public final native void clearWebkitLineGrid() /*-{ this.webkitLineGrid = ""; }-*/;
public final native String getWebkitLineSnap() /*-{ return this.webkitLineSnap; }-*/;
public final native void setWebkitLineSnap(String value) /*-{ this.webkitLineSnap = value; }-*/;
public final native void clearWebkitLineSnap() /*-{ this.webkitLineSnap = ""; }-*/;
public final native String getWebkitLogicalWidth() /*-{ return this.webkitLogicalWidth; }-*/;
public final native void setWebkitLogicalWidth(String value) /*-{ this.webkitLogicalWidth = value; }-*/;
public final native void clearWebkitLogicalWidth() /*-{ this.webkitLogicalWidth = ""; }-*/;
public final native String getWebkitLogicalHeight() /*-{ return this.webkitLogicalHeight; }-*/;
public final native void setWebkitLogicalHeight(String value) /*-{ this.webkitLogicalHeight = value; }-*/;
public final native void clearWebkitLogicalHeight() /*-{ this.webkitLogicalHeight = ""; }-*/;
public final native String getWebkitMarginAfterCollapse() /*-{ return this.webkitMarginAfterCollapse; }-*/;
public final native void setWebkitMarginAfterCollapse(String value) /*-{ this.webkitMarginAfterCollapse = value; }-*/;
public final native void clearWebkitMarginAfterCollapse() /*-{ this.webkitMarginAfterCollapse = ""; }-*/;
public final native String getWebkitMarginBeforeCollapse() /*-{ return this.webkitMarginBeforeCollapse; }-*/;
public final native void setWebkitMarginBeforeCollapse(String value) /*-{ this.webkitMarginBeforeCollapse = value; }-*/;
public final native void clearWebkitMarginBeforeCollapse() /*-{ this.webkitMarginBeforeCollapse = ""; }-*/;
public final native String getWebkitMarginBottomCollapse() /*-{ return this.webkitMarginBottomCollapse; }-*/;
public final native void setWebkitMarginBottomCollapse(String value) /*-{ this.webkitMarginBottomCollapse = value; }-*/;
public final native void clearWebkitMarginBottomCollapse() /*-{ this.webkitMarginBottomCollapse = ""; }-*/;
public final native String getWebkitMarginTopCollapse() /*-{ return this.webkitMarginTopCollapse; }-*/;
public final native void setWebkitMarginTopCollapse(String value) /*-{ this.webkitMarginTopCollapse = value; }-*/;
public final native void clearWebkitMarginTopCollapse() /*-{ this.webkitMarginTopCollapse = ""; }-*/;
public final native String getWebkitMarginCollapse() /*-{ return this.webkitMarginCollapse; }-*/;
public final native void setWebkitMarginCollapse(String value) /*-{ this.webkitMarginCollapse = value; }-*/;
public final native void clearWebkitMarginCollapse() /*-{ this.webkitMarginCollapse = ""; }-*/;
public final native String getWebkitMarginAfter() /*-{ return this.webkitMarginAfter; }-*/;
public final native void setWebkitMarginAfter(String value) /*-{ this.webkitMarginAfter = value; }-*/;
public final native void clearWebkitMarginAfter() /*-{ this.webkitMarginAfter = ""; }-*/;
public final native String getWebkitMarginBefore() /*-{ return this.webkitMarginBefore; }-*/;
public final native void setWebkitMarginBefore(String value) /*-{ this.webkitMarginBefore = value; }-*/;
public final native void clearWebkitMarginBefore() /*-{ this.webkitMarginBefore = ""; }-*/;
public final native String getWebkitMarginEnd() /*-{ return this.webkitMarginEnd; }-*/;
public final native void setWebkitMarginEnd(String value) /*-{ this.webkitMarginEnd = value; }-*/;
public final native void clearWebkitMarginEnd() /*-{ this.webkitMarginEnd = ""; }-*/;
public final native String getWebkitMarginStart() /*-{ return this.webkitMarginStart; }-*/;
public final native void setWebkitMarginStart(String value) /*-{ this.webkitMarginStart = value; }-*/;
public final native void clearWebkitMarginStart() /*-{ this.webkitMarginStart = ""; }-*/;
public final native String getWebkitMarquee() /*-{ return this.webkitMarquee; }-*/;
public final native void setWebkitMarquee(String value) /*-{ this.webkitMarquee = value; }-*/;
public final native void clearWebkitMarquee() /*-{ this.webkitMarquee = ""; }-*/;
public final native String getWebkitMarqueeDirection() /*-{ return this.webkitMarqueeDirection; }-*/;
public final native void setWebkitMarqueeDirection(String value) /*-{ this.webkitMarqueeDirection = value; }-*/;
public final native void clearWebkitMarqueeDirection() /*-{ this.webkitMarqueeDirection = ""; }-*/;
public final native String getWebkitMarqueeIncrement() /*-{ return this.webkitMarqueeIncrement; }-*/;
public final native void setWebkitMarqueeIncrement(String value) /*-{ this.webkitMarqueeIncrement = value; }-*/;
public final native void clearWebkitMarqueeIncrement() /*-{ this.webkitMarqueeIncrement = ""; }-*/;
public final native String getWebkitMarqueeRepetition() /*-{ return this.webkitMarqueeRepetition; }-*/;
public final native void setWebkitMarqueeRepetition(String value) /*-{ this.webkitMarqueeRepetition = value; }-*/;
public final native void clearWebkitMarqueeRepetition() /*-{ this.webkitMarqueeRepetition = ""; }-*/;
public final native String getWebkitMarqueeSpeed() /*-{ return this.webkitMarqueeSpeed; }-*/;
public final native void setWebkitMarqueeSpeed(String value) /*-{ this.webkitMarqueeSpeed = value; }-*/;
public final native void clearWebkitMarqueeSpeed() /*-{ this.webkitMarqueeSpeed = ""; }-*/;
public final native String getWebkitMarqueeStyle() /*-{ return this.webkitMarqueeStyle; }-*/;
public final native void setWebkitMarqueeStyle(String value) /*-{ this.webkitMarqueeStyle = value; }-*/;
public final native void clearWebkitMarqueeStyle() /*-{ this.webkitMarqueeStyle = ""; }-*/;
public final native String getWebkitMask() /*-{ return this.webkitMask; }-*/;
public final native void setWebkitMask(String value) /*-{ this.webkitMask = value; }-*/;
public final native void clearWebkitMask() /*-{ this.webkitMask = ""; }-*/;
public final native String getWebkitMaskAttachment() /*-{ return this.webkitMaskAttachment; }-*/;
public final native void setWebkitMaskAttachment(String value) /*-{ this.webkitMaskAttachment = value; }-*/;
public final native void clearWebkitMaskAttachment() /*-{ this.webkitMaskAttachment = ""; }-*/;
public final native String getWebkitMaskBoxImage() /*-{ return this.webkitMaskBoxImage; }-*/;
public final native void setWebkitMaskBoxImage(String value) /*-{ this.webkitMaskBoxImage = value; }-*/;
public final native void clearWebkitMaskBoxImage() /*-{ this.webkitMaskBoxImage = ""; }-*/;
public final native String getWebkitMaskBoxImageOutset() /*-{ return this.webkitMaskBoxImageOutset; }-*/;
public final native void setWebkitMaskBoxImageOutset(String value) /*-{ this.webkitMaskBoxImageOutset = value; }-*/;
public final native void clearWebkitMaskBoxImageOutset() /*-{ this.webkitMaskBoxImageOutset = ""; }-*/;
public final native String getWebkitMaskBoxImageRepeat() /*-{ return this.webkitMaskBoxImageRepeat; }-*/;
public final native void setWebkitMaskBoxImageRepeat(String value) /*-{ this.webkitMaskBoxImageRepeat = value; }-*/;
public final native void clearWebkitMaskBoxImageRepeat() /*-{ this.webkitMaskBoxImageRepeat = ""; }-*/;
public final native String getWebkitMaskBoxImageSlice() /*-{ return this.webkitMaskBoxImageSlice; }-*/;
public final native void setWebkitMaskBoxImageSlice(String value) /*-{ this.webkitMaskBoxImageSlice = value; }-*/;
public final native void clearWebkitMaskBoxImageSlice() /*-{ this.webkitMaskBoxImageSlice = ""; }-*/;
public final native String getWebkitMaskBoxImageSource() /*-{ return this.webkitMaskBoxImageSource; }-*/;
public final native void setWebkitMaskBoxImageSource(String value) /*-{ this.webkitMaskBoxImageSource = value; }-*/;
public final native void clearWebkitMaskBoxImageSource() /*-{ this.webkitMaskBoxImageSource = ""; }-*/;
public final native String getWebkitMaskBoxImageWidth() /*-{ return this.webkitMaskBoxImageWidth; }-*/;
public final native void setWebkitMaskBoxImageWidth(String value) /*-{ this.webkitMaskBoxImageWidth = value; }-*/;
public final native void clearWebkitMaskBoxImageWidth() /*-{ this.webkitMaskBoxImageWidth = ""; }-*/;
public final native String getWebkitMaskClip() /*-{ return this.webkitMaskClip; }-*/;
public final native void setWebkitMaskClip(String value) /*-{ this.webkitMaskClip = value; }-*/;
public final native void clearWebkitMaskClip() /*-{ this.webkitMaskClip = ""; }-*/;
public final native String getWebkitMaskComposite() /*-{ return this.webkitMaskComposite; }-*/;
public final native void setWebkitMaskComposite(String value) /*-{ this.webkitMaskComposite = value; }-*/;
public final native void clearWebkitMaskComposite() /*-{ this.webkitMaskComposite = ""; }-*/;
public final native String getWebkitMaskImage() /*-{ return this.webkitMaskImage; }-*/;
public final native void setWebkitMaskImage(String value) /*-{ this.webkitMaskImage = value; }-*/;
public final native void clearWebkitMaskImage() /*-{ this.webkitMaskImage = ""; }-*/;
public final native String getWebkitMaskOrigin() /*-{ return this.webkitMaskOrigin; }-*/;
public final native void setWebkitMaskOrigin(String value) /*-{ this.webkitMaskOrigin = value; }-*/;
public final native void clearWebkitMaskOrigin() /*-{ this.webkitMaskOrigin = ""; }-*/;
public final native String getWebkitMaskPosition() /*-{ return this.webkitMaskPosition; }-*/;
public final native void setWebkitMaskPosition(String value) /*-{ this.webkitMaskPosition = value; }-*/;
public final native void clearWebkitMaskPosition() /*-{ this.webkitMaskPosition = ""; }-*/;
public final native String getWebkitMaskPositionX() /*-{ return this.webkitMaskPositionX; }-*/;
public final native void setWebkitMaskPositionX(String value) /*-{ this.webkitMaskPositionX = value; }-*/;
public final native void clearWebkitMaskPositionX() /*-{ this.webkitMaskPositionX = ""; }-*/;
public final native String getWebkitMaskPositionY() /*-{ return this.webkitMaskPositionY; }-*/;
public final native void setWebkitMaskPositionY(String value) /*-{ this.webkitMaskPositionY = value; }-*/;
public final native void clearWebkitMaskPositionY() /*-{ this.webkitMaskPositionY = ""; }-*/;
public final native String getWebkitMaskRepeat() /*-{ return this.webkitMaskRepeat; }-*/;
public final native void setWebkitMaskRepeat(String value) /*-{ this.webkitMaskRepeat = value; }-*/;
public final native void clearWebkitMaskRepeat() /*-{ this.webkitMaskRepeat = ""; }-*/;
public final native String getWebkitMaskRepeatX() /*-{ return this.webkitMaskRepeatX; }-*/;
public final native void setWebkitMaskRepeatX(String value) /*-{ this.webkitMaskRepeatX = value; }-*/;
public final native void clearWebkitMaskRepeatX() /*-{ this.webkitMaskRepeatX = ""; }-*/;
public final native String getWebkitMaskRepeatY() /*-{ return this.webkitMaskRepeatY; }-*/;
public final native void setWebkitMaskRepeatY(String value) /*-{ this.webkitMaskRepeatY = value; }-*/;
public final native void clearWebkitMaskRepeatY() /*-{ this.webkitMaskRepeatY = ""; }-*/;
public final native String getWebkitMaskSize() /*-{ return this.webkitMaskSize; }-*/;
public final native void setWebkitMaskSize(String value) /*-{ this.webkitMaskSize = value; }-*/;
public final native void clearWebkitMaskSize() /*-{ this.webkitMaskSize = ""; }-*/;
public final native String getWebkitMatchNearestMailBlockquoteColor() /*-{ return this.webkitMatchNearestMailBlockquoteColor; }-*/;
public final native void setWebkitMatchNearestMailBlockquoteColor(String value) /*-{ this.webkitMatchNearestMailBlockquoteColor = value; }-*/;
public final native void clearWebkitMatchNearestMailBlockquoteColor() /*-{ this.webkitMatchNearestMailBlockquoteColor = ""; }-*/;
public final native String getWebkitMaxLogicalWidth() /*-{ return this.webkitMaxLogicalWidth; }-*/;
public final native void setWebkitMaxLogicalWidth(String value) /*-{ this.webkitMaxLogicalWidth = value; }-*/;
public final native void clearWebkitMaxLogicalWidth() /*-{ this.webkitMaxLogicalWidth = ""; }-*/;
public final native String getWebkitMaxLogicalHeight() /*-{ return this.webkitMaxLogicalHeight; }-*/;
public final native void setWebkitMaxLogicalHeight(String value) /*-{ this.webkitMaxLogicalHeight = value; }-*/;
public final native void clearWebkitMaxLogicalHeight() /*-{ this.webkitMaxLogicalHeight = ""; }-*/;
public final native String getWebkitMinLogicalWidth() /*-{ return this.webkitMinLogicalWidth; }-*/;
public final native void setWebkitMinLogicalWidth(String value) /*-{ this.webkitMinLogicalWidth = value; }-*/;
public final native void clearWebkitMinLogicalWidth() /*-{ this.webkitMinLogicalWidth = ""; }-*/;
public final native String getWebkitMinLogicalHeight() /*-{ return this.webkitMinLogicalHeight; }-*/;
public final native void setWebkitMinLogicalHeight(String value) /*-{ this.webkitMinLogicalHeight = value; }-*/;
public final native void clearWebkitMinLogicalHeight() /*-{ this.webkitMinLogicalHeight = ""; }-*/;
public final native String getWebkitNbspMode() /*-{ return this.webkitNbspMode; }-*/;
public final native void setWebkitNbspMode(String value) /*-{ this.webkitNbspMode = value; }-*/;
public final native void clearWebkitNbspMode() /*-{ this.webkitNbspMode = ""; }-*/;
public final native String getWebkitPaddingAfter() /*-{ return this.webkitPaddingAfter; }-*/;
public final native void setWebkitPaddingAfter(String value) /*-{ this.webkitPaddingAfter = value; }-*/;
public final native void clearWebkitPaddingAfter() /*-{ this.webkitPaddingAfter = ""; }-*/;
public final native String getWebkitPaddingBefore() /*-{ return this.webkitPaddingBefore; }-*/;
public final native void setWebkitPaddingBefore(String value) /*-{ this.webkitPaddingBefore = value; }-*/;
public final native void clearWebkitPaddingBefore() /*-{ this.webkitPaddingBefore = ""; }-*/;
public final native String getWebkitPaddingEnd() /*-{ return this.webkitPaddingEnd; }-*/;
public final native void setWebkitPaddingEnd(String value) /*-{ this.webkitPaddingEnd = value; }-*/;
public final native void clearWebkitPaddingEnd() /*-{ this.webkitPaddingEnd = ""; }-*/;
public final native String getWebkitPaddingStart() /*-{ return this.webkitPaddingStart; }-*/;
public final native void setWebkitPaddingStart(String value) /*-{ this.webkitPaddingStart = value; }-*/;
public final native void clearWebkitPaddingStart() /*-{ this.webkitPaddingStart = ""; }-*/;
public final native String getWebkitPerspective() /*-{ return this.webkitPerspective; }-*/;
public final native void setWebkitPerspective(String value) /*-{ this.webkitPerspective = value; }-*/;
public final native void clearWebkitPerspective() /*-{ this.webkitPerspective = ""; }-*/;
public final native String getWebkitPerspectiveOrigin() /*-{ return this.webkitPerspectiveOrigin; }-*/;
public final native void setWebkitPerspectiveOrigin(String value) /*-{ this.webkitPerspectiveOrigin = value; }-*/;
public final native void clearWebkitPerspectiveOrigin() /*-{ this.webkitPerspectiveOrigin = ""; }-*/;
public final native String getWebkitPerspectiveOriginX() /*-{ return this.webkitPerspectiveOriginX; }-*/;
public final native void setWebkitPerspectiveOriginX(String value) /*-{ this.webkitPerspectiveOriginX = value; }-*/;
public final native void clearWebkitPerspectiveOriginX() /*-{ this.webkitPerspectiveOriginX = ""; }-*/;
public final native String getWebkitPerspectiveOriginY() /*-{ return this.webkitPerspectiveOriginY; }-*/;
public final native void setWebkitPerspectiveOriginY(String value) /*-{ this.webkitPerspectiveOriginY = value; }-*/;
public final native void clearWebkitPerspectiveOriginY() /*-{ this.webkitPerspectiveOriginY = ""; }-*/;
public final native String getWebkitPrintColorAdjust() /*-{ return this.webkitPrintColorAdjust; }-*/;
public final native void setWebkitPrintColorAdjust(String value) /*-{ this.webkitPrintColorAdjust = value; }-*/;
public final native void clearWebkitPrintColorAdjust() /*-{ this.webkitPrintColorAdjust = ""; }-*/;
public final native String getWebkitRtlOrdering() /*-{ return this.webkitRtlOrdering; }-*/;
public final native void setWebkitRtlOrdering(String value) /*-{ this.webkitRtlOrdering = value; }-*/;
public final native void clearWebkitRtlOrdering() /*-{ this.webkitRtlOrdering = ""; }-*/;
public final native String getWebkitTextCombine() /*-{ return this.webkitTextCombine; }-*/;
public final native void setWebkitTextCombine(String value) /*-{ this.webkitTextCombine = value; }-*/;
public final native void clearWebkitTextCombine() /*-{ this.webkitTextCombine = ""; }-*/;
public final native String getWebkitTextDecorationsInEffect() /*-{ return this.webkitTextDecorationsInEffect; }-*/;
public final native void setWebkitTextDecorationsInEffect(String value) /*-{ this.webkitTextDecorationsInEffect = value; }-*/;
public final native void clearWebkitTextDecorationsInEffect() /*-{ this.webkitTextDecorationsInEffect = ""; }-*/;
public final native String getWebkitTextEmphasis() /*-{ return this.webkitTextEmphasis; }-*/;
public final native void setWebkitTextEmphasis(String value) /*-{ this.webkitTextEmphasis = value; }-*/;
public final native void clearWebkitTextEmphasis() /*-{ this.webkitTextEmphasis = ""; }-*/;
public final native String getWebkitTextEmphasisColor() /*-{ return this.webkitTextEmphasisColor; }-*/;
public final native void setWebkitTextEmphasisColor(String value) /*-{ this.webkitTextEmphasisColor = value; }-*/;
public final native void clearWebkitTextEmphasisColor() /*-{ this.webkitTextEmphasisColor = ""; }-*/;
public final native String getWebkitTextEmphasisPosition() /*-{ return this.webkitTextEmphasisPosition; }-*/;
public final native void setWebkitTextEmphasisPosition(String value) /*-{ this.webkitTextEmphasisPosition = value; }-*/;
public final native void clearWebkitTextEmphasisPosition() /*-{ this.webkitTextEmphasisPosition = ""; }-*/;
public final native String getWebkitTextEmphasisStyle() /*-{ return this.webkitTextEmphasisStyle; }-*/;
public final native void setWebkitTextEmphasisStyle(String value) /*-{ this.webkitTextEmphasisStyle = value; }-*/;
public final native void clearWebkitTextEmphasisStyle() /*-{ this.webkitTextEmphasisStyle = ""; }-*/;
public final native String getWebkitTextFillColor() /*-{ return this.webkitTextFillColor; }-*/;
public final native void setWebkitTextFillColor(String value) /*-{ this.webkitTextFillColor = value; }-*/;
public final native void clearWebkitTextFillColor() /*-{ this.webkitTextFillColor = ""; }-*/;
public final native String getWebkitTextSecurity() /*-{ return this.webkitTextSecurity; }-*/;
public final native void setWebkitTextSecurity(String value) /*-{ this.webkitTextSecurity = value; }-*/;
public final native void clearWebkitTextSecurity() /*-{ this.webkitTextSecurity = ""; }-*/;
public final native String getWebkitTextStroke() /*-{ return this.webkitTextStroke; }-*/;
public final native void setWebkitTextStroke(String value) /*-{ this.webkitTextStroke = value; }-*/;
public final native void clearWebkitTextStroke() /*-{ this.webkitTextStroke = ""; }-*/;
public final native String getWebkitTextStrokeColor() /*-{ return this.webkitTextStrokeColor; }-*/;
public final native void setWebkitTextStrokeColor(String value) /*-{ this.webkitTextStrokeColor = value; }-*/;
public final native void clearWebkitTextStrokeColor() /*-{ this.webkitTextStrokeColor = ""; }-*/;
public final native String getWebkitTextStrokeWidth() /*-{ return this.webkitTextStrokeWidth; }-*/;
public final native void setWebkitTextStrokeWidth(String value) /*-{ this.webkitTextStrokeWidth = value; }-*/;
public final native void clearWebkitTextStrokeWidth() /*-{ this.webkitTextStrokeWidth = ""; }-*/;
public final native String getWebkitTransform() /*-{ return this.webkitTransform; }-*/;
public final native void setWebkitTransform(String value) /*-{ this.webkitTransform = value; }-*/;
public final native void clearWebkitTransform() /*-{ this.webkitTransform = ""; }-*/;
public final native String getWebkitTransformOrigin() /*-{ return this.webkitTransformOrigin; }-*/;
public final native void setWebkitTransformOrigin(String value) /*-{ this.webkitTransformOrigin = value; }-*/;
public final native void clearWebkitTransformOrigin() /*-{ this.webkitTransformOrigin = ""; }-*/;
public final native String getWebkitTransformOriginX() /*-{ return this.webkitTransformOriginX; }-*/;
public final native void setWebkitTransformOriginX(String value) /*-{ this.webkitTransformOriginX = value; }-*/;
public final native void clearWebkitTransformOriginX() /*-{ this.webkitTransformOriginX = ""; }-*/;
public final native String getWebkitTransformOriginY() /*-{ return this.webkitTransformOriginY; }-*/;
public final native void setWebkitTransformOriginY(String value) /*-{ this.webkitTransformOriginY = value; }-*/;
public final native void clearWebkitTransformOriginY() /*-{ this.webkitTransformOriginY = ""; }-*/;
public final native String getWebkitTransformOriginZ() /*-{ return this.webkitTransformOriginZ; }-*/;
public final native void setWebkitTransformOriginZ(String value) /*-{ this.webkitTransformOriginZ = value; }-*/;
public final native void clearWebkitTransformOriginZ() /*-{ this.webkitTransformOriginZ = ""; }-*/;
public final native String getWebkitTransformStyle() /*-{ return this.webkitTransformStyle; }-*/;
public final native void setWebkitTransformStyle(String value) /*-{ this.webkitTransformStyle = value; }-*/;
public final native void clearWebkitTransformStyle() /*-{ this.webkitTransformStyle = ""; }-*/;
public final native String getWebkitTransition() /*-{ return this.webkitTransition; }-*/;
public final native void setWebkitTransition(String value) /*-{ this.webkitTransition = value; }-*/;
public final native void clearWebkitTransition() /*-{ this.webkitTransition = ""; }-*/;
public final native String getWebkitTransitionDelay() /*-{ return this.webkitTransitionDelay; }-*/;
public final native void setWebkitTransitionDelay(String value) /*-{ this.webkitTransitionDelay = value; }-*/;
public final native void clearWebkitTransitionDelay() /*-{ this.webkitTransitionDelay = ""; }-*/;
public final native String getWebkitTransitionDuration() /*-{ return this.webkitTransitionDuration; }-*/;
public final native void setWebkitTransitionDuration(String value) /*-{ this.webkitTransitionDuration = value; }-*/;
public final native void clearWebkitTransitionDuration() /*-{ this.webkitTransitionDuration = ""; }-*/;
public final native String getWebkitTransitionProperty() /*-{ return this.webkitTransitionProperty; }-*/;
public final native void setWebkitTransitionProperty(String value) /*-{ this.webkitTransitionProperty = value; }-*/;
public final native void clearWebkitTransitionProperty() /*-{ this.webkitTransitionProperty = ""; }-*/;
public final native String getWebkitTransitionTimingFunction() /*-{ return this.webkitTransitionTimingFunction; }-*/;
public final native void setWebkitTransitionTimingFunction(String value) /*-{ this.webkitTransitionTimingFunction = value; }-*/;
public final native void clearWebkitTransitionTimingFunction() /*-{ this.webkitTransitionTimingFunction = ""; }-*/;
public final native String getWebkitUserDrag() /*-{ return this.webkitUserDrag; }-*/;
public final native void setWebkitUserDrag(String value) /*-{ this.webkitUserDrag = value; }-*/;
public final native void clearWebkitUserDrag() /*-{ this.webkitUserDrag = ""; }-*/;
public final native String getWebkitUserModify() /*-{ return this.webkitUserModify; }-*/;
public final native void setWebkitUserModify(String value) /*-{ this.webkitUserModify = value; }-*/;
public final native void clearWebkitUserModify() /*-{ this.webkitUserModify = ""; }-*/;
public final native String getWebkitUserSelect() /*-{ return this.webkitUserSelect; }-*/;
public final native void setWebkitUserSelect(String value) /*-{ this.webkitUserSelect = value; }-*/;
public final native void clearWebkitUserSelect() /*-{ this.webkitUserSelect = ""; }-*/;
public final native String getWebkitFlowInto() /*-{ return this.webkitFlowInto; }-*/;
public final native void setWebkitFlowInto(String value) /*-{ this.webkitFlowInto = value; }-*/;
public final native void clearWebkitFlowInto() /*-{ this.webkitFlowInto = ""; }-*/;
public final native String getWebkitFlowFrom() /*-{ return this.webkitFlowFrom; }-*/;
public final native void setWebkitFlowFrom(String value) /*-{ this.webkitFlowFrom = value; }-*/;
public final native void clearWebkitFlowFrom() /*-{ this.webkitFlowFrom = ""; }-*/;
public final native String getWebkitRegionOverflow() /*-{ return this.webkitRegionOverflow; }-*/;
public final native void setWebkitRegionOverflow(String value) /*-{ this.webkitRegionOverflow = value; }-*/;
public final native void clearWebkitRegionOverflow() /*-{ this.webkitRegionOverflow = ""; }-*/;
public final native String getWebkitShapeInside() /*-{ return this.webkitShapeInside; }-*/;
public final native void setWebkitShapeInside(String value) /*-{ this.webkitShapeInside = value; }-*/;
public final native void clearWebkitShapeInside() /*-{ this.webkitShapeInside = ""; }-*/;
public final native String getWebkitShapeOutside() /*-{ return this.webkitShapeOutside; }-*/;
public final native void setWebkitShapeOutside(String value) /*-{ this.webkitShapeOutside = value; }-*/;
public final native void clearWebkitShapeOutside() /*-{ this.webkitShapeOutside = ""; }-*/;
public final native String getWebkitWrapMargin() /*-{ return this.webkitWrapMargin; }-*/;
public final native void setWebkitWrapMargin(String value) /*-{ this.webkitWrapMargin = value; }-*/;
public final native void clearWebkitWrapMargin() /*-{ this.webkitWrapMargin = ""; }-*/;
public final native String getWebkitWrapPadding() /*-{ return this.webkitWrapPadding; }-*/;
public final native void setWebkitWrapPadding(String value) /*-{ this.webkitWrapPadding = value; }-*/;
public final native void clearWebkitWrapPadding() /*-{ this.webkitWrapPadding = ""; }-*/;
public final native String getWebkitRegionBreakAfter() /*-{ return this.webkitRegionBreakAfter; }-*/;
public final native void setWebkitRegionBreakAfter(String value) /*-{ this.webkitRegionBreakAfter = value; }-*/;
public final native void clearWebkitRegionBreakAfter() /*-{ this.webkitRegionBreakAfter = ""; }-*/;
public final native String getWebkitRegionBreakBefore() /*-{ return this.webkitRegionBreakBefore; }-*/;
public final native void setWebkitRegionBreakBefore(String value) /*-{ this.webkitRegionBreakBefore = value; }-*/;
public final native void clearWebkitRegionBreakBefore() /*-{ this.webkitRegionBreakBefore = ""; }-*/;
public final native String getWebkitRegionBreakInside() /*-{ return this.webkitRegionBreakInside; }-*/;
public final native void setWebkitRegionBreakInside(String value) /*-{ this.webkitRegionBreakInside = value; }-*/;
public final native void clearWebkitRegionBreakInside() /*-{ this.webkitRegionBreakInside = ""; }-*/;
public final native String getWebkitWrapFlow() /*-{ return this.webkitWrapFlow; }-*/;
public final native void setWebkitWrapFlow(String value) /*-{ this.webkitWrapFlow = value; }-*/;
public final native void clearWebkitWrapFlow() /*-{ this.webkitWrapFlow = ""; }-*/;
public final native String getWebkitWrapThrough() /*-{ return this.webkitWrapThrough; }-*/;
public final native void setWebkitWrapThrough(String value) /*-{ this.webkitWrapThrough = value; }-*/;
public final native void clearWebkitWrapThrough() /*-{ this.webkitWrapThrough = ""; }-*/;
public final native String getWebkitWrap() /*-{ return this.webkitWrap; }-*/;
public final native void setWebkitWrap(String value) /*-{ this.webkitWrap = value; }-*/;
public final native void clearWebkitWrap() /*-{ this.webkitWrap = ""; }-*/;
public final native String getWebkitTapHighlightColor() /*-{ return this.webkitTapHighlightColor; }-*/;
public final native void setWebkitTapHighlightColor(String value) /*-{ this.webkitTapHighlightColor = value; }-*/;
public final native void clearWebkitTapHighlightColor() /*-{ this.webkitTapHighlightColor = ""; }-*/;
public final native String getWebkitDashboardRegion() /*-{ return this.webkitDashboardRegion; }-*/;
public final native void setWebkitDashboardRegion(String value) /*-{ this.webkitDashboardRegion = value; }-*/;
public final native void clearWebkitDashboardRegion() /*-{ this.webkitDashboardRegion = ""; }-*/;
public final native String getWebkitOverflowScrolling() /*-{ return this.webkitOverflowScrolling; }-*/;
public final native void setWebkitOverflowScrolling(String value) /*-{ this.webkitOverflowScrolling = value; }-*/;
public final native void clearWebkitOverflowScrolling() /*-{ this.webkitOverflowScrolling = ""; }-*/;
}
