#!/bin/bash

#
# install-node-webkit
#
# Copyright (C) 2009-12 by RStudio, Inc.
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

# install dir
INSTALL_DIR=`pwd`

# determine platform
PLATFORM=`uname`

# bail if not mac for now
if [ "$PLATFORM" != "Darwin" ]
then
  exit 0
fi

# use curl or wget as appropriate
download()
{
  if [ "$PLATFORM" == "Darwin" ]
  then
    curl -L https://s3.amazonaws.com/rstudio-buildtools/$1 > $1
  else
    wget https://s3.amazonaws.com/rstudio-buildtools/$1 -O $1
  fi
}

# download and extract if necessary
NODE_WEBKIT_VERSION="0.7.5"
if [ "$PLATFORM" == "Darwin" ]
then
  NODE_WEBKIT_PLATFORM=osx-ia32
fi

NODE_WEBKIT_DIR=node-webkit
if [ -d "$NODE_WEBKIT_DIR/$NODE_WEBKIT_VERSION" ]
then
   echo "node-webkit $NODE_WEBKIT_VERSION already installed"
else
   NODE_WEBKIT_FILE=node-webkit-v${NODE_WEBKIT_VERSION}-${NODE_WEBKIT_PLATFORM}
   NODE_WEBKIT_ARCHIVE=$NODE_WEBKIT_FILE.zip
   download $NODE_WEBKIT_ARCHIVE
   mkdir -p $NODE_WEBKIT_DIR
   unzip -q $NODE_WEBKIT_ARCHIVE -d $NODE_WEBKIT_DIR/$NODE_WEBKIT_VERSION
   rm $NODE_WEBKIT_ARCHIVE
fi

# back to install dir
cd $INSTALL_DIR