#!/usr/bin/env bash

#
# install-dictionaries
#
# Copyright (C) 2022 by Posit, PBC
#
# Unless you have received this program directly from Posit pursuant
# to the terms of a commercial license agreement with Posit, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

source "$(dirname "${BASH_SOURCE[0]}")/../tools/rstudio-tools.sh"
section "Installing Dictionaries"

URL="https://s3.amazonaws.com/rstudio-buildtools/dictionaries"

# download and extract the dictionaries if necessary
DICTIONARIES_DIR="${RSTUDIO_TOOLS_ROOT}/dictionaries"
if [ -d "${DICTIONARIES_DIR}" ]; then
   echo "Dictionaries already installed at '${DICTIONARIES_DIR}'"
   exit 0
fi

sudo-if-necessary-for "${RSTUDIO_TOOLS_ROOT}" "$@"

CORE_DICTIONARIES=core-dictionaries.zip
download "${URL}/${CORE_DICTIONARIES}"
rm -rf "${DICTIONARIES_DIR}"
mkdir -p "${DICTIONARIES_DIR}"
unzip -qd "${DICTIONARIES_DIR}" "${CORE_DICTIONARIES}"
rm "${CORE_DICTIONARIES}"

