#!/usr/bin/env bash

#
# install-dictionaries
#
# Copyright (C) 2009-11 by RStudio, Inc.
#
# This program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

# install dir
INSTALL_DIR=`pwd`

# determine platform
PLATFORM=`uname`

# use curl or wget as appropriate
download()
{
  if [ "$PLATFORM" == "Darwin" ]
  then
    curl -L https://s3.amazonaws.com/rstudio-dictionaries/$1 > $1
  elif [ "$PLATFORM" == "FreeBSD" ]
  then
    fetch -o $1 https://s3.amazonaws.com/rstudio-dictionaries/$1
  else
    wget https://s3.amazonaws.com/rstudio-dictionaries/$1 -O $1
  fi
}

# download and extract the dictionaries if necessary
DICTIONARIES_DIR=dictionaries
if [ -d "$DICTIONARIES_DIR" ]
then
   echo "Dictionaries already installed"
else
   CORE_DICTIONARIES=core-dictionaries.zip
   download $CORE_DICTIONARIES
   mkdir -p $DICTIONARIES_DIR
   unzip -qd "$DICTIONARIES_DIR" "$CORE_DICTIONARIES"
   rm $CORE_DICTIONARIES
fi

# back to install dir
cd $INSTALL_DIR
