#!/usr/bin/env bash

#
# install-common
#
# Copyright (C) 2021 by RStudio, PBC
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

function help() {
  cat <<EOF
usage: install-common [options]

Options
  --install-crashpad-sudo
      When installing dependencies to setup a dev environment, need to run install-crashpad
      via sudo; however, this causes problems if used when building a Dockerfile

EOF
}

INSTALL_CRASHPAD_SUDO=
while [ $# -gt 0 ]; do
  case "$1" in
    --install-crashpad-sudo)
      INSTALL_CRASHPAD_SUDO="sudo"
      echo Installing crashpad via sudo
      shift
      ;;
    --help|-h)
      help
      exit 0
      ;;
    *)
      help
      exit 1
      ;;
  esac
done

./install-dictionaries
./install-mathjax
./install-boost
./install-pandoc
./install-packages
./install-sentry-cli
./install-npm-dependencies
./install-soci
./install-yaml-cpp

if [[ "$OSTYPE" == "darwin"* ]]; then
  # use pre-built binaries on macos as compilation environment is difficult
  # to configure there
  echo Using pre-built osx binaries
  $INSTALL_CRASHPAD_SUDO ./install-crashpad osx
else
  $INSTALL_CRASHPAD_SUDO ./install-crashpad
fi

if [ -e install-overlay ]
then
   ./install-overlay
fi
