#!/bin/bash

#
# install-dependencies-java
#
# Copyright (C) 2009-11 by RStudio, Inc.
#
# This program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

# install dir
INSTALL_DIR=`pwd`

download()
{
  CURL=`which curl`
  if [ "$CURL" != "" ]
  then
    curl -L https://s3.amazonaws.com/rstudio-buildtools/$1 > $1
  else
    wget https://s3.amazonaws.com/rstudio-buildtools/$1 -O $1
  fi
}

# target directory for gwt
GWT_DIR=$INSTALL_DIR/../../src/gwt

# lib dir
LIB_DIR=$GWT_DIR/lib
mkdir -p $LIB_DIR

# gwt incubator
GWT_INCUBATOR_JAR=gwt-incubator-20100204-r1747.jar
INSTALLED_VERSION_FILE=$LIB_DIR/gwt-incubator/installed_version
INSTALLED_VERSION=`cat $INSTALLED_VERSION_FILE 2>/dev/null`
if [ "$GWT_INCUBATOR_JAR" != "$INSTALLED_VERSION" ]
then
   download $GWT_INCUBATOR_JAR
   rm -rf $LIB_DIR/gwt-incubator
   mkdir -p $LIB_DIR/gwt-incubator
   mv $GWT_INCUBATOR_JAR $LIB_DIR/gwt-incubator
   echo "$GWT_INCUBATOR_JAR" > $INSTALLED_VERSION_FILE
else
   echo "$GWT_INCUBATOR_JAR already installed"
fi

# guice
GUICE_ZIP=guice.zip
INSTALLED_VERSION_FILE=$LIB_DIR/guice/installed_version
INSTALLED_VERSION=`cat $INSTALLED_VERSION_FILE 2>/dev/null`
if [ "$GUICE_ZIP" != "$INSTALLED_VERSION" ]
then
   download $GUICE_ZIP
   rm -rf $LIB_DIR/guice
   unzip -qd $LIB_DIR $GUICE_ZIP
   echo "$GUICE_ZIP" > $INSTALLED_VERSION_FILE
   rm $GUICE_ZIP
else
   echo "$GUICE_ZIP already installed"
fi

# gin
GIN_ZIP=gin.zip
INSTALLED_VERSION_FILE=$LIB_DIR/gin/installed_version
INSTALLED_VERSION=`cat $INSTALLED_VERSION_FILE 2>/dev/null`
if [ "$GIN_ZIP" != "$INSTALLED_VERSION" ]
then
   download $GIN_ZIP
   rm -rf $LIB_DIR/gin
   unzip -qd $LIB_DIR $GIN_ZIP
   echo "$GIN_ZIP" > $INSTALLED_VERSION_FILE
   rm $GIN_ZIP
else
   echo "$GIN_ZIP already installed"
fi

# gwt sdk
GWT_SDK=gwt-2.0.4
GWT_SDK_ZIP=$GWT_SDK.zip
INSTALLED_VERSION_FILE=$GWT_DIR/sdk/installed_version
INSTALLED_VERSION=`cat $INSTALLED_VERSION_FILE 2>/dev/null`
if [ "$GWT_SDK_ZIP" != "$INSTALLED_VERSION" ]
then
   download $GWT_SDK_ZIP
   rm -rf $GWT_DIR/sdk
   unzip -qd $GWT_DIR $GWT_SDK_ZIP
   mv $GWT_DIR/$GWT_SDK $GWT_DIR/sdk
   echo "$GWT_SDK_ZIP" > $INSTALLED_VERSION_FILE
   rm $GWT_SDK_ZIP
else
   echo "$GWT_SDK_ZIP already installed"
fi

# back to install dir
cd $INSTALL_DIR
