#!/usr/bin/env bash

#
# install-qt-src
#
# Copyright (C) 2022 by Posit Software, PBC
#
# Unless you have received this program directly from Posit pursuant
# to the terms of a commercial license agreement with Posit, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

if [ "$#" == "0" ]; then
	echo "Usage: install-qt-src version"
	exit 0
fi

source "$(dirname "${BASH_SOURCE[0]}")/../tools/rstudio-tools.sh"
section "Installing Qt"

# Set up variables.
: "${ROOT="${HOME}/opt/local/qt"}"
: "${VERSION="$1"}"

PREFIX="${ROOT}/${VERSION}"

if [ "$(uname)" = "Linux" ]; then

	info
	info "Installing Qt build dependencies"
	info
	info "If this fails, ensure you've enabled Source Code repositories."
	info "This implies adding 'deb-src' repositories to /etc/apt/sources.list on Debian."
	info "On Ubuntu, you can use the 'Software & Updates' application to enable these as well."
	info

	sudo apt-get build-dep -y qtbase5-dev
	sudo apt-get install -y libxcb-xinerama0-dev
	sudo apt-get install -y bison flex gperf python2-dev
	sudo apt-get install -y python-is-python3
 
fi

VERSION="$1"
VERSION_MAJMIN=$(echo "${VERSION}" | cut -d"." -f"1,2")

cd "${TMPDIR:-/tmp}"

mkdir "qt-${VERSION}-src"
cd "qt-${VERSION}-src"

PARTS=(
	"https://download.qt.io"
	"official_releases"
	"qt"
	"${VERSION_MAJMIN}"
	"${VERSION}"
	"single"
	"qt-everywhere-src-${VERSION}.tar.xz"
)
URL=$(IFS=/; printf "%s" "${PARTS[*]}")

info "Downloading Qt"
download "${URL}"

info "Extracting Qt"
TARBALL="$(basename "${URL}")"
tar xaf "${TARBALL}"

NAME="qt-everywhere-src-${VERSION}"
cd "${NAME}"

# on Jammy Jellyfish, we need to use an older version of gcc
CODENAME=$(source /etc/os-release; echo "${UBUNTU_CODENAME}")
if [ "${CODENAME}" = "jammy" ]; then
	sudo apt install gcc-9 g++-9
	cat <<- EOF >> qtbase/mkspecs/linux-g++/qmake.conf
	QMAKE_CC     = /usr/bin/gcc-9
	QMAKE_CXX    = /usr/bin/g++-9
	QMAKE_LINK_C = /usr/bin/gcc-9
	QMAKE_LINK   = /usr/bin/g++-9
	EOF
fi

info "Configuring Qt"
./configure             \
	-prefix "${PREFIX}" \
	-opensource         \
	-confirm-license    \
	-release            \
	-recheck-all

info "Building Qt"
info "Grab a cup of coffee, this will take a while."
make ${MAKEFLAGS:-j4}

info "Installing Qt"
sudo make install

info "Qt ${VERSION} was successfully installed."
info "Install path: ${PREFIX}"

