#!/usr/bin/env bash

#
# install-yaml-cpp
#
# Copyright (C) 2021 by RStudio, PBC
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

YAML_CPP_VERSION="0.6.3"
YAML_CPP_BRANCH="yaml-cpp-${YAML_CPP_VERSION}"
YAML_CPP_DIRECTORY="/opt/rstudio-tools/yaml-cpp/${YAML_CPP_VERSION}"

if [ -f "${YAML_CPP_DIRECTORY}" ]; then
	echo "${YAML_CPP_BRANCH} already installed."
	exit 0
fi

# lazy way to make sure parent directory of target is created
mkdir -p "${YAML_CPP_DIRECTORY}"
rm -rf "${YAML_CPP_DIRECTORY}"

# check out the required branch of yaml-cpp
if ! [ -f "${YAML_CPP_BRANCH}" ]; then
	git clone                                \
		--depth 1                            \
		--branch "${YAML_CPP_BRANCH}"        \
		"https://github.com/jbeder/yaml-cpp" \
		"${YAML_CPP_DIRECTORY}"
		
fi

# go to directory
cd "${YAML_CPP_DIRECTORY}"

# build on demand
rm -rf build
mkdir build
cd build

cmake -DYAML_CPP_BUILD_TESTS=Off ..
cmake --build .

