#!/usr/bin/env bash

#
# install-common
#
# Copyright (C) 2022 by Posit Software, PBC
#
# Unless you have received this program directly from Posit Software pursuant
# to the terms of a commercial license agreement with Posit Software, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

./install-dictionaries
./install-mathjax
./install-boost
./install-pandoc
./install-quarto
./install-packages
./install-sentry-cli
./install-npm-dependencies
./install-soci
./install-yaml-cpp
./install-crashpad
./install-panmirror

if [ -e install-overlay ]
then
   ./install-overlay $1
fi
