#!/usr/bin/env bash

#
# patch-node
#
# Copyright (C) 2024 Posit Software, PBC
#
# Unless you have received this program directly from Posit Software pursuant
# to the terms of a commercial license agreement with Posit Software, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

source "$(dirname "${BASH_SOURCE[0]}")/../tools/rstudio-tools.sh"

# check for required ENV vars (as set by install-npm-dependencies)
if ! check_env_vars NODE_VERSION NODE_FOLDER NODE_ROOT NODE_SUBDIR NODE_BASE_URL; then
	exit 1 # check_env_vars has already printed an error message
fi

section "Applying patches to node ${NODE_VERSION}"

rm "${NODE_SUBDIR:?}/bin/npm"
rm "${NODE_SUBDIR:?}/bin/npx"
rm "${NODE_SUBDIR:?}/bin/corepack"
rm "${NODE_SUBDIR:?}/CHANGELOG.md"
rm "${NODE_SUBDIR:?}/README.md"
rm -rf "${NODE_SUBDIR:?}/include"
rm -rf "${NODE_SUBDIR:?}/lib"
rm -rf "${NODE_SUBDIR:?}/share"