#!/usr/bin/env bash

#
# update-pandoc
#
# Copyright (C) 2009-12 by RStudio, Inc.
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

# install dir
INSTALL_DIR=`pwd`

# script dir
SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $SCRIPT_DIR

# remove then re-install pandoc
PANDOC_VERSION=1.13.1
PANDOC_DIR=pandoc/$PANDOC_VERSION
rm -rf $PANDOC_DIR
./install-pandoc
$PANDOC_DIR/pandoc -D latex
$PANDOC_DIR/pandoc --version

# back to install dir
cd $INSTALL_DIR
