FROM alpine:3.6
RUN apk -v --update add \
		bash \
        python \
        py-pip \
	    git \
        groff \
        less \
        mailcap \
        && \
     pip install --upgrade awscli s3cmd python-magic && \
     apk -v --purge del py-pip && \
     rm /var/cache/apk/* && \
     mkdir -p /scripts

