

#' Convert a document using pandoc
#'
#' Convert the \code{input} document to the specified \code{format} and write it
#' to \code{output}.
#'
#' @param input Input file
#' @param output Output file (if not specified then a default based on the
#' specified format is chosen)
#' @param format Pandoc format to convert to (defaults to HTML if not specified)
#' @param options Command line options to pass to pandoc
#' @param quiet \code{TRUE} to supress printing of the pandoc command line
#'
#' @return The output file generated by the converstion
#'
#' @export
pandocConvert <- function(input,
                          output = NULL,
                          format = NULL,
                          options = NULL,
                          quiet = FALSE) {

  verifyPandocVersion()

  if (is.null(format))
    format <- "html"

  if (is.null(output))
    output <- pandocOutputFile(input, format)

  args <- c("--output", output,
            "--to", format,
            options,
            input,
            recursive = TRUE)

  if (!quiet) {
    cat("pandoc ")
    cat(paste(args, collapse=" "))
    cat("\n")
  }

  execPandoc(args)

  invisible(output)
}


#' Determine the output file for a pandoc conversion
#'
#' Give an input file and pandoc format determine the name of the output file to
#' write.
#'
#' @param input Input file
#' @param pandocFormat Pandoc format of the output (e.g. \code{html},
#'   \code{html5}, \code{docx}, \code{latex}, \code{beamer})
#'
#' @return Output file
#'
#' @export
pandocOutputFile <- function(input, pandocFormat) {
  if (pandocFormat %in% c("latex", "beamer"))
    ext <- ".pdf"
  else if (pandocFormat %in% c("html", "html5", "revealjs"))
    ext <- ".html"
  else
    ext <- paste0(".", pandocFormat)
  paste0(tools::file_path_sans_ext(input), ext)
}


#' Pandoc options for R Markdown
#'
#' Get the pandoc command line options required to render R Markdown.
#'
#' @param featureFlags Additional flags for enabling and disabling markdown
#' features supported during a conversion.
#'
#' @return Character vector of pandoc options
#'
#' @export
pandocMarkdownOptions <- function(featureFlags = NULL) {
  c("--from",
    paste0("markdown_github",
           "-hard_line_breaks",
           "+superscript",
           "+tex_math_dollars",
           "+raw_html",
           "+auto_identifiers",
           "+raw_tex",
           "+latex_macros",
           "+footnotes",
           "+inline_notes",
           "+citations",
           "+yaml_metadata_block",
           featureFlags),
    "--smart")
}


execPandoc <- function(args, ...) {
  pandoc <- pandocPath()
  if (nzchar(pandoc)) {
    command <- paste(pandoc, paste(shQuote(args), collapse = " "))
    system(command, ...)
  } else {
    stop("pandoc was not found on the system path", call. = FALSE)
  }
}

pandocPath <- function() {
  Sys.which("pandoc")
}

verifyPandocVersion <- function() {
  hasPandoc <- hasRequiredPandocVersion()
  if (!hasPandoc) {
    msg <- paste("The pandoc package requires that pandoc version",
                 requiredPandocVersion(),
                 "or greater is installed and available on the path.")
    oldVersion <- attr(hasPandoc, "version")
    if (!is.null(oldVersion))
      msg <- paste(msg, "You currently have version", oldVersion, "installed,",
                   "please update to a newer version.")
    else
      msg <- paste(msg, "No version of pandoc was found on the path.")

    stop(msg, call.=FALSE)
  }
}

hasRequiredPandocVersion <- function() {
  if (nzchar(pandocPath())) {
    versionInfo <- execPandoc("--version", intern = TRUE)
    version <- strsplit(versionInfo, "\n")[[1]][1]
    version <- strsplit(version, " ")[[1]][2]
    hasRequired <- numeric_version(version) >= requiredPandocVersion()
    if (hasRequired) {
      TRUE
    } else {
      attr(hasRequired, "version") <- version
      hasRequired
    }
  } else {
    FALSE
  }
}

requiredPandocVersion <- function() {
  "1.12.3"
}

