#!/bin/bash

#
# install-qt-48-sdk
#
# Copyright (C) 2009-11 by RStudio, Inc.
#
# This program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

# This archive includes the files required to build against Qt 4.8. It was 
# created by:
#
#  1) Installing the Qt 4.8 SDK into the default location in the home folder
#  2) Removing all folders in the QtSDK folder except for the Desktop folder
#  3) Creating an archive from ~ using: 
#
#     tar czf QtSDK-4.8.0-x86_64.tar.gz QtSDK/
#

# install dir
INSTALL_DIR=`pwd`

# define QT archive to download
SYSTEM_ARCH=`getconf LONG_BIT`
if [ "$SYSTEM_ARCH" == "64" ]
then
  QT_ARCH=x86_64
else
  QT_ARCH=x86
fi
QT_SDK_BINARY=QtSDK-4.8.0-${QT_ARCH}.tar.gz
QT_SDK_URL=https://s3.amazonaws.com/rstudio-buildtools/$QT_SDK_BINARY
QT_SDK_DIR=$INSTALL_DIR/../QtSDK

if ! test -e $QT_SDK_DIR
then
   # download and install
   cd ..
   wget $QT_SDK_URL -O $QT_SDK_BINARY
   tar xf $QT_SDK_BINARY
   rm $QT_SDK_BINARY
   cd $INSTALL_DIR
else
   echo "Qt 4.8.0 SDK already installed"
fi

