"undefined"===typeof PDFJS&&(("undefined"!==typeof window?window:this).PDFJS={});
(function(){function c(b,d){return new a(this.slice(b,d))}function b(b,a){2>arguments.length&&(a=0);for(var c=0,g=b.length;c<g;++c,++a)this[a]=b[c]&255}function a(a){var d;if("number"===typeof a){d=[];for(var e=0;e<a;++e)d[e]=0}else if("slice"in a)d=a.slice(0);else{d=[];for(var e=0,g=a.length;e<g;++e)d[e]=a[e]}d.subarray=c;d.buffer=d;d.byteLength=d.length;d.set=b;"object"===typeof a&&a.buffer&&(d.buffer=a.buffer);return d}"undefined"!==typeof Uint8Array?("undefined"===typeof Uint8Array.prototype.subarray&&
(Uint8Array.prototype.subarray=function(a,b){return new Uint8Array(this.slice(a,b))},Float32Array.prototype.subarray=function(a,b){return new Float32Array(this.slice(a,b))}),"undefined"===typeof Float64Array&&(window.Float64Array=Float32Array)):(window.Uint8Array=a,window.Uint32Array=a,window.Int32Array=a,window.Uint16Array=a,window.Float32Array=a,window.Float64Array=a)})();(function(){window.URL||(window.URL=window.webkitURL)})();
(function(){"undefined"===typeof Object.create&&(Object.create=function(c){function b(){}b.prototype=c;return new b})})();
(function(){if("undefined"!==typeof Object.defineProperty){var c=!0;try{Object.defineProperty(new Image,"id",{value:"test"});var b=function(){};b.prototype={get id(){}};Object.defineProperty(new b,"id",{value:"",configurable:!0,enumerable:!0,writable:!1})}catch(a){c=!1}if(c)return}Object.defineProperty=function(a,b,c){delete a[b];"get"in c&&a.__defineGetter__(b,c.get);"set"in c&&a.__defineSetter__(b,c.set);"value"in c&&(a.__defineSetter__(b,function(a){this.__defineGetter__(b,function(){return a});
return a}),a[b]=c.value)}})();(function(){"undefined"===typeof Object.keys&&(Object.keys=function(c){var b=[],a;for(a in c)c.hasOwnProperty(a)&&b.push(a);return b})})();
(function(){if("undefined"!==typeof FileReader){var c=FileReader.prototype;"readAsArrayBuffer"in c||Object.defineProperty(c,"readAsArrayBuffer",{value:function(b){var a=new FileReader,c=this;a.onload=function(a){for(var a=a.target.result,b=new ArrayBuffer(a.length),g=new Uint8Array(b),h=0,i=a.length;h<i;h++)g[h]=a.charCodeAt(h);Object.defineProperty(c,"result",{value:b,enumerable:!0,writable:!1,configurable:!0});a=document.createEvent("HTMLEvents");a.initEvent("load",!1,!1);c.dispatchEvent(a)};a.readAsBinaryString(b)}})}})();
(function(){function c(){this.overrideMimeType("text/plain; charset=x-user-defined")}var b=XMLHttpRequest.prototype;"overrideMimeType"in b||Object.defineProperty(b,"overrideMimeType",{value:function(){}});"response"in b||"mozResponseArrayBuffer"in b||"mozResponse"in b||"responseArrayBuffer"in b||("undefined"!==typeof VBArray?Object.defineProperty(b,"response",{get:function(){return new Uint8Array((new VBArray(this.responseBody)).toArray())}}):("function"===typeof b.overrideMimeType&&Object.defineProperty(b,
"responseType",{set:c}),Object.defineProperty(b,"response",{get:function(){var a=this.responseText,b,c=a.length,e=new Uint8Array(c);for(b=0;b<c;++b)e[b]=a.charCodeAt(b)&255;return e}})))})();
(function(){"btoa"in window||(window.btoa=function(c){var b="",a,f;for(a=0,f=c.length;a<f;a+=3)var d=c.charCodeAt(a)&255,e=c.charCodeAt(a+1)&255,g=c.charCodeAt(a+2)&255,h=(d&3)<<4|e>>4,e=a+1<f?(e&15)<<2|g>>6:64,g=a+2<f?g&63:64,b=b+("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(d>>2)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(h)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g));
return b})})();(function(){"atob"in window||(window.atob=function(c){c=c.replace(/=+$/,"");if(1==c.length%4)throw Error("bad atob input");for(var b=0,a,f,d=0,e="";f=c.charAt(d++);~f&&(a=b%4?64*a+f:f,b++%4)&&(e+=String.fromCharCode(255&a>>(-2*b&6))))f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(f);return e})})();
(function(){"undefined"===typeof Function.prototype.bind&&(Function.prototype.bind=function(c){var b=this,a=Array.prototype.slice.call(arguments,1);return function(){var f=a.concat(Array.prototype.slice.call(arguments));return b.apply(c,f)}})})();
(function(){"dataset"in document.createElement("div")||Object.defineProperty(HTMLElement.prototype,"dataset",{get:function(){if(this._dataset)return this._dataset;for(var c={},b=0,a=this.attributes.length;b<a;b++){var f=this.attributes[b];if("data-"==f.name.substring(0,5)){var d=f.name.substring(5).replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()});c[d]=f.value}}Object.defineProperty(this,"_dataset",{value:c,writable:!1,enumerable:!1});return c},enumerable:!0})})();
(function(){function c(a,b,c,e){var g=(a.className||"").split(/\s+/g);""===g[0]&&g.shift();var h=g.indexOf(b);0>h&&c&&g.push(b);0<=h&&e&&g.splice(h,1);a.className=g.join(" ");return 0<=h}if(!("classList"in document.createElement("div"))){var b={add:function(a){c(this.element,a,!0,!1)},contains:function(a){return c(this.element,a,!1,!1)},remove:function(a){c(this.element,a,!1,!0)},toggle:function(a){c(this.element,a,!0,!0)}};Object.defineProperty(HTMLElement.prototype,"classList",{get:function(){if(this._classList)return this._classList;
var a=Object.create(b,{element:{value:this,writable:!1,enumerable:!0}});Object.defineProperty(this,"_classList",{value:a,writable:!1,enumerable:!1});return a},enumerable:!0})}})();
(function(){"console"in window?"bind"in console.log||(console.log=function(c){return function(b){return c(b)}}(console.log),console.error=function(c){return function(b){return c(b)}}(console.error),console.warn=function(c){return function(b){return c(b)}}(console.warn)):window.console={log:function(){},error:function(){},warn:function(){}}})();
(function(){function c(a){b(a.target)&&a.stopPropagation()}function b(a){return a.disabled||a.parentNode&&b(a.parentNode)}-1!=navigator.userAgent.indexOf("Opera")&&document.addEventListener("click",c,!0)})();(function(){0<=navigator.userAgent.indexOf("Trident")&&(PDFJS.disableCreateObjectURL=!0)})();
(function(){if(!("language"in navigator&&/^[a-z]+(-[A-Z]+)?$/.test(navigator.language))){var c=PDFJS,b;b=(navigator.language||navigator.userLanguage||"en-US").split(/[-_]/);b[0]=b[0].toLowerCase();1<b.length&&(b[1]=b[1].toUpperCase());b=b.join("-");c.locale=b}})();(function(){var c=0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor"),b=/Android\s[0-2][^\d]/.test(navigator.userAgent);if(c||b)PDFJS.disableRange=!0})();
(function(){window.history.pushState||(PDFJS.disableHistory=!0)})();
