document.webL10n=function(A,h){function B(){var c=h.querySelector('script[type="application/l10n"]');return c?JSON.parse(c.innerHTML):null}function u(c){var b=h.createEvent("Event");b.initEvent("localized",!0,!1);b.language=c;h.dispatchEvent(b)}function v(c,b,e,d){var b=b||function(){},e=e||function(){console.warn(c+" not found.")},a=new XMLHttpRequest;a.open("GET",c,d);a.overrideMimeType&&a.overrideMimeType("text/plain; charset=utf-8");a.onreadystatechange=function(){4==a.readyState&&(200==a.status||
0===a.status?b(a.responseText):e())};a.onerror=e;a.ontimeout=e;try{a.send(null)}catch(f){e()}}function C(c,b,e,d){function a(a){function c(a,l){for(var w=a.replace(g,"").split(/[\r\n]+/),r="*",q=b.replace(/-[a-z]+$/i,""),r=!1,n="",j=0;j<w.length;j++){var s=w[j];if(!o.test(s)){if(l){if(h.test(s)){n=h.exec(s);r=n[1];r="*"!==r&&r!==b&&r!==q;continue}else if(r)continue;i.test(s)&&(n=i.exec(s),e(f+n[1]))}(n=s.match(p))&&3==n.length&&(d[n[1]]=0>n[2].lastIndexOf("\\")?n[2]:n[2].replace(/\\\\/g,"\\").replace(/\\n/g,
"\n").replace(/\\r/g,"\r").replace(/\\t/g,"\t").replace(/\\b/g,"\u0008").replace(/\\f/g,"\u000c").replace(/\\{/g,"{").replace(/\\}/g,"}").replace(/\\"/g,'"').replace(/\\'/g,"'"))}}}function e(a){v(a,function(a){c(a,!1)},null,!1)}var d=[],g=/^\s*|\s*$/,o=/^\s*#|^\s*$/,h=/^\s*\[(.*)\]\s*$/,i=/^\s*@import\s+url\((.*)\)\s*$/i,p=/^([^=\s]*)\s*=\s*(.+)$/;c(a,!0);return d}var f=c.replace(/[^\/]*$/,"")||"./";v(c,function(b){t+=b;var b=a(b),c;for(c in b){var d,f;f=c.lastIndexOf(".");0<f?(d=c.substring(0,f),
f=c.substr(f+1)):(d=c,f=i);g[d]||(g[d]={});g[d][f]=b[c]}e&&e()},d,D)}function E(c,b){function e(a){var b=a.href;this.load=function(a,c){var d=a;C(b,a,c,function(){console.warn(b+" not found.");d=""});return d}}b=b||function(){};g={};p=t="";p=c;var d=h.querySelectorAll('link[type="application/l10n"]'),a=d.length;if(0===a)(d=B())&&d.locales&&d.default_locale?(console.log("using the embedded JSON directory, early way out"),g=d.locales[c]||d.locales[d.default_locale],b()):console.log("no resource to load, early way out"),
u(c),j="complete";else for(var f=null,l=0,f=function(){l++;l>=a&&(b(),u(c),j="complete")},i=0;i<a;i++)(new e(d[i])).load(c,f)!=c&&(console.warn('"'+c+'" resource not found'),p="")}function F(c){function b(a,b,c){return b<=a&&a<=c}var e={"0":function(){return"other"},1:function(a){return b(a%100,3,10)?"few":0===a?"zero":b(a%100,11,99)?"many":2==a?"two":1==a?"one":"other"},2:function(a){return 0!==a&&0===a%10?"many":2==a?"two":1==a?"one":"other"},3:function(a){return 1==a?"one":"other"},4:function(a){return b(a,
0,1)?"one":"other"},5:function(a){return b(a,0,2)&&2!=a?"one":"other"},6:function(a){return 0===a?"zero":1==a%10&&11!=a%100?"one":"other"},7:function(a){return 2==a?"two":1==a?"one":"other"},8:function(a){return b(a,3,6)?"few":b(a,7,10)?"many":2==a?"two":1==a?"one":"other"},9:function(a){return 0===a||1!=a&&b(a%100,1,19)?"few":1==a?"one":"other"},10:function(a){return b(a%10,2,9)&&!b(a%100,11,19)?"few":1==a%10&&!b(a%100,11,19)?"one":"other"},11:function(a){return b(a%10,2,4)&&!b(a%100,12,14)?"few":
0===a%10||b(a%10,5,9)||b(a%100,11,14)?"many":1==a%10&&11!=a%100?"one":"other"},12:function(a){return b(a,2,4)?"few":1==a?"one":"other"},13:function(a){return b(a%10,2,4)&&!b(a%100,12,14)?"few":1!=a&&b(a%10,0,1)||b(a%10,5,9)||b(a%100,12,14)?"many":1==a?"one":"other"},14:function(a){return b(a%100,3,4)?"few":2==a%100?"two":1==a%100?"one":"other"},15:function(a){return 0===a||b(a%100,2,10)?"few":b(a%100,11,19)?"many":1==a?"one":"other"},16:function(a){return 1==a%10&&11!=a?"one":"other"},17:function(a){return 3==
a?"few":0===a?"zero":6==a?"many":2==a?"two":1==a?"one":"other"},18:function(a){return 0===a?"zero":b(a,0,2)&&0!==a&&2!=a?"one":"other"},19:function(a){return b(a,2,10)?"few":b(a,0,1)?"one":"other"},20:function(a){return(b(a%10,3,4)||9==a%10)&&!b(a%100,10,19)&&!b(a%100,70,79)&&!b(a%100,90,99)?"few":0===a%1E6&&0!==a?"many":2==a%10&&-1===[12,72,92].indexOf(a%100)?"two":1==a%10&&-1===[11,71,91].indexOf(a%100)?"one":"other"},21:function(a){return 0===a?"zero":1==a?"one":"other"},22:function(a){return b(a,
0,1)||b(a,11,99)?"one":"other"},23:function(a){return b(a%10,1,2)||0===a%20?"one":"other"},24:function(a){return b(a,3,10)||b(a,13,19)?"few":-1!==[2,12].indexOf(a)?"two":-1!==[1,11].indexOf(a)?"one":"other"}},d={af:3,ak:4,am:4,ar:1,asa:3,az:0,be:11,bem:3,bez:3,bg:3,bh:4,bm:0,bn:3,bo:0,br:20,brx:3,bs:11,ca:3,cgg:3,chr:3,cs:12,cy:17,da:3,de:3,dv:3,dz:0,ee:3,el:3,en:3,eo:3,es:3,et:3,eu:3,fa:0,ff:5,fi:3,fil:4,fo:3,fr:5,fur:3,fy:3,ga:8,gd:24,gl:3,gsw:3,gu:3,guw:4,gv:23,ha:3,haw:3,he:2,hi:4,hr:11,hu:0,
id:0,ig:0,ii:0,is:3,it:3,iu:7,ja:0,jmc:3,jv:0,ka:0,kab:5,kaj:3,kcg:3,kde:0,kea:0,kk:3,kl:3,km:0,kn:0,ko:0,ksb:3,ksh:21,ku:3,kw:7,lag:18,lb:3,lg:3,ln:4,lo:0,lt:10,lv:6,mas:3,mg:4,mk:16,ml:3,mn:3,mo:9,mr:3,ms:0,mt:15,my:0,nah:3,naq:7,nb:3,nd:3,ne:3,nl:3,nn:3,no:3,nr:3,nso:4,ny:3,nyn:3,om:3,or:3,pa:3,pap:3,pl:13,ps:3,pt:3,rm:3,ro:9,rof:3,ru:11,rwk:3,sah:0,saq:3,se:7,seh:3,ses:0,sg:0,sh:11,shi:19,sk:12,sl:14,sma:7,smi:7,smj:7,smn:7,sms:7,sn:3,so:3,sq:3,sr:11,ss:3,ssy:3,st:3,sv:3,sw:3,syr:3,ta:3,te:3,
teo:3,th:0,ti:4,tig:3,tk:3,tl:4,tn:3,to:0,tr:0,ts:3,tzm:22,uk:11,ur:3,ve:3,vi:0,vun:3,wa:4,wae:3,wo:0,xh:3,xog:3,yo:0,zh:0,zu:3}[c.replace(/-.*$/,"")];return!(d in e)?(console.warn("plural form unknown for ["+c+"]"),function(){return"other"}):e[d]}function x(c,b,e){var d=g[c];if(!d){console.warn("#"+c+" is undefined.");if(!e)return null;d=e}var e={},a;for(a in d){var f=d[a];var l=b,h=c,j=a,k=/\{\[\s*([a-zA-Z]+)\(([a-zA-Z]+)\)\s*\]\}/.exec(f);if(k&&k.length){var m=k[1],k=k[2],o=void 0;l&&k in l?o=
l[k]:k in g&&(o=g[k]);m in q&&(f=(0,q[m])(f,o,h,j))}l=b;h=c;j=/\{\{\s*(.+?)\s*\}\}/;for(m=j.exec(f);m&&m&&!(2>m.length);){k=m[1];o="";if(l&&k in l)o=l[k];else if(k in g)o=g[k][i];else{console.log("argument {{"+k+"}} for #"+h+" is undefined.");break}f=f.substring(0,m.index)+o+f.substr(m.index+m[0].length);m=j.exec(f)}e[a]=f}return e}function y(c){var b,e;if(c){b=c.getAttribute("data-l10n-id");var d=c.getAttribute("data-l10n-args");e={};if(d)try{e=JSON.parse(d)}catch(a){console.warn("could not parse arguments for #"+
b)}}else b=void 0,e=void 0;if(b)if(e=x(b,e)){if(e[i]){if(c.children)b=c.children.length;else if("undefined"!==typeof c.childElementCount)b=c.childElementCount;else for(d=b=0;d<c.childNodes.length;d++)b+=1===c.nodeType?1:0;if(0===b)c[i]=e[i];else{b=c.childNodes;for(var d=!1,f=0,g=b.length;f<g;f++)3===b[f].nodeType&&/\S/.test(b[f].nodeValue)&&(d?b[f].nodeValue="":(b[f].nodeValue=e[i],d=!0));d||(b=h.createTextNode(e[i]),c.insertBefore(b,c.firstChild))}delete e[i]}for(var j in e)c[j]=e[j]}else console.warn("#"+
b+" is undefined.")}function z(c){for(var b=(c=c||h.documentElement)?c.querySelectorAll("*[data-l10n-id]"):[],e=b.length,d=0;d<e;d++)y(b[d]);y(c)}var g={},t="",i="textContent",p="",q={},j="loading",D=!0;q.plural=function(c,b,e,d){b=parseFloat(b);if(isNaN(b)||d!=i)return c;q._pluralRules||(q._pluralRules=F(p));var a="["+q._pluralRules(b)+"]";0===b&&e+"[zero]"in g?c=g[e+"[zero]"][d]:1==b&&e+"[one]"in g?c=g[e+"[one]"][d]:2==b&&e+"[two]"in g?c=g[e+"[two]"][d]:e+a in g?c=g[e+a][d]:e+"[other]"in g&&(c=
g[e+"[other]"][d]);return c};return{get:function(c,b,e){var d=c.lastIndexOf("."),a=i;0<d&&(a=c.substr(d+1),c=c.substring(0,d));var f;e&&(f={},f[a]=e);return(b=x(c,b,f))&&a in b?b[a]:"{{"+c+"}}"},getData:function(){return g},getText:function(){return t},getLanguage:function(){return p},setLanguage:function(c){E(c,z)},getDirection:function(){return 0<=["ar","he","fa","ps","ur"].indexOf(p.split("-")[0])?"rtl":"ltr"},translate:z,getReadyState:function(){return j},ready:function(c){c&&("complete"==j||
"interactive"==j?A.setTimeout(c):h.addEventListener?h.addEventListener("localized",c):h.attachEvent&&h.documentElement.attachEvent("onpropertychange",function(b){"localized"===b.propertyName&&c()}))}}}(window,document);
