var DEFAULT_URL="compressed.tracemonkey-pldi-09.pdf",DEFAULT_SCALE="auto",DEFAULT_SCALE_DELTA=1.1,UNKNOWN_SCALE=0,CACHE_SIZE=20,CSS_UNITS=96/72,SCROLLBAR_PADDING=40,VERTICAL_PADDING=5,MAX_AUTO_SCALE=1.25,MIN_SCALE=0.25,MAX_SCALE=4,VIEW_HISTORY_MEMORY=20,SCALE_SELECT_CONTAINER_PADDING=8,SCALE_SELECT_PADDING=22,THUMBNAIL_SCROLL_MARGIN=-19,USE_ONLY_CSS_ZOOM=!1,CLEANUP_TIMEOUT=3E4,IGNORE_CURRENT_POSITION_ON_ZOOM=!1,RenderingStates={INITIAL:0,RUNNING:1,PAUSED:2,FINISHED:3},FindStates={FIND_FOUND:0,FIND_NOTFOUND:1,
FIND_WRAPPED:2,FIND_PENDING:3};PDFJS.imageResourcesPath="./images/";PDFJS.workerSrc="../build/pdf.worker.js";
var mozL10n=document.mozL10n||document.webL10n,CustomStyle=function(){function a(){}var b=["ms","Moz","Webkit","O"],c={};a.getProp=function(a,d){if(1==arguments.length&&"string"==typeof c[a])return c[a];var d=d||document.documentElement,g=d.style,h,f;if("string"==typeof g[a])return c[a]=a;f=a.charAt(0).toUpperCase()+a.slice(1);for(var j=0,o=b.length;j<o;j++)if(h=b[j]+f,"string"==typeof g[h])return c[a]=h;return c[a]="undefined"};a.setProp=function(a,b,c){a=this.getProp(a);"undefined"!=a&&(b.style[a]=
c)};return a}();function getFileName(a){var b=a.indexOf("#"),c=a.indexOf("?"),b=Math.min(0<b?b:a.length,0<c?c:a.length);return a.substring(a.lastIndexOf("/",b)+1,b)}function getOutputScale(a){a=(window.devicePixelRatio||1)/(a.webkitBackingStorePixelRatio||a.mozBackingStorePixelRatio||a.msBackingStorePixelRatio||a.oBackingStorePixelRatio||a.backingStorePixelRatio||1);return{sx:a,sy:a,scaled:1!=a}}
function scrollIntoView(a,b){var c=a.offsetParent,e=a.offsetTop+a.clientTop,d=a.offsetLeft+a.clientLeft;if(c){for(;c.clientHeight===c.scrollHeight;)if(c.dataset._scaleY&&(e/=c.dataset._scaleY,d/=c.dataset._scaleX),e+=c.offsetTop,d+=c.offsetLeft,c=c.offsetParent,!c)return;b&&(void 0!==b.top&&(e+=b.top),void 0!==b.left&&(d+=b.left,c.scrollLeft=d));c.scrollTop=e}else console.error("offsetParent is not set -- cannot scroll")}function noContextMenuHandler(a){a.preventDefault()}
function getPDFFileNameFromURL(a){var b=/[^\/?#=]+\.pdf\b(?!.*\.pdf\b)/i,a=/^(?:([^:]+:)?\/\/[^\/]+)?([^?#]*)(\?[^#]*)?(#.*)?$/.exec(a);if(a=b.exec(a[1])||b.exec(a[2])||b.exec(a[3]))if(a=a[0],-1!=a.indexOf("%"))try{a=b.exec(decodeURIComponent(a))[0]}catch(c){}return a||"document.pdf"}
var ProgressBar=function(){function a(a,c){this.div=document.querySelector(a+" .progress");this.bar=this.div.parentNode;this.height=c.height||100;this.width=c.width||100;this.units=c.units||"%";this.div.style.height=this.height+this.units;this.percent=0}a.prototype={updateBar:function(){this._indeterminate?(this.div.classList.add("indeterminate"),this.div.style.width=this.width+this.units):(this.div.classList.remove("indeterminate"),this.div.style.width=this.width*this._percent/100+this.units)},get percent(){return this._percent},
set percent(a){this._indeterminate=isNaN(a);this._percent=Math.min(Math.max(a,0),100);this.updateBar()},setWidth:function(a){a&&(a=a.parentNode.offsetWidth-a.offsetWidth,0<a&&this.bar.setAttribute("style","width: calc(100% - "+a+"px);"))},hide:function(){this.bar.classList.add("hidden");this.bar.removeAttribute("style")}};return a}(),Cache=function(a){var b=[];this.push=function(c){var e=b.indexOf(c);0<=e&&b.splice(e);b.push(c);b.length>a&&b.shift().destroy()}},isLocalStorageEnabled=function(){try{return"localStorage"in
window&&null!==window.localStorage&&localStorage}catch(a){return!1}}(),EXPORTED_SYMBOLS=["DEFAULT_PREFERENCES"],DEFAULT_PREFERENCES={showPreviousViewOnLoad:!0,defaultZoomValue:"",ifAvailableShowOutlineOnLoad:!1},Preferences=function(){function a(){this.prefs={};this.isInitializedPromiseResolved=!1;this.initializedPromise=this.readFromStorage(DEFAULT_PREFERENCES).then(function(a){this.isInitializedPromiseResolved=!0;a&&(this.prefs=a)}.bind(this))}a.prototype={writeToStorage:function(){},readFromStorage:function(){return Promise.resolve()},
reset:function(){this.isInitializedPromiseResolved&&(this.prefs={},this.writeToStorage(DEFAULT_PREFERENCES))},set:function(a,c){if(this.isInitializedPromiseResolved)if(void 0===DEFAULT_PREFERENCES[a])console.error("Preferences_set: '"+a+"' is undefined.");else if(void 0===c)console.error("Preferences_set: no value is specified.");else{var e=typeof c,d=typeof DEFAULT_PREFERENCES[a];if(e!==d)if("number"===e&&"string"===d)c=c.toString();else{console.error("Preferences_set: '"+c+"' is a \""+e+'", expected a "'+
d+'".');return}else if("number"===e&&(c|0)!==c){console.error("Preferences_set: '"+c+'\' must be an "integer".');return}this.prefs[a]=c;this.writeToStorage(this.prefs)}},get:function(a){var c=DEFAULT_PREFERENCES[a];if(void 0===c)console.error("Preferences_get: '"+a+"' is undefined.");else return this.isInitializedPromiseResolved&&(a=this.prefs[a],void 0!==a)?a:c}};return a}();Preferences.prototype.writeToStorage=function(a){isLocalStorageEnabled&&localStorage.setItem("pdfjs.preferences",JSON.stringify(a))};
Preferences.prototype.readFromStorage=function(){return new Promise(function(a){if(isLocalStorageEnabled){var b=JSON.parse(localStorage.getItem("pdfjs.preferences"));a(b)}})};
(function(){function a(a){var b=document.createEvent("CustomEvent");b.initCustomEvent(a,!1,!1,"custom");window.dispatchEvent(b)}function b(){if(d)if(e(),++g<d.length){var a=d[g];"function"===typeof a.mozPrintCallback?a.mozPrintCallback({context:a.getContext("2d"),abort:c,done:b}):b()}else e(),h.call(window),setTimeout(c,20)}function c(){d&&(d=null,e(),a("afterprint"))}function e(){var a=document.getElementById("mozPrintCallback-shim");if(d){var b=Math.round(100*g/d.length),e=a.querySelector("progress"),
h=a.querySelector(".relative-progress");e.value=b;h.textContent=b+"%";a.removeAttribute("hidden");a.onclick=c}else a.setAttribute("hidden","")}if(!("mozPrintCallback"in document.createElement("canvas"))){HTMLCanvasElement.prototype.mozPrintCallback=void 0;var d,g,h=window.print;window.print=function(){if(d)console.warn("Ignored window.print() because of a pending print job.");else try{a("beforeprint")}finally{d=document.querySelectorAll("canvas"),g=-1,b()}};var f=!!document.attachEvent;window.addEventListener("keydown",
function(a){80===a.keyCode&&(a.ctrlKey||a.metaKey)&&!a.altKey&&(!a.shiftKey||window.chrome||window.opera)?(window.print(),f||(a.preventDefault(),a.stopImmediatePropagation?a.stopImmediatePropagation():a.stopPropagation())):27===a.keyCode&&d&&c()},!0);f&&document.attachEvent("onkeydown",function(a){a=a||window.event;if(80===a.keyCode&&a.ctrlKey)return a.keyCode=0,!1});if("onbeforeprint"in window){var j=function(a){"custom"!==a.detail&&a.stopImmediatePropagation&&a.stopImmediatePropagation()};window.addEventListener("beforeprint",
j,!1);window.addEventListener("afterprint",j,!1)}}})();
var DownloadManager=function(){function a(a,b){var d=document.createElement("a");d.click?(d.href=a,d.target="_parent","download"in d&&(d.download=b),(document.body||document.documentElement).appendChild(d),d.click(),d.parentNode.removeChild(d)):(window.top===window&&a.split("#")[0]===window.location.href.split("#")[0]&&(d=-1===a.indexOf("?")?"?":"&",a=a.replace(/#|$/,d+"$&")),window.open(a,"_parent"))}function b(){}b.prototype={downloadUrl:function(b,e){PDFJS.isValidUrl(b,!0)&&a(b+"#pdfjs.action=download",
e)},download:function(b,e,d){URL?navigator.msSaveBlob?navigator.msSaveBlob(b,d)||this.downloadUrl(e,d):(b=URL.createObjectURL(b),a(b,d)):this.downloadUrl(e,d)}};return b}(),cache=new Cache(CACHE_SIZE),currentPageNumber=1,ViewHistory=function(){function a(a){this.fingerprint=a;var c;this.isInitializedPromiseResolved=!1;this.initializedPromise=new Promise(function(a){c=a});a=function(a){this.isInitializedPromiseResolved=!0;this.initialize(a||"{}");c()}.bind(this);isLocalStorageEnabled&&a(localStorage.getItem("database"))}
a.prototype={initialize:function(a){a=JSON.parse(a);"files"in a||(a.files=[]);a.files.length>=VIEW_HISTORY_MEMORY&&a.files.shift();for(var c,e=0,d=a.files.length;e<d;e++)if(a.files[e].fingerprint===this.fingerprint){c=e;break}"number"!==typeof c&&(c=a.files.push({fingerprint:this.fingerprint})-1);this.file=a.files[c];this.database=a},set:function(a,c){if(this.isInitializedPromiseResolved){this.file[a]=c;var e=JSON.stringify(this.database);isLocalStorageEnabled&&localStorage.setItem("database",e)}},
get:function(a,c){return!this.isInitializedPromiseResolved?c:this.file[a]||c}};return a}(),PDFFindBar={opened:!1,bar:null,toggleButton:null,findField:null,highlightAll:null,caseSensitive:null,findMsg:null,findStatusIcon:null,findPreviousButton:null,findNextButton:null,initialize:function(a){if("undefined"===typeof PDFFindController||null===PDFFindController)throw"PDFFindBar cannot be initialized without a PDFFindController instance.";this.bar=a.bar;this.toggleButton=a.toggleButton;this.findField=
a.findField;this.highlightAll=a.highlightAllCheckbox;this.caseSensitive=a.caseSensitiveCheckbox;this.findMsg=a.findMsg;this.findStatusIcon=a.findStatusIcon;this.findPreviousButton=a.findPreviousButton;this.findNextButton=a.findNextButton;var b=this;this.toggleButton.addEventListener("click",function(){b.toggle()});this.findField.addEventListener("input",function(){b.dispatchEvent("")});this.bar.addEventListener("keydown",function(a){switch(a.keyCode){case 13:a.target===b.findField&&b.dispatchEvent("again",
a.shiftKey);break;case 27:b.close()}});this.findPreviousButton.addEventListener("click",function(){b.dispatchEvent("again",!0)});this.findNextButton.addEventListener("click",function(){b.dispatchEvent("again",!1)});this.highlightAll.addEventListener("click",function(){b.dispatchEvent("highlightallchange")});this.caseSensitive.addEventListener("click",function(){b.dispatchEvent("casesensitivitychange")})},dispatchEvent:function(a,b){var c=document.createEvent("CustomEvent");c.initCustomEvent("find"+
a,!0,!0,{query:this.findField.value,caseSensitive:this.caseSensitive.checked,highlightAll:this.highlightAll.checked,findPrevious:b});return window.dispatchEvent(c)},updateUIState:function(a,b){var c=!1,e="",d="";switch(a){case FindStates.FIND_PENDING:d="pending";break;case FindStates.FIND_NOTFOUND:e=mozL10n.get("find_not_found",null,"Phrase not found");c=!0;break;case FindStates.FIND_WRAPPED:e=b?mozL10n.get("find_reached_top",null,"Reached top of document, continued from bottom"):mozL10n.get("find_reached_bottom",
null,"Reached end of document, continued from top")}c?this.findField.classList.add("notFound"):this.findField.classList.remove("notFound");this.findField.setAttribute("data-status",d);this.findMsg.textContent=e},open:function(){this.opened||(this.opened=!0,this.toggleButton.classList.add("toggled"),this.bar.classList.remove("hidden"));this.findField.select();this.findField.focus()},close:function(){this.opened&&(this.opened=!1,this.toggleButton.classList.remove("toggled"),this.bar.classList.add("hidden"),
PDFFindController.active=!1)},toggle:function(){this.opened?this.close():this.open()}},PDFFindController={startedTextExtraction:!1,extractTextPromises:[],pendingFindMatches:{},active:!1,pageContents:[],pageMatches:[],selected:{pageIdx:-1,matchIdx:-1},offset:{pageIdx:null,matchIdx:null},resumePageIdx:null,state:null,dirtyMatch:!1,findTimeout:null,pdfPageSource:null,integratedFind:!1,initialize:function(a){if("undefined"===typeof PDFFindBar||null===PDFFindBar)throw"PDFFindController cannot be initialized without a PDFFindController instance";
this.pdfPageSource=a.pdfPageSource;this.integratedFind=a.integratedFind;a=["find","findagain","findhighlightallchange","findcasesensitivitychange"];this.firstPagePromise=new Promise(function(a){this.resolveFirstPage=a}.bind(this));this.handleEvent=this.handleEvent.bind(this);for(var b=0;b<a.length;b++)window.addEventListener(a[b],this.handleEvent)},reset:function(){this.startedTextExtraction=!1;this.extractTextPromises=[];this.active=!1},calcFindMatch:function(a){var b=this.pageContents[a],c=this.state.query,
e=c.length;if(0!==e){this.state.caseSensitive||(b=b.toLowerCase(),c=c.toLowerCase());for(var d=[],g=-e;;){g=b.indexOf(c,g+e);if(-1===g)break;d.push(g)}this.pageMatches[a]=d;this.updatePage(a);this.resumePageIdx===a&&(this.resumePageIdx=null,this.nextPageMatch())}},extractText:function(){function a(c){d.pdfPageSource.pages[c].getTextContent().then(function(e){for(var f="",j=0;j<e.length;j++)f+=e[j].str;d.pageContents.push(f);b[c](c);c+1<d.pdfPageSource.pages.length&&a(c+1)})}if(!this.startedTextExtraction){this.startedTextExtraction=
!0;this.pageContents=[];for(var b=[],c=0,e=this.pdfPageSource.pdfDocument.numPages;c<e;c++)this.extractTextPromises.push(new Promise(function(a){b.push(a)}));var d=this;a(0)}},handleEvent:function(a){if(null===this.state||"findagain"!==a.type)this.dirtyMatch=!0;this.state=a.detail;this.updateUIState(FindStates.FIND_PENDING);this.firstPagePromise.then(function(){this.extractText();clearTimeout(this.findTimeout);"find"===a.type?this.findTimeout=setTimeout(this.nextMatch.bind(this),250):this.nextMatch()}.bind(this))},
updatePage:function(a){var b=this.pdfPageSource.pages[a];this.selected.pageIdx===a&&b.scrollIntoView();b.textLayer&&b.textLayer.updateMatches()},nextMatch:function(){var a=this.state.findPrevious,b=this.pdfPageSource.page-1,c=this.pdfPageSource.pages.length;this.active=!0;if(this.dirtyMatch){this.dirtyMatch=!1;this.selected.pageIdx=this.selected.matchIdx=-1;this.offset.pageIdx=b;this.offset.matchIdx=null;this.hadMatch=!1;this.resumePageIdx=null;this.pageMatches=[];for(var e=this,b=0;b<c;b++)this.updatePage(b),
b in this.pendingFindMatches||(this.pendingFindMatches[b]=!0,this.extractTextPromises[b].then(function(a){delete e.pendingFindMatches[a];e.calcFindMatch(a)}))}if(""===this.state.query)this.updateUIState(FindStates.FIND_FOUND);else if(!this.resumePageIdx){c=this.offset;if(null!==c.matchIdx){b=this.pageMatches[c.pageIdx].length;if(!a&&c.matchIdx+1<b||a&&0<c.matchIdx){this.hadMatch=!0;c.matchIdx=a?c.matchIdx-1:c.matchIdx+1;this.updateMatch(!0);return}this.advanceOffsetPage(a)}this.nextPageMatch()}},
matchesReady:function(a){var b=this.offset,a=a.length,c=this.state.findPrevious;if(a)return this.hadMatch=!0,b.matchIdx=c?a-1:0,this.updateMatch(!0),!0;this.advanceOffsetPage(c);return b.wrapped&&(b.matchIdx=null,!this.hadMatch)?(this.updateMatch(!1),!0):!1},nextPageMatch:function(){null!==this.resumePageIdx&&console.error("There can only be one pending page.");do{var a=this.offset.pageIdx,b=this.pageMatches[a];if(!b){this.resumePageIdx=a;break}}while(!this.matchesReady(b))},advanceOffsetPage:function(a){var b=
this.offset,c=this.extractTextPromises.length;b.pageIdx=a?b.pageIdx-1:b.pageIdx+1;b.matchIdx=null;if(b.pageIdx>=c||0>b.pageIdx)b.pageIdx=a?c-1:0,b.wrapped=!0},updateMatch:function(a){var b=FindStates.FIND_NOTFOUND,c=this.offset.wrapped;this.offset.wrapped=!1;a&&(a=this.selected.pageIdx,this.selected.pageIdx=this.offset.pageIdx,this.selected.matchIdx=this.offset.matchIdx,b=c?FindStates.FIND_WRAPPED:FindStates.FIND_FOUND,-1!==a&&a!==this.selected.pageIdx&&this.updatePage(a));this.updateUIState(b,this.state.findPrevious);
-1!==this.selected.pageIdx&&this.updatePage(this.selected.pageIdx,!0)},updateUIState:function(a,b){this.integratedFind?FirefoxCom.request("updateFindControlState",{result:a,findPrevious:b}):PDFFindBar.updateUIState(a,b)}},PDFHistory={initialized:!1,initialDestination:null,initialize:function(a){function b(){var a=c._getPreviousParams(null,!0);a&&(c._pushToHistory(a,!1,!c.current.dest&&c.current.hash!==c.previousHash),c._updatePreviousBookmark());window.removeEventListener("beforeunload",b,!1)}if(!PDFJS.disableHistory&&
!PDFView.isViewerEmbedded){this.initialized=!0;this.reInitialized=!1;this.historyUnlocked=this.allowHashChange=!0;this.previousHash=window.location.hash.substring(1);this.currentBookmark="";this.currentPage=0;this.updatePreviousBookmark=!1;this.previousBookmark="";this.previousPage=0;this.nextHashParam="";this.fingerprint=a;this.currentUid=this.uid=0;this.current={};a=window.history.state;this._isStateObjectDefined(a)?(a.target.dest?this.initialDestination=a.target.dest:PDFView.initialBookmark=a.target.hash,
this.currentUid=a.uid,this.uid=a.uid+1,this.current=a.target):(a&&a.fingerprint&&this.fingerprint!==a.fingerprint&&(this.reInitialized=!0),this._pushOrReplaceState({fingerprint:this.fingerprint},!0));var c=this;window.addEventListener("popstate",function(a){a.preventDefault();a.stopPropagation();c.historyUnlocked&&(a.state?c._goTo(a.state):(c.previousHash=window.location.hash.substring(1),0===c.uid&&(a=c.previousHash&&c.currentBookmark&&c.previousHash!==c.currentBookmark?{hash:c.currentBookmark,page:c.currentPage}:
{page:1},c.historyUnlocked=!1,c.allowHashChange=!1,window.history.back(),c._pushToHistory(a,!1,!0),window.history.forward(),c.historyUnlocked=!0),c._pushToHistory({hash:c.previousHash},!1,!0),c._updatePreviousBookmark()))},!1);window.addEventListener("beforeunload",b,!1);window.addEventListener("pageshow",function(){window.addEventListener("beforeunload",b,!1)},!1)}},_isStateObjectDefined:function(a){return a&&0<=a.uid&&a.fingerprint&&this.fingerprint===a.fingerprint&&a.target&&a.target.hash?!0:!1},
_pushOrReplaceState:function(a,b){b?window.history.replaceState(a,"",document.URL):window.history.pushState(a,"",document.URL)},get isHashChangeUnlocked(){if(!this.initialized)return!0;var a=this.allowHashChange;this.allowHashChange=!0;return a},_updatePreviousBookmark:function(){this.updatePreviousBookmark&&this.currentBookmark&&this.currentPage&&(this.previousBookmark=this.currentBookmark,this.previousPage=this.currentPage,this.updatePreviousBookmark=!1)},updateCurrentBookmark:function(a,b){this.initialized&&
(this.currentBookmark=a.substring(1),this.currentPage=b|0,this._updatePreviousBookmark())},updateNextHashParam:function(a){this.initialized&&(this.nextHashParam=a)},push:function(a,b){if(this.initialized&&this.historyUnlocked)if(a.dest&&!a.hash&&(a.hash=this.current.hash&&this.current.dest&&this.current.dest===a.dest?this.current.hash:PDFView.getDestinationHash(a.dest).split("#")[1]),a.page&&(a.page|=0),b){var c=window.history.state.target;c||(this._pushToHistory(a,!1),this.previousHash=window.location.hash.substring(1));
this.updatePreviousBookmark=this.nextHashParam?!1:!0;c&&this._updatePreviousBookmark()}else{if(this.nextHashParam){if(this.nextHashParam===a.hash){this.nextHashParam=null;this.updatePreviousBookmark=!0;return}this.nextHashParam=null}a.hash?this.current.hash?this.current.hash!==a.hash?this._pushToHistory(a,!0):(!this.current.page&&a.page&&this._pushToHistory(a,!1,!0),this.updatePreviousBookmark=!0):this._pushToHistory(a,!0):this.current.page&&a.page&&this.current.page!==a.page&&this._pushToHistory(a,
!0)}},_getPreviousParams:function(a,b){if(!this.currentBookmark||!this.currentPage)return null;this.updatePreviousBookmark&&(this.updatePreviousBookmark=!1);if(0<this.uid&&(!this.previousBookmark||!this.previousPage))return null;if(!this.current.dest&&!a||b){if(this.previousBookmark===this.currentBookmark)return null}else if(this.current.page||a){if(this.previousPage===this.currentPage)return null}else return null;var c={hash:this.currentBookmark,page:this.currentPage};PresentationMode.active&&(c.hash=
null);return c},_stateObj:function(a){return{fingerprint:this.fingerprint,uid:this.uid,target:a}},_pushToHistory:function(a,b,c){this.initialized&&(!a.hash&&a.page&&(a.hash="page="+a.page),b&&!c&&(b=this._getPreviousParams())&&this._pushToHistory(b,!1,!this.current.dest&&this.current.hash!==this.previousHash),this._pushOrReplaceState(this._stateObj(a),c||0===this.uid),this.currentUid=this.uid++,this.current=a,this.updatePreviousBookmark=!0)},_goTo:function(a){if(this.initialized&&this.historyUnlocked&&
this._isStateObjectDefined(a)){if(!this.reInitialized&&a.uid<this.currentUid){var b=this._getPreviousParams(!0);if(b){this._pushToHistory(this.current,!1);this._pushToHistory(b,!1);this.currentUid=a.uid;window.history.back();return}}this.historyUnlocked=!1;a.target.dest?PDFView.navigateTo(a.target.dest):PDFView.setHash(a.target.hash);this.currentUid=a.uid;a.uid>this.uid&&(this.uid=a.uid);this.current=a.target;this.updatePreviousBookmark=!0;a=window.location.hash.substring(1);this.previousHash!==a&&
(this.allowHashChange=!1);this.previousHash=a;this.historyUnlocked=!0}},back:function(){this.go(-1)},forward:function(){this.go(1)},go:function(a){if(this.initialized&&this.historyUnlocked){var b=window.history.state;-1===a&&b&&0<b.uid?window.history.back():1===a&&b&&b.uid<this.uid-1&&window.history.forward()}}},SecondaryToolbar={opened:!1,previousContainerHeight:null,newContainerHeight:null,initialize:function(a){this.toolbar=a.toolbar;this.presentationMode=a.presentationMode;this.documentProperties=
a.documentProperties;this.buttonContainer=this.toolbar.firstElementChild;this.toggleButton=a.toggleButton;this.presentationModeButton=a.presentationModeButton;this.openFile=a.openFile;this.print=a.print;this.download=a.download;this.viewBookmark=a.viewBookmark;this.firstPage=a.firstPage;this.lastPage=a.lastPage;this.pageRotateCw=a.pageRotateCw;this.pageRotateCcw=a.pageRotateCcw;this.documentPropertiesButton=a.documentPropertiesButton;var a=[{element:this.toggleButton,handler:this.toggle},{element:this.presentationModeButton,
handler:this.presentationModeClick},{element:this.openFile,handler:this.openFileClick},{element:this.print,handler:this.printClick},{element:this.download,handler:this.downloadClick},{element:this.viewBookmark,handler:this.viewBookmarkClick},{element:this.firstPage,handler:this.firstPageClick},{element:this.lastPage,handler:this.lastPageClick},{element:this.pageRotateCw,handler:this.pageRotateCwClick},{element:this.pageRotateCcw,handler:this.pageRotateCcwClick},{element:this.documentPropertiesButton,
handler:this.documentPropertiesClick}],b;for(b in a){var c=a[b].element;c&&c.addEventListener("click",a[b].handler.bind(this))}},presentationModeClick:function(){this.presentationMode.request();this.close()},openFileClick:function(){document.getElementById("fileInput").click();this.close()},printClick:function(){window.print();this.close()},downloadClick:function(){PDFView.download();this.close()},viewBookmarkClick:function(){this.close()},firstPageClick:function(){PDFView.page=1;this.close()},lastPageClick:function(){PDFView.page=
PDFView.pdfDocument.numPages;this.close()},pageRotateCwClick:function(){PDFView.rotatePages(90)},pageRotateCcwClick:function(){PDFView.rotatePages(-90)},documentPropertiesClick:function(){this.documentProperties.show();this.close()},setMaxHeight:function(a){a&&this.buttonContainer&&(this.newContainerHeight=a.clientHeight,this.previousContainerHeight!==this.newContainerHeight&&(this.buttonContainer.setAttribute("style","max-height: "+(this.newContainerHeight-SCROLLBAR_PADDING)+"px;"),this.previousContainerHeight=
this.newContainerHeight))},open:function(){this.opened||(this.opened=!0,this.toggleButton.classList.add("toggled"),this.toolbar.classList.remove("hidden"))},close:function(a){if(this.opened&&(!a||this.toolbar.contains(a)))this.opened=!1,this.toolbar.classList.add("hidden"),this.toggleButton.classList.remove("toggled")},toggle:function(){this.opened?this.close():this.open()}},PasswordPrompt={visible:!1,updatePassword:null,reason:null,overlayContainer:null,passwordField:null,passwordText:null,passwordSubmit:null,
passwordCancel:null,initialize:function(a){this.overlayContainer=a.overlayContainer;this.passwordField=a.passwordField;this.passwordText=a.passwordText;this.passwordSubmit=a.passwordSubmit;this.passwordCancel=a.passwordCancel;this.passwordSubmit.addEventListener("click",this.verifyPassword.bind(this));this.passwordCancel.addEventListener("click",this.hide.bind(this));this.passwordField.addEventListener("keydown",function(a){13===a.keyCode&&this.verifyPassword()}.bind(this));window.addEventListener("keydown",
function(a){27===a.keyCode&&this.hide()}.bind(this))},show:function(){if(!this.visible){this.visible=!0;this.overlayContainer.classList.remove("hidden");this.overlayContainer.firstElementChild.classList.remove("hidden");this.passwordField.focus();var a=mozL10n.get("password_label",null,"Enter the password to open this PDF file.");this.reason===PDFJS.PasswordResponses.INCORRECT_PASSWORD&&(a=mozL10n.get("password_invalid",null,"Invalid password. Please try again."));this.passwordText.textContent=a}},
hide:function(){this.visible&&(this.visible=!1,this.passwordField.value="",this.overlayContainer.classList.add("hidden"),this.overlayContainer.firstElementChild.classList.add("hidden"))},verifyPassword:function(){var a=this.passwordField.value;if(a&&0<a.length)return this.hide(),this.updatePassword(a)}},DELAY_BEFORE_HIDING_CONTROLS=3E3,SELECTOR="presentationControls",DELAY_BEFORE_RESETTING_SWITCH_IN_PROGRESS=1E3,PresentationMode={active:!1,args:null,contextMenuOpen:!1,prevCoords:{x:null,y:null},initialize:function(a){this.container=
a.container;this.secondaryToolbar=a.secondaryToolbar;this.viewer=this.container.firstElementChild;this.firstPage=a.firstPage;this.lastPage=a.lastPage;this.pageRotateCw=a.pageRotateCw;this.pageRotateCcw=a.pageRotateCcw;this.firstPage.addEventListener("click",function(){this.contextMenuOpen=!1;this.secondaryToolbar.firstPageClick()}.bind(this));this.lastPage.addEventListener("click",function(){this.contextMenuOpen=!1;this.secondaryToolbar.lastPageClick()}.bind(this));this.pageRotateCw.addEventListener("click",
function(){this.contextMenuOpen=!1;this.secondaryToolbar.pageRotateCwClick()}.bind(this));this.pageRotateCcw.addEventListener("click",function(){this.contextMenuOpen=!1;this.secondaryToolbar.pageRotateCcwClick()}.bind(this))},get isFullscreen(){return document.fullscreenElement||document.mozFullScreen||document.webkitIsFullScreen||document.msFullscreenElement},_setSwitchInProgress:function(){this.switchInProgress&&clearTimeout(this.switchInProgress);this.switchInProgress=setTimeout(function(){delete this.switchInProgress}.bind(this),
DELAY_BEFORE_RESETTING_SWITCH_IN_PROGRESS);PDFView.currentPosition=null},_resetSwitchInProgress:function(){this.switchInProgress&&(clearTimeout(this.switchInProgress),delete this.switchInProgress)},request:function(){if(!PDFView.supportsFullscreen||this.isFullscreen||!this.viewer.hasChildNodes())return!1;this._setSwitchInProgress();if(this.container.requestFullscreen)this.container.requestFullscreen();else if(this.container.mozRequestFullScreen)this.container.mozRequestFullScreen();else if(this.container.webkitRequestFullScreen)this.container.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);
else if(this.container.msRequestFullscreen)this.container.msRequestFullscreen();else return!1;this.args={page:PDFView.page,previousScale:PDFView.currentScaleValue};return!0},enter:function(){this.active=!0;this._resetSwitchInProgress();setTimeout(function(){PDFView.page=this.args.page;PDFView.setScale("page-fit",!0)}.bind(this),0);window.addEventListener("mousemove",this.mouseMove,!1);window.addEventListener("mousedown",this.mouseDown,!1);window.addEventListener("contextmenu",this.contextMenu,!1);
this.showControls();HandTool.enterPresentationMode();this.contextMenuOpen=!1;this.container.setAttribute("contextmenu","viewerContextMenu")},exit:function(){var a=PDFView.page;setTimeout(function(){PDFView.setScale(this.args.previousScale);PDFView.page=a;this.active=!1;this.args=null}.bind(this),0);window.removeEventListener("mousemove",this.mouseMove,!1);window.removeEventListener("mousedown",this.mouseDown,!1);window.removeEventListener("contextmenu",this.contextMenu,!1);this.hideControls();PDFView.clearMouseScrollState();
HandTool.exitPresentationMode();this.container.removeAttribute("contextmenu");this.contextMenuOpen=!1;scrollIntoView(document.getElementById("thumbnailContainer"+a))},showControls:function(){this.controlsTimeout?clearTimeout(this.controlsTimeout):this.container.classList.add(SELECTOR);this.controlsTimeout=setTimeout(function(){this.container.classList.remove(SELECTOR);delete this.controlsTimeout}.bind(this),DELAY_BEFORE_HIDING_CONTROLS)},hideControls:function(){this.controlsTimeout&&(this.container.classList.remove(SELECTOR),
clearTimeout(this.controlsTimeout),delete this.controlsTimeout)},mouseMove:function(a){var a={x:a.clientX,y:a.clientY},b=PresentationMode.prevCoords;PresentationMode.prevCoords=a;a.x===b.x&&a.y===b.y||PresentationMode.showControls()},mouseDown:function(a){var b=PresentationMode;if(b.contextMenuOpen)b.contextMenuOpen=!1,a.preventDefault();else if(0===a.button&&(!a.target.href||!a.target.classList.contains("internalLink")))a.preventDefault(),PDFView.page+=a.shiftKey?-1:1},contextMenu:function(){PresentationMode.contextMenuOpen=
!0}};(function(){function a(){PresentationMode.isFullscreen?PresentationMode.enter():PresentationMode.exit()}window.addEventListener("fullscreenchange",a,!1);window.addEventListener("mozfullscreenchange",a,!1);window.addEventListener("webkitfullscreenchange",a,!1);window.addEventListener("MSFullscreenChange",a,!1)})();"use strict";
var GrabToPan=function(){function a(a){this.element=a.element;this.document=a.element.ownerDocument;"function"===typeof a.ignoreTarget&&(this.ignoreTarget=a.ignoreTarget);this.onActiveChanged=a.onActiveChanged;this.activate=this.activate.bind(this);this.deactivate=this.deactivate.bind(this);this.toggle=this.toggle.bind(this);this._onmousedown=this._onmousedown.bind(this);this._onmousemove=this._onmousemove.bind(this);this._endPan=this._endPan.bind(this);(this.overlay=document.createElement("div")).className=
"grab-to-pan-grabbing"}a.prototype={CSS_CLASS_GRAB:"grab-to-pan-grab",activate:function(){if(!this.active&&(this.active=!0,this.element.addEventListener("mousedown",this._onmousedown,!0),this.element.classList.add(this.CSS_CLASS_GRAB),this.onActiveChanged))this.onActiveChanged(!0)},deactivate:function(){if(this.active&&(this.active=!1,this.element.removeEventListener("mousedown",this._onmousedown,!0),this._endPan(),this.element.classList.remove(this.CSS_CLASS_GRAB),this.onActiveChanged))this.onActiveChanged(!1)},
toggle:function(){this.active?this.deactivate():this.activate()},ignoreTarget:function(a){return a[b]("a[href], a[href] *, input, textarea, button, button *, select, option")},_onmousedown:function(a){if(!(0!==a.button||this.ignoreTarget(a.target))){if(a.originalTarget)try{a.originalTarget.tagName}catch(b){return}this.scrollLeftStart=this.element.scrollLeft;this.scrollTopStart=this.element.scrollTop;this.clientXStart=a.clientX;this.clientYStart=a.clientY;this.document.addEventListener("mousemove",
this._onmousemove,!0);this.document.addEventListener("mouseup",this._endPan,!0);this.element.addEventListener("scroll",this._endPan,!0);a.preventDefault();a.stopPropagation();this.document.documentElement.classList.add(this.CSS_CLASS_GRABBING)}},_onmousemove:function(a){this.element.removeEventListener("scroll",this._endPan,!0);var b;if("buttons"in a&&c)b=!(a.buttons|1);else if(d||g)b=0===a.which;b?this._endPan():(b=a.clientX-this.clientXStart,this.element.scrollTop=this.scrollTopStart-(a.clientY-
this.clientYStart),this.element.scrollLeft=this.scrollLeftStart-b,this.overlay.parentNode||document.body.appendChild(this.overlay))},_endPan:function(){this.element.removeEventListener("scroll",this._endPan,!0);this.document.removeEventListener("mousemove",this._onmousemove,!0);this.document.removeEventListener("mouseup",this._endPan,!0);this.overlay.parentNode&&this.overlay.parentNode.removeChild(this.overlay)}};var b;["webkitM","mozM","msM","oM","m"].some(function(a){a+="atches";a in document.documentElement&&
(b=a);a+="Selector";a in document.documentElement&&(b=a);return b});var c=!document.documentMode||9<document.documentMode,e=window.chrome,d=e&&(e.webstore||e.app),g=/Apple/.test(navigator.vendor)&&/Version\/([6-9]\d*|[1-5]\d+)/.test(navigator.userAgent);return a}(),HandTool={initialize:function(a){var b=a.toggleHandTool;this.handTool=new GrabToPan({element:a.container,onActiveChanged:function(a){b&&(a?(b.title=mozL10n.get("hand_tool_disable.title",null,"Disable hand tool"),b.firstElementChild.textContent=
mozL10n.get("hand_tool_disable_label",null,"Disable hand tool")):(b.title=mozL10n.get("hand_tool_enable.title",null,"Enable hand tool"),b.firstElementChild.textContent=mozL10n.get("hand_tool_enable_label",null,"Enable hand tool")))}});b&&b.addEventListener("click",this.toggle.bind(this),!1)},toggle:function(){this.handTool.toggle();SecondaryToolbar.close()},enterPresentationMode:function(){this.handTool.active&&(this.wasActive=!0,this.handTool.deactivate())},exitPresentationMode:function(){this.wasActive&&
(this.wasActive=null,this.handTool.activate())}},DocumentProperties={overlayContainer:null,fileName:"",fileSize:"",visible:!1,fileNameField:null,fileSizeField:null,titleField:null,authorField:null,subjectField:null,keywordsField:null,creationDateField:null,modificationDateField:null,creatorField:null,producerField:null,versionField:null,pageCountField:null,initialize:function(a){this.overlayContainer=a.overlayContainer;this.fileNameField=a.fileNameField;this.fileSizeField=a.fileSizeField;this.titleField=
a.titleField;this.authorField=a.authorField;this.subjectField=a.subjectField;this.keywordsField=a.keywordsField;this.creationDateField=a.creationDateField;this.modificationDateField=a.modificationDateField;this.creatorField=a.creatorField;this.producerField=a.producerField;this.versionField=a.versionField;this.pageCountField=a.pageCountField;a.closeButton&&a.closeButton.addEventListener("click",this.hide.bind(this));window.addEventListener("keydown",function(a){27===a.keyCode&&this.hide()}.bind(this))},
getProperties:function(){var a=this;this.fileName=getPDFFileNameFromURL(PDFView.url);PDFView.pdfDocument.getDownloadInfo().then(function(b){a.setFileSize(b.length)});PDFView.pdfDocument.getMetadata().then(function(b){var b=[{field:a.fileNameField,content:a.fileName},{field:a.fileSizeField,content:a.fileSize},{field:a.titleField,content:b.info.Title},{field:a.authorField,content:b.info.Author},{field:a.subjectField,content:b.info.Subject},{field:a.keywordsField,content:b.info.Keywords},{field:a.creationDateField,
content:a.parseDate(b.info.CreationDate)},{field:a.modificationDateField,content:a.parseDate(b.info.ModDate)},{field:a.creatorField,content:b.info.Creator},{field:a.producerField,content:b.info.Producer},{field:a.versionField,content:b.info.PDFFormatVersion},{field:a.pageCountField,content:PDFView.pdfDocument.numPages}],c;for(c in b){var e=b[c];e.field&&void 0!==e.content&&""!==e.content&&(e.field.textContent=e.content)}})},setFileSize:function(a){var b=a/1024;this.fileSize=1024>b?mozL10n.get("document_properties_kb",
{size_kb:(+b.toPrecision(3)).toLocaleString(),size_b:a.toLocaleString()},"{{size_kb}} KB ({{size_b}} bytes)"):mozL10n.get("document_properties_mb",{size_mb:(+(b/1024).toPrecision(3)).toLocaleString(),size_b:a.toLocaleString()},"{{size_mb}} MB ({{size_b}} bytes)")},show:function(){this.visible||(this.visible=!0,this.overlayContainer.classList.remove("hidden"),this.overlayContainer.lastElementChild.classList.remove("hidden"),this.getProperties())},hide:function(){this.visible&&(this.visible=!1,this.overlayContainer.classList.add("hidden"),
this.overlayContainer.lastElementChild.classList.add("hidden"))},parseDate:function(a){var b=a;if(void 0===b)return"";"D:"===b.substring(0,2)&&(b=b.substring(2));var a=parseInt(b.substring(0,4),10),c=parseInt(b.substring(4,6),10)-1,e=parseInt(b.substring(6,8),10),d=parseInt(b.substring(8,10),10),g=parseInt(b.substring(10,12),10),h=parseInt(b.substring(12,14),10),f=b.substring(14,15),j=parseInt(b.substring(15,17),10),b=parseInt(b.substring(18,20),10);"-"==f?(d+=j,g+=b):"+"==f&&(d-=j,g+=b);c=new Date(Date.UTC(a,
c,e,d,g,h));a=c.toLocaleDateString();c=c.toLocaleTimeString();return mozL10n.get("document_properties_date_string",{date:a,time:c},"{{date}}, {{time}}")}},PDFView={pages:[],thumbnails:[],currentScale:UNKNOWN_SCALE,currentScaleValue:null,initialBookmark:document.location.hash.substring(1),container:null,thumbnailContainer:null,initialized:!1,fellback:!1,pdfDocument:null,sidebarOpen:!1,pageViewScroll:null,thumbnailViewScroll:null,pageRotation:0,mouseScrollTimeStamp:0,mouseScrollDelta:0,lastScroll:0,
previousPageNumber:1,isViewerEmbedded:window.parent!==window,idleTimeout:null,currentPosition:null,initialize:function(){var a=this,b=this.container=document.getElementById("viewerContainer");this.pageViewScroll={};this.watchScroll(b,this.pageViewScroll,updateViewarea);var c=this.thumbnailContainer=document.getElementById("thumbnailView");this.thumbnailViewScroll={};this.watchScroll(c,this.thumbnailViewScroll,this.renderHighestPriority.bind(this));PDFFindBar.initialize({bar:document.getElementById("findbar"),
toggleButton:document.getElementById("viewFind"),findField:document.getElementById("findInput"),highlightAllCheckbox:document.getElementById("findHighlightAll"),caseSensitiveCheckbox:document.getElementById("findMatchCase"),findMsg:document.getElementById("findMsg"),findStatusIcon:document.getElementById("findStatusIcon"),findPreviousButton:document.getElementById("findPrevious"),findNextButton:document.getElementById("findNext")});PDFFindController.initialize({pdfPageSource:this,integratedFind:this.supportsIntegratedFind});
HandTool.initialize({container:b,toggleHandTool:document.getElementById("toggleHandTool")});SecondaryToolbar.initialize({toolbar:document.getElementById("secondaryToolbar"),presentationMode:PresentationMode,toggleButton:document.getElementById("secondaryToolbarToggle"),presentationModeButton:document.getElementById("secondaryPresentationMode"),openFile:document.getElementById("secondaryOpenFile"),print:document.getElementById("secondaryPrint"),download:document.getElementById("secondaryDownload"),
viewBookmark:document.getElementById("secondaryViewBookmark"),firstPage:document.getElementById("firstPage"),lastPage:document.getElementById("lastPage"),pageRotateCw:document.getElementById("pageRotateCw"),pageRotateCcw:document.getElementById("pageRotateCcw"),documentProperties:DocumentProperties,documentPropertiesButton:document.getElementById("documentProperties")});PasswordPrompt.initialize({overlayContainer:document.getElementById("overlayContainer"),passwordField:document.getElementById("password"),
passwordText:document.getElementById("passwordText"),passwordSubmit:document.getElementById("passwordSubmit"),passwordCancel:document.getElementById("passwordCancel")});PresentationMode.initialize({container:b,secondaryToolbar:SecondaryToolbar,firstPage:document.getElementById("contextFirstPage"),lastPage:document.getElementById("contextLastPage"),pageRotateCw:document.getElementById("contextPageRotateCw"),pageRotateCcw:document.getElementById("contextPageRotateCcw")});DocumentProperties.initialize({overlayContainer:document.getElementById("overlayContainer"),
closeButton:document.getElementById("documentPropertiesClose"),fileNameField:document.getElementById("fileNameField"),fileSizeField:document.getElementById("fileSizeField"),titleField:document.getElementById("titleField"),authorField:document.getElementById("authorField"),subjectField:document.getElementById("subjectField"),keywordsField:document.getElementById("keywordsField"),creationDateField:document.getElementById("creationDateField"),modificationDateField:document.getElementById("modificationDateField"),
creatorField:document.getElementById("creatorField"),producerField:document.getElementById("producerField"),versionField:document.getElementById("versionField"),pageCountField:document.getElementById("pageCountField")});this.initialized=!0;b.addEventListener("scroll",function(){a.lastScroll=Date.now()},!1)},getPage:function(a){return this.pdfDocument.getPage(a)},watchScroll:function(a,b,c){b.down=!0;b.lastY=a.scrollTop;a.addEventListener("scroll",function(){var e=a.scrollTop,d=b.lastY;e>d?b.down=
!0:e<d&&(b.down=!1);b.lastY=e;c()},!0)},_setScaleUpdatePages:function(a,b,c,e){this.currentScaleValue=b;if(a!==this.currentScale){for(var b=0,d=this.pages.length;b<d;b++)this.pages[b].update(a);this.currentScale=a;if(!e){var e=this.page,g;this.currentPosition&&!IGNORE_CURRENT_POSITION_ON_ZOOM&&(e=this.currentPosition.page,g=[null,{name:"XYZ"},this.currentPosition.left,this.currentPosition.top,null]);this.pages[e-1].scrollIntoView(g)}g=document.createEvent("UIEvents");g.initUIEvent("scalechange",!1,
!1,window,0);g.scale=a;g.resetAutoSettings=c;window.dispatchEvent(g)}},setScale:function(a,b,c){if("custom"!==a){var e=parseFloat(a);if(0<e)this._setScaleUpdatePages(e,a,!0,c);else{var d=this.pages[this.page-1];if(d){e=(this.container.clientWidth-SCROLLBAR_PADDING)/d.width*d.scale;d=(this.container.clientHeight-VERTICAL_PADDING)/d.height*d.scale;switch(a){case "page-actual":e=1;break;case "page-width":break;case "page-height":e=d;break;case "page-fit":e=Math.min(e,d);break;case "auto":e=Math.min(MAX_AUTO_SCALE,
e);break;default:console.error("pdfViewSetScale: '"+a+"' is an unknown zoom value.");return}this._setScaleUpdatePages(e,a,b,c);selectScaleOption(a)}}}},zoomIn:function(a){var b=this.currentScale;do b=(b*DEFAULT_SCALE_DELTA).toFixed(2),b=Math.ceil(10*b)/10,b=Math.min(MAX_SCALE,b);while(--a&&b<MAX_SCALE);this.setScale(b,!0)},zoomOut:function(a){var b=this.currentScale;do b=(b/DEFAULT_SCALE_DELTA).toFixed(2),b=Math.floor(10*b)/10,b=Math.max(MIN_SCALE,b);while(--a&&b>MIN_SCALE);this.setScale(b,!0)},set page(a){var b=
this.pages,c=document.createEvent("UIEvents");c.initUIEvent("pagechange",!1,!1,window,0);0<a&&a<=b.length?(b[a-1].updateStats(),this.previousPageNumber=currentPageNumber,currentPageNumber=a,c.pageNumber=a,window.dispatchEvent(c),updateViewarea.inProgress||this.loading&&1===a||b[a-1].scrollIntoView()):(this.previousPageNumber=a,c.pageNumber=this.page,window.dispatchEvent(c))},get page(){return currentPageNumber},get supportsPrinting(){var a="mozPrintCallback"in document.createElement("canvas");Object.defineProperty(this,
"supportsPrinting",{value:a,enumerable:!0,configurable:!0,writable:!1});return a},get supportsFullscreen(){var a=document.documentElement,a=a.requestFullscreen||a.mozRequestFullScreen||a.webkitRequestFullScreen||a.msRequestFullscreen;!1===document.fullscreenEnabled||!1===document.mozFullScreenEnabled||!1===document.webkitFullscreenEnabled||!1===document.msFullscreenEnabled?a=!1:this.isViewerEmbedded&&(a=!1);Object.defineProperty(this,"supportsFullscreen",{value:a,enumerable:!0,configurable:!0,writable:!1});
return a},get supportsIntegratedFind(){Object.defineProperty(this,"supportsIntegratedFind",{value:!1,enumerable:!0,configurable:!0,writable:!1});return!1},get supportsDocumentFonts(){Object.defineProperty(this,"supportsDocumentFonts",{value:!0,enumerable:!0,configurable:!0,writable:!1});return!0},get supportsDocumentColors(){Object.defineProperty(this,"supportsDocumentColors",{value:!0,enumerable:!0,configurable:!0,writable:!1});return!0},get loadingBar(){var a=new ProgressBar("#loadingBar",{});Object.defineProperty(this,
"loadingBar",{value:a,enumerable:!0,configurable:!0,writable:!1});return a},get isHorizontalScrollbarEnabled(){return PresentationMode.active?!1:this.container.scrollWidth>this.container.clientWidth},setTitleUsingUrl:function(a){this.url=a;try{this.setTitle(decodeURIComponent(getFileName(a))||a)}catch(b){this.setTitle(a)}},setTitle:function(a){document.title=a},open:function(a,b,c,e,d){c={password:c};"string"===typeof a?(this.setTitleUsingUrl(a),c.url=a):a&&"byteLength"in a&&(c.data=a);if(d)for(var g in d)c[g]=
d[g];this.pdfDocument&&this.pdfDocument.destroy();this.pdfDocument=null;var h=this;h.loading=!0;PDFJS.getDocument(c,e,function(a,b){PasswordPrompt.updatePassword=a;PasswordPrompt.reason=b;PasswordPrompt.show()},function(a){h.progress(a.loaded/a.total)}).then(function(a){h.load(a,b);h.loading=!1},function(a,b){var c=mozL10n.get("loading_error",null,"An error occurred while loading the PDF.");b&&"InvalidPDFException"===b.name&&(c=mozL10n.get("invalid_file_error",null,"Invalid or corrupted PDF file."));
b&&"MissingPDFException"===b.name&&(c=mozL10n.get("missing_file_error",null,"Missing PDF file."));h.error(c,{message:a});h.loading=!1})},download:function(){function a(){e.downloadUrl(b,c)}var b=this.url.split("#")[0],c=getPDFFileNameFromURL(b),e=new DownloadManager;e.onerror=function(){PDFView.error("PDF failed to download.")};this.pdfDocument?this.pdfDocument.getData().then(function(a){a=PDFJS.createBlob(a,"application/pdf");e.download(a,b,c)},a).then(null,a):a()},fallback:function(){},navigateTo:function(a){var b=
"",c=this,e=function(d){c.pendingRefStr=null;var g=d instanceof Object?c.pagesRefMap[d.num+" "+d.gen+" R"]:d+1;g?(g>c.pages.length&&(g=c.pages.length),c.pages[g-1].scrollIntoView(a),PDFHistory.push({dest:a,hash:b,page:g})):c.pdfDocument.getPageIndex(d).then(function(a){c.pagesRefMap[d.num+" "+d.gen+" R"]=a+1;e(d)})};this.destinationsPromise.then(function(){"string"===typeof a&&(b=a,a=c.destinations[a]);a instanceof Array&&e(a[0])})},getDestinationHash:function(a){if("string"===typeof a)return PDFView.getAnchorUrl("#"+
escape(a));if(a instanceof Array){var b=a[0];if(b=b instanceof Object?this.pagesRefMap[b.num+" "+b.gen+" R"]:b+1){var b=PDFView.getAnchorUrl("#page="+b),c=a[1];if("object"===typeof c&&"name"in c&&"XYZ"==c.name){var c=a[4]||this.currentScaleValue,e=parseFloat(c);e&&(c=100*e);b+="&zoom="+c;if(a[2]||a[3])b+=","+(a[2]||0)+","+(a[3]||0)}return b}}return""},getAnchorUrl:function(a){return a},error:function(a,b){var c=mozL10n.get("error_version_info",{version:PDFJS.version||"?",build:PDFJS.build||"?"},"PDF.js v{{version}} (build: {{build}})")+
"\n";b&&(c+=mozL10n.get("error_message",{message:b.message},"Message: {{message}}"),b.stack?c+="\n"+mozL10n.get("error_stack",{stack:b.stack},"Stack: {{stack}}"):(b.filename&&(c+="\n"+mozL10n.get("error_file",{file:b.filename},"File: {{file}}")),b.lineNumber&&(c+="\n"+mozL10n.get("error_line",{line:b.lineNumber},"Line: {{line}}"))));var e=document.getElementById("errorWrapper");e.removeAttribute("hidden");document.getElementById("errorMessage").textContent=a;var d=document.getElementById("errorClose");
d.onclick=function(){e.setAttribute("hidden","true")};var g=document.getElementById("errorMoreInfo"),h=document.getElementById("errorShowMore"),f=document.getElementById("errorShowLess");h.onclick=function(){g.removeAttribute("hidden");h.setAttribute("hidden","true");f.removeAttribute("hidden");g.style.height=g.scrollHeight+"px"};f.onclick=function(){g.setAttribute("hidden","true");h.removeAttribute("hidden");f.setAttribute("hidden","true")};h.oncontextmenu=noContextMenuHandler;f.oncontextmenu=noContextMenuHandler;
d.oncontextmenu=noContextMenuHandler;h.removeAttribute("hidden");f.setAttribute("hidden","true");g.value=c},progress:function(a){a=Math.round(100*a);a>PDFView.loadingBar.percent&&(PDFView.loadingBar.percent=a)},load:function(a,b){function c(a,b){a.onAfterDraw=function(){d||(d=!0,g());b.setImage(a.canvas)}}var e=this,d=!1,g=null,h=new Promise(function(a){g=a});PDFFindController.reset();this.pdfDocument=a;document.getElementById("errorWrapper").setAttribute("hidden","true");a.getDownloadInfo().then(function(){PDFView.loadingBar.hide();
document.getElementById("outerContainer").classList.remove("loadingInProgress")});var f=document.getElementById("thumbnailView");for(f.parentNode.scrollTop=0;f.hasChildNodes();)f.removeChild(f.lastChild);"_loadingInterval"in f&&clearInterval(f._loadingInterval);for(var j=document.getElementById("viewer");j.hasChildNodes();)j.removeChild(j.lastChild);var o=a.numPages,l=a.fingerprint;document.getElementById("numPages").textContent=mozL10n.get("page_of",{pageCount:o},"of {{pageCount}}");document.getElementById("pageNumber").max=
o;var n=PDFView.prefs=new Preferences;PDFView.documentFingerprint=l;var q=PDFView.store=new ViewHistory(l);this.pageRotation=0;var r=this.pages=[],m=this.pagesRefMap={},i=this.thumbnails=[],p;this.pagesPromise=l=new Promise(function(a){p=a});var k=a.getPage(1);k.then(function(d){for(var d=d.getViewport((b||1)*CSS_UNITS),g=1;g<=o;++g){var l=d.clone(),n=new PageView(j,g,b,e.navigateTo.bind(e),l),l=new ThumbnailView(f,g,l);c(n,l);r.push(n);i.push(l)}h.then(function(){if(PDFJS.disableAutoFetch)p();else for(var b=
o,c=1;c<=o;++c)a.getPage(c).then(function(a,c){var e=r[a-1];e.pdfPage||e.setPdfPage(c);m[c.ref.num+" "+c.ref.gen+" R"]=a;b--;b||p()}.bind(null,c))});d=document.createEvent("CustomEvent");d.initCustomEvent("documentload",!0,!0,{});window.dispatchEvent(d);PDFView.loadingBar.setWidth(j);PDFFindController.resolveFirstPage()});Promise.all([k,n.initializedPromise,q.initializedPromise]).then(function(){var a=n.get("showPreviousViewOnLoad"),c=n.get("defaultZoomValue"),d=null;if(a&&q.get("exists",!1))var a=
q.get("page","1"),c=c||q.get("zoom",PDFView.currentScale),d=q.get("scrollLeft","0"),h=q.get("scrollTop","0"),d="page="+a+"&zoom="+c+","+d+","+h;else c&&(d="page=1&zoom="+c);PDFHistory.initialize(e.documentFingerprint);e.setInitialView(d,b);e.isViewerEmbedded||e.container.focus()});l.then(function(){PDFView.supportsPrinting&&a.getJavaScript().then(function(a){a.length&&(console.warn("Warning: JavaScript is not supported"),PDFView.fallback(PDFJS.UNSUPPORTED_FEATURES.javaScript));for(var b=/\bprint\s*\(/g,
c=0,e=a.length;c<e;c++){var d=a[c];if(d&&b.test(d)){setTimeout(function(){window.print()});break}}})});k=this.destinationsPromise=a.getDestinations();k.then(function(a){e.destinations=a});Promise.all([l,k,PDFView.animationStartedPromise]).then(function(){a.getOutline().then(function(a){e.outline=new DocumentOutlineView(a);document.getElementById("viewOutline").disabled=!a;a&&n.get("ifAvailableShowOutlineOnLoad")&&(e.sidebarOpen||document.getElementById("sidebarToggle").click(),e.switchSidebarView("outline"))})});
a.getMetadata().then(function(b){var c=b.info,b=b.metadata;e.documentInfo=c;e.metadata=b;console.log("PDF "+a.fingerprint+" ["+c.PDFFormatVersion+" "+(c.Producer||"-")+" / "+(c.Creator||"-")+"]"+(PDFJS.version?" (PDF.js: "+PDFJS.version+")":""));var d;b&&b.has("dc:title")&&(d=b.get("dc:title"));!d&&c&&c.Title&&(d=c.Title);d&&e.setTitle(d+" - "+document.title);c.IsAcroFormPresent&&(console.warn("Warning: AcroForm/XFA is not supported"),PDFView.fallback(PDFJS.UNSUPPORTED_FEATURES.forms))})},setInitialView:function(a,
b){this.currentScale=0;this.currentScaleValue=null;document.getElementById("pageNumber").value=currentPageNumber=1;this.currentPosition=null;PDFHistory.initialDestination?(this.navigateTo(PDFHistory.initialDestination),PDFHistory.initialDestination=null):this.initialBookmark?(this.setHash(this.initialBookmark),PDFHistory.push({hash:this.initialBookmark},!!this.initialBookmark),this.initialBookmark=null):a?this.setHash(a):b&&(this.setScale(b,!0),this.page=1);PDFView.currentScale===UNKNOWN_SCALE&&this.setScale(DEFAULT_SCALE,
!0)},renderHighestPriority:function(){PDFView.idleTimeout&&(clearTimeout(PDFView.idleTimeout),PDFView.idleTimeout=null);var a=this.getHighestPriority(this.getVisiblePages(),this.pages,this.pageViewScroll.down);if(a)this.renderView(a,"page");else{if(this.sidebarOpen&&(a=this.getHighestPriority(this.getVisibleThumbs(),this.thumbnails,this.thumbnailViewScroll.down))){this.renderView(a,"thumbnail");return}PDFView.idleTimeout=setTimeout(function(){PDFView.cleanup()},CLEANUP_TIMEOUT)}},cleanup:function(){for(var a=
0,b=this.pages.length;a<b;a++)this.pages[a]&&this.pages[a].renderingState!==RenderingStates.FINISHED&&this.pages[a].reset();this.pdfDocument.cleanup()},getHighestPriority:function(a,b,c){var e=a.views,d=e.length;if(0===d)return!1;for(var g=0;g<d;++g){var h=e[g].view;if(!this.isViewFinished(h))return h}a=c?a.last.id:a.first.id-2;return b[a]&&!this.isViewFinished(b[a])?b[a]:!1},isViewFinished:function(a){return a.renderingState===RenderingStates.FINISHED},renderView:function(a,b){switch(a.renderingState){case RenderingStates.FINISHED:return!1;
case RenderingStates.PAUSED:PDFView.highestPriorityPage=b+a.id;a.resume();break;case RenderingStates.RUNNING:PDFView.highestPriorityPage=b+a.id;break;case RenderingStates.INITIAL:PDFView.highestPriorityPage=b+a.id,a.draw(this.renderHighestPriority.bind(this))}return!0},setHash:function(a){if(a)if(0<=a.indexOf("="))if(a=PDFView.parseQueryString(a),"nameddest"in a)PDFHistory.updateNextHashParam(a.nameddest),PDFView.navigateTo(a.nameddest);else{var b,c;"page"in a&&(b=a.page|0||1);if("zoom"in a){c=a.zoom.split(",");
var e=c[0],d=parseFloat(e);d&&(e=d/100);c=[null,{name:"XYZ"},1<c.length?c[1]|0:null,2<c.length?c[2]|0:null,e]}c?this.pages[(b||this.page)-1].scrollIntoView(c):b&&(this.page=b);"pagemode"in a&&(b=document.getElementById("sidebarToggle"),"thumbs"===a.pagemode||"bookmarks"===a.pagemode?(this.sidebarOpen||b.click(),this.switchSidebarView("thumbs"===a.pagemode?"thumbs":"outline")):"none"===a.pagemode&&this.sidebarOpen&&b.click())}else/^\d+$/.test(a)?this.page=a:(PDFHistory.updateNextHashParam(unescape(a)),
PDFView.navigateTo(unescape(a)))},switchSidebarView:function(a){var b=document.getElementById("thumbnailView"),c=document.getElementById("outlineView"),e=document.getElementById("viewThumbnail"),d=document.getElementById("viewOutline");switch(a){case "thumbs":a=b.classList.contains("hidden");e.classList.add("toggled");d.classList.remove("toggled");b.classList.remove("hidden");c.classList.add("hidden");PDFView.renderHighestPriority();a&&scrollIntoView(document.getElementById("thumbnailContainer"+this.page));
break;case "outline":e.classList.remove("toggled"),d.classList.add("toggled"),b.classList.add("hidden"),c.classList.remove("hidden"),d.getAttribute("disabled")}},getVisiblePages:function(){if(PresentationMode.active){var a=[],b=this.pages[this.page-1];a.push({id:b.id,view:b});return{first:b,last:b,views:a}}return this.getVisibleElements(this.container,this.pages,!0)},getVisibleThumbs:function(){return this.getVisibleElements(this.thumbnailContainer,this.thumbnails)},getVisibleElements:function(a,
b,c){for(var e=a.scrollTop,d=e+a.clientHeight,g=a.scrollLeft,h=g+a.clientWidth,a=[],f,j,o,l,n,q=0,r=b.length;q<r;++q)if(f=b[q],j=f.el.offsetTop+f.el.clientTop,o=f.el.clientHeight,!(j+o<e)){if(j>d)break;n=f.el.offsetLeft+f.el.clientLeft;l=f.el.clientWidth;n+l<g||n>h||(l=Math.max(0,e-j)+Math.max(0,j+o-d),o=100*(o-l)/o|0,a.push({id:f.id,x:n,y:j,view:f,percent:o}))}b=a[0];e=a[a.length-1];c&&a.sort(function(a,b){var c=a.percent-b.percent;return 0.001<Math.abs(c)?-c:a.id-b.id});return{first:b,last:e,views:a}},
parseQueryString:function(a){for(var a=a.split("&"),b={},c=0;c<a.length;++c){var e=a[c].split("="),d=1<e.length?e[1]:null;b[decodeURIComponent(e[0])]=decodeURIComponent(d)}return b},beforePrint:function(){if(this.supportsPrinting){var a=!1;if(this.pages.length)for(var b=0,c=this.pages.length;b<c;++b){if(!this.pages[b].pdfPage){a=!0;break}}else a=!0;if(a)a=mozL10n.get("printing_not_ready",null,"Warning: The PDF is not fully loaded for printing."),window.alert(a);else{document.querySelector("body").setAttribute("data-mozPrintCallback",
!0);b=0;for(c=this.pages.length;b<c;++b)this.pages[b].beforePrint()}}else this.error(mozL10n.get("printing_not_supported",null,"Warning: Printing is not fully supported by this browser."))},afterPrint:function(){for(var a=document.getElementById("printContainer");a.hasChildNodes();)a.removeChild(a.lastChild)},rotatePages:function(a){var b=this.pages[this.page-1];this.pageRotation=(this.pageRotation+360+a)%360;for(var a=0,c=this.pages.length;a<c;a++){var e=this.pages[a];e.update(e.scale,this.pageRotation)}a=
0;for(c=this.thumbnails.length;a<c;a++)this.thumbnails[a].update(this.pageRotation);this.setScale(this.currentScaleValue,!0,!0);this.renderHighestPriority();b&&b.scrollIntoView()},mouseScroll:function(a){var b=(new Date).getTime(),c=this.mouseScrollTimeStamp;b>c&&50>b-c||((0<this.mouseScrollDelta&&0>a||0>this.mouseScrollDelta&&0<a)&&this.clearMouseScrollState(),this.mouseScrollDelta+=a,120<=Math.abs(this.mouseScrollDelta)&&(a=0<this.mouseScrollDelta?-1:1,this.clearMouseScrollState(),c=this.page,1==
c&&-1==a||c==this.pages.length&&1==a||(this.page+=a,this.mouseScrollTimeStamp=b)))},clearMouseScrollState:function(){this.mouseScrollDelta=this.mouseScrollTimeStamp=0}},PageView=function(a,b,c,e,d){function g(a,b,c){function e(a,b){a.href=PDFView.getDestinationHash(b);a.onclick=function(){b&&PDFView.navigateTo(b);return!1};b&&(a.className="internalLink")}function d(a,b){a.href=PDFView.getAnchorUrl("");a.onclick=function(){switch(b){case "GoToPage":document.getElementById("pageNumber").focus();break;
case "GoBack":PDFHistory.back();break;case "GoForward":PDFHistory.forward();break;case "Find":PDFView.supportsIntegratedFind||PDFFindBar.toggle();break;case "NextPage":PDFView.page++;break;case "PrevPage":PDFView.page--;break;case "LastPage":PDFView.page=PDFView.pages.length;break;case "FirstPage":PDFView.page=1}return!1};a.className="internalLink"}b.getAnnotations().then(function(h){f.annotationLayer&&(a.removeChild(f.annotationLayer),f.annotationLayer=null);c=c.clone({dontFlip:!0});for(var g=0;g<
h.length;g++){var i=h[g];if((i=PDFJS.Annotation.fromData(i))&&i.hasHtml()){var p=i.getHtmlElement(b.commonObjs);mozL10n.translate(p);var i=i.getData(),k=i.rect,s=b.view,k=PDFJS.Util.normalizeRect([k[0],s[3]-k[1]+s[1],k[2],s[3]-k[3]+s[1]]);p.style.left=k[0]+"px";p.style.top=k[1]+"px";p.style.position="absolute";s="matrix("+c.transform.join(",")+")";CustomStyle.setProp("transform",p,s);CustomStyle.setProp("transformOrigin",p,-k[0]+"px "+-k[1]+"px");"Link"===i.subtype&&!i.url&&(k=p.getElementsByTagName("a")[0])&&
(i.action?d(k,i.action):e(k,"dest"in i?i.dest:null));f.annotationLayer||(i=document.createElement("div"),i.className="annotationLayer",a.appendChild(i),f.annotationLayer=i);f.annotationLayer.appendChild(p)}}})}this.id=b;this.rotation=0;this.scale=c||1;this.viewport=d;this.pdfPageRotate=d.rotation;this.renderingState=RenderingStates.INITIAL;this.annotationLayer=this.zoomLayer=this.textLayer=this.resume=null;b=document.createElement("a");b.name=""+this.id;var h=this.el=document.createElement("div");
h.id="pageContainer"+this.id;h.className="page";h.style.width=Math.floor(this.viewport.width)+"px";h.style.height=Math.floor(this.viewport.height)+"px";a.appendChild(b);a.appendChild(h);this.setPdfPage=function(a){this.pdfPage=a;this.pdfPageRotate=a.rotate;this.viewport=a.getViewport(this.scale*CSS_UNITS,(this.rotation+this.pdfPageRotate)%360);this.stats=a.stats;this.reset()};this.destroy=function(){this.zoomLayer=null;this.reset();this.pdfPage&&this.pdfPage.destroy()};this.reset=function(){this.renderTask&&
this.renderTask.cancel();this.resume=null;this.renderingState=RenderingStates.INITIAL;h.style.width=Math.floor(this.viewport.width)+"px";h.style.height=Math.floor(this.viewport.height)+"px";for(var a=h.childNodes,b=h.childNodes.length-1;0<=b;b--){var c=a[b];this.zoomLayer&&this.zoomLayer===c||h.removeChild(c)}h.removeAttribute("data-loaded");this.annotationLayer=null;delete this.canvas;this.loadingIconDiv=document.createElement("div");this.loadingIconDiv.className="loadingIcon";h.appendChild(this.loadingIconDiv)};
this.update=function(a,b){this.scale=a||this.scale;"undefined"!==typeof b&&(this.rotation=b);this.viewport=this.viewport.clone({scale:this.scale*CSS_UNITS,rotation:(this.rotation+this.pdfPageRotate)%360});USE_ONLY_CSS_ZOOM&&this.canvas?this.cssTransform(this.canvas):(this.canvas&&!this.zoomLayer&&(this.zoomLayer=this.canvas.parentNode,this.zoomLayer.style.position="absolute"),this.zoomLayer&&this.cssTransform(this.zoomLayer.firstChild),this.reset())};this.cssTransform=function(a){var b=this.viewport.width,
c=this.viewport.height;a.style.width=a.parentNode.style.width=h.style.width=Math.floor(b)+"px";a.style.height=a.parentNode.style.height=h.style.height=Math.floor(c)+"px";var e=this.viewport.rotation-a._viewport.rotation,d=Math.abs(e),f=1,m=1;if(90===d||270===d)f=c/b,m=b/c;CustomStyle.setProp("transform",a,"rotate("+e+"deg) scale("+f+","+m+")");if(this.textLayer){c=Math.abs(this.viewport.rotation-this.textLayer.viewport.rotation);e=b/a.width;if(90===c||270===c)e=b/a.height;var a=this.textLayer.textLayerDiv,
i,p;switch(c){case 0:i=p=0;break;case 90:i=0;p="-"+a.style.height;break;case 180:i="-"+a.style.width;p="-"+a.style.height;break;case 270:i="-"+a.style.width;p=0;break;default:console.error("Bad rotation value.")}CustomStyle.setProp("transform",a,"rotate("+c+"deg) scale("+e+", "+e+") translate("+i+", "+p+")");CustomStyle.setProp("transformOrigin",a,"0% 0%")}USE_ONLY_CSS_ZOOM&&this.annotationLayer&&g(h,this.pdfPage,this.viewport)};Object.defineProperty(this,"width",{get:function(){return this.viewport.width},
enumerable:!0});Object.defineProperty(this,"height",{get:function(){return this.viewport.height},enumerable:!0});var f=this;this.getPagePoint=function(a,b){return this.viewport.convertToPdfPoint(a,b)};this.scrollIntoView=function(a){if(PresentationMode.active){if(PDFView.page!==this.id){PDFView.page=this.id;return}a=null;PDFView.setScale(PDFView.currentScaleValue,!0,!0)}if(a){var b=0,c=0,e=0,d=0,g,f;f=!!(this.rotation%180);g=(f?this.height:this.width)/this.scale/CSS_UNITS;f=(f?this.width:this.height)/
this.scale/CSS_UNITS;var i=0;switch(a[1].name){case "XYZ":b=a[2];c=a[3];i=a[4];b=null!==b?b:0;c=null!==c?c:f;break;case "Fit":case "FitB":i="page-fit";break;case "FitH":case "FitBH":c=a[2];i="page-width";break;case "FitV":case "FitBV":b=a[2];e=g;d=f;i="page-height";break;case "FitR":b=a[2];c=a[3];e=a[4]-b;d=a[5]-c;g=(PDFView.container.clientWidth-SCROLLBAR_PADDING)/e/CSS_UNITS;f=(PDFView.container.clientHeight-SCROLLBAR_PADDING)/d/CSS_UNITS;i=Math.min(Math.abs(g),Math.abs(f));break;default:return}i&&
i!==PDFView.currentScale?PDFView.setScale(i,!0,!0):PDFView.currentScale===UNKNOWN_SCALE&&PDFView.setScale(DEFAULT_SCALE,!0,!0);"page-fit"===i&&!a[4]?scrollIntoView(h):(b=[this.viewport.convertToViewportPoint(b,c),this.viewport.convertToViewportPoint(b+e,c+d)],a=Math.min(b[0][0],b[1][0]),b=Math.min(b[0][1],b[1][1]),scrollIntoView(h,{left:a,top:b}))}else scrollIntoView(h)};this.getTextContent=function(){return PDFView.getPage(this.id).then(function(a){return a.getTextContent()})};this.draw=function(a){function b(e){s===
k.renderTask&&(k.renderTask=null);if("cancelled"!==e){k.renderingState=RenderingStates.FINISHED;k.loadingIconDiv&&(h.removeChild(k.loadingIconDiv),delete k.loadingIconDiv);k.zoomLayer&&(h.removeChild(k.zoomLayer),k.zoomLayer=null);e&&PDFView.error(mozL10n.get("rendering_error",null,"An error occurred while rendering the page."),e);k.stats=c.stats;k.updateStats();if(k.onAfterDraw)k.onAfterDraw();cache.push(k);e=document.createEvent("CustomEvent");e.initCustomEvent("pagerender",!0,!0,{pageNumber:c.pageNumber});
h.dispatchEvent(e);a()}}var c=this.pdfPage;if(!this.pagePdfPromise)if(c){this.renderingState!==RenderingStates.INITIAL&&console.error("Must be in new state before drawing");this.renderingState=RenderingStates.RUNNING;var e=this.viewport,d=document.createElement("div");d.style.width=h.style.width;d.style.height=h.style.height;d.classList.add("canvasWrapper");var f=document.createElement("canvas");f.id="page"+this.id;d.appendChild(f);h.appendChild(d);this.canvas=f;var d=f.getContext("2d"),m=getOutputScale(d);
if(USE_ONLY_CSS_ZOOM){var i=e.clone({scale:CSS_UNITS});m.sx*=i.width/e.width;m.sy*=i.height/e.height;m.scaled=!0}f.width=Math.floor(e.width)*m.sx|0;f.height=Math.floor(e.height)*m.sy|0;f.style.width=Math.floor(e.width)+"px";f.style.height=Math.floor(e.height)+"px";f._viewport=e;e=null;PDFJS.disableTextLayer||(e=document.createElement("div"),e.className="textLayer",e.style.width=f.width+"px",e.style.height=f.height+"px",h.appendChild(e));var p=this.textLayer=e?new TextLayerBuilder({textLayerDiv:e,
pageIndex:this.id-1,lastScrollSource:PDFView,viewport:this.viewport,isViewerInPresentationMode:PresentationMode.active}):null;d._scaleX=m.sx;d._scaleY=m.sy;m.scaled&&d.scale(m.sx,m.sy);m.scaled&&e&&(CustomStyle.setProp("transform",e,"scale("+1/m.sx+", "+1/m.sy+")"),CustomStyle.setProp("transformOrigin",e,"0% 0%"),e.dataset._scaleX=m.sx,e.dataset._scaleY=m.sy);var k=this,s=this.renderTask=this.pdfPage.render({canvasContext:d,viewport:this.viewport,textLayer:p,continueCallback:function(a){PDFView.highestPriorityPage!==
"page"+k.id?(k.renderingState=RenderingStates.PAUSED,k.resume=function(){k.renderingState=RenderingStates.RUNNING;a()}):a()}});this.renderTask.promise.then(function(){b(null)},function(a){b(a)});p&&this.getTextContent().then(function(a){p.setTextContent(a)});g(h,c,this.viewport);h.setAttribute("data-loaded",!0)}else f=PDFView.getPage(this.id),f.then(function(b){delete this.pagePdfPromise;this.setPdfPage(b);this.draw(a)}.bind(this)),this.pagePdfPromise=f};this.beforePrint=function(){var a=this.pdfPage,
b=a.getViewport(1),c=document.createElement("canvas");c.width=2*Math.floor(b.width);c.height=2*Math.floor(b.height);c.style.width=2*b.width+"pt";c.style.height=2*b.height+"pt";CustomStyle.setProp("transform",c,"scale(0.5, 0.5)");CustomStyle.setProp("transformOrigin",c,"0% 0%");var e=document.getElementById("printContainer"),d=document.createElement("div");d.style.width=b.width+"pt";d.style.height=b.height+"pt";d.appendChild(c);e.appendChild(d);c.mozPrintCallback=function(e){var d=e.context;d.save();
d.fillStyle="rgb(255, 255, 255)";d.fillRect(0,0,c.width,c.height);d.restore();d.scale(2,2);a.render({canvasContext:d,viewport:b,intent:"print"}).promise.then(function(){e.done()},function(a){console.error(a);"abort"in e?e.abort():e.done()})}};this.updateStats=function(){this.stats&&PDFJS.pdfBug&&Stats.enabled&&Stats.add(this.id,this.stats)}},ThumbnailView=function(a,b,c){var e=document.createElement("a");e.href=PDFView.getAnchorUrl("#page="+b);e.title=mozL10n.get("thumb_page_title",{page:b},"Page {{page}}");
e.onclick=function(){PDFView.page=b;return!1};this.pdfPage=void 0;this.viewport=c;this.pdfPageRotate=c.rotation;this.rotation=0;this.pageWidth=this.viewport.width;this.pageHeight=this.viewport.height;this.pageRatio=this.pageWidth/this.pageHeight;this.id=b;this.canvasWidth=98;this.canvasHeight=this.canvasWidth/this.pageWidth*this.pageHeight;this.scale=this.canvasWidth/this.pageWidth;var d=this.el=document.createElement("div");d.id="thumbnailContainer"+b;d.className="thumbnail";1===b&&d.classList.add("selected");
var g=document.createElement("div");g.className="thumbnailSelectionRing";g.style.width=this.canvasWidth+"px";g.style.height=this.canvasHeight+"px";d.appendChild(g);e.appendChild(d);a.appendChild(e);this.hasImage=!1;this.renderingState=RenderingStates.INITIAL;this.setPdfPage=function(a){this.pdfPage=a;this.pdfPageRotate=a.rotate;this.viewport=a.getViewport(1,(this.rotation+this.pdfPageRotate)%360);this.update()};this.update=function(a){void 0!==a&&(this.rotation=a);this.viewport=this.viewport.clone({scale:1,
rotation:(this.rotation+this.pdfPageRotate)%360});this.pageWidth=this.viewport.width;this.pageHeight=this.viewport.height;this.pageRatio=this.pageWidth/this.pageHeight;this.canvasHeight=this.canvasWidth/this.pageWidth*this.pageHeight;this.scale=this.canvasWidth/this.pageWidth;d.removeAttribute("data-loaded");g.textContent="";g.style.width=this.canvasWidth+"px";g.style.height=this.canvasHeight+"px";this.hasImage=!1;this.renderingState=RenderingStates.INITIAL;this.resume=null};this.getPageDrawContext=
function(){var a=document.createElement("canvas");a.id="thumbnail"+b;a.width=this.canvasWidth;a.height=this.canvasHeight;a.className="thumbnailImage";a.setAttribute("aria-label",mozL10n.get("thumb_page_canvas",{page:b},"Thumbnail of Page {{page}}"));d.setAttribute("data-loaded",!0);g.appendChild(a);a=a.getContext("2d");a.save();a.fillStyle="rgb(255, 255, 255)";a.fillRect(0,0,this.canvasWidth,this.canvasHeight);a.restore();return a};this.drawingRequired=function(){return!this.hasImage};this.draw=function(a){if(this.pdfPage)if(this.renderingState!==
RenderingStates.INITIAL&&console.error("Must be in new state before drawing"),this.renderingState=RenderingStates.RUNNING,this.hasImage)a();else{var b=this,c=this.getPageDrawContext(),e=this.viewport.clone({scale:this.scale});this.pdfPage.render({canvasContext:c,viewport:e,continueCallback:function(a){PDFView.highestPriorityPage!=="thumbnail"+b.id?(b.renderingState=RenderingStates.PAUSED,b.resume=function(){b.renderingState=RenderingStates.RUNNING;a()}):a()}}).promise.then(function(){b.renderingState=
RenderingStates.FINISHED;a()},function(){b.renderingState=RenderingStates.FINISHED;a()});this.hasImage=!0}else PDFView.getPage(this.id).then(function(b){this.setPdfPage(b);this.draw(a)}.bind(this))};this.setImage=function(a){if(this.pdfPage){if(!this.hasImage&&a){this.renderingState=RenderingStates.FINISHED;var b=this.getPageDrawContext();b.drawImage(a,0,0,a.width,a.height,0,0,b.canvas.width,b.canvas.height);this.hasImage=!0}}else PDFView.getPage(this.id).then(function(b){this.setPdfPage(b);this.setImage(a)}.bind(this))}},
FIND_SCROLL_OFFSET_TOP=-50,FIND_SCROLL_OFFSET_LEFT=-400,TextLayerBuilder=function(a){var b=document.createDocumentFragment();this.textLayerDiv=a.textLayerDiv;this.divContentDone=this.layoutDone=!1;this.pageIdx=a.pageIndex;this.matches=[];this.lastScrollSource=a.lastScrollSource;this.viewport=a.viewport;this.isViewerInPresentationMode=a.isViewerInPresentationMode;"undefined"===typeof PDFFindController&&(window.PDFFindController=null);"undefined"===typeof this.lastScrollSource&&(this.lastScrollSource=
null);this.beginLayout=function(){this.textDivs=[];this.renderingDone=!1};this.endLayout=function(){this.layoutDone=!0;this.insertDivContent()};this.renderLayer=function(){var a=this.textDivs,e=document.createElement("canvas").getContext("2d");if(!(1E5<a.length)){for(var d=0,g=a.length;d<g;d++){var h=a[d];if(!("isWhitespace"in h.dataset)){e.font=h.style.fontSize+" "+h.style.fontFamily;var f=e.measureText(h.textContent).width;0<f&&(b.appendChild(h),f="scale("+h.dataset.canvasWidth/f+", 1)",f="rotate("+
h.dataset.angle+"deg) "+f,CustomStyle.setProp("transform",h,f),CustomStyle.setProp("transformOrigin",h,"0% 0%"))}}this.textLayerDiv.appendChild(b);this.renderingDone=!0;this.updateMatches()}};this.setupRenderLayoutTimer=function(){var a=this,b=null===this.lastScrollSource?0:this.lastScrollSource.lastScroll;200<Date.now()-b?this.renderLayer():(this.renderTimer&&clearTimeout(this.renderTimer),this.renderTimer=setTimeout(function(){a.setupRenderLayoutTimer()},200))};this.appendText=function(a){var b=
document.createElement("div"),d=a.fontSize*Math.abs(a.vScale);b.dataset.canvasWidth=a.canvasWidth*Math.abs(a.hScale);b.dataset.fontName=a.fontName;b.dataset.angle=a.angle*(180/Math.PI);b.style.fontSize=d+"px";b.style.fontFamily=a.fontFamily;d=a.ascent?a.ascent*d:a.descent?(1+a.descent)*d:d;b.style.left=a.x+d*Math.sin(a.angle)+"px";b.style.top=a.y-d*Math.cos(a.angle)+"px";this.textDivs.push(b)};this.insertDivContent=function(){if(this.layoutDone&&!this.divContentDone&&this.textContent){this.divContentDone=
!0;for(var a=this.textDivs,b=this.textContent,d=0;d<b.length;d++){var g=b[d],h=a[d];/\S/.test(g.str)?(h.textContent=g.str,h.dir=g.dir):h.dataset.isWhitespace=!0}this.setupRenderLayoutTimer()}};this.setTextContent=function(a){this.textContent=a;this.insertDivContent()};this.convertMatches=function(a){for(var b=0,d=0,g=this.textContent,h=g.length-1,f=null===PDFFindController?0:PDFFindController.state.query.length,j=[],o=0;o<a.length;o++){for(var l=a[o];b!==h&&l>=d+g[b].str.length;)d+=g[b].str.length,
b++;b==g.length&&console.error("Could not find matching mapping");for(var n={begin:{divIdx:b,offset:l-d}},l=l+f;b!==h&&l>d+g[b].str.length;)d+=g[b].str.length,b++;n.end={divIdx:b,offset:l-d};j.push(n)}return j};this.renderMatches=function(a){function b(a,c){var d=a.divIdx,e=h[d];e.textContent="";var f=g[d].str.substring(0,a.offset),f=document.createTextNode(f);if(c){var d=j&&d===o,i=document.createElement("span");i.className=c+(d?" selected":"");i.appendChild(f);e.appendChild(i)}else e.appendChild(f)}
function d(a,b,c){var d=a.divIdx,e=h[d],a=g[d].str.substring(a.offset,b.offset),a=document.createTextNode(a);c?(b=document.createElement("span"),b.className=c,b.appendChild(a),e.appendChild(b)):e.appendChild(a)}if(0!==a.length){var g=this.textContent,h=this.textDivs,f=null,j=null===PDFFindController?!1:this.pageIdx===PDFFindController.selected.pageIdx,o=null===PDFFindController?-1:PDFFindController.selected.matchIdx,l={divIdx:-1,offset:void 0},n=o,q=n+1;if(null===PDFFindController?0:PDFFindController.state.highlightAll)n=
0,q=a.length;else if(!j)return;for(;n<q;n++){var r=a[n],m=r.begin,r=r.end,i=j&&n===o,p=i?" selected":"";i&&!this.isViewerInPresentationMode&&scrollIntoView(h[m.divIdx],{top:FIND_SCROLL_OFFSET_TOP,left:FIND_SCROLL_OFFSET_LEFT});!f||m.divIdx!==f.divIdx?(null!==f&&d(f,l),b(m)):d(f,m);if(m.divIdx===r.divIdx)d(m,r,"highlight"+p);else{d(m,l,"highlight begin"+p);for(f=m.divIdx+1;f<r.divIdx;f++)h[f].className="highlight middle"+p;b(r,"highlight end"+p)}f=r}f&&d(f,l)}};this.updateMatches=function(){if(this.renderingDone){for(var a=
this.matches,b=this.textDivs,d=this.textContent,g=-1,h=0;h<a.length;h++){for(var f=a[h],g=Math.max(g,f.begin.divIdx);g<=f.end.divIdx;g++){var j=b[g];j.textContent=d[g].str;j.className=""}g=f.end.divIdx+1}null!==PDFFindController&&PDFFindController.active&&(this.matches=this.convertMatches(null===PDFFindController?[]:PDFFindController.pageMatches[this.pageIdx]||[]),this.renderMatches(this.matches))}}},DocumentOutlineView=function(a){function b(a,b){a.href=PDFView.getDestinationHash(b.dest);a.onclick=
function(){PDFView.navigateTo(b.dest);return!1}}var c=document.getElementById("outlineView");for(document.getElementById("viewOutline");c.firstChild;)c.removeChild(c.firstChild);if(a)for(a=[{parent:c,items:a}];0<a.length;){var c=a.shift(),e,d=c.items.length;for(e=0;e<d;e++){var g=c.items[e],h=document.createElement("div");h.className="outlineItem";var f=document.createElement("a");b(f,g);f.textContent=g.title;h.appendChild(f);0<g.items.length&&(f=document.createElement("div"),f.className="outlineItems",
h.appendChild(f),a.push({parent:f,items:g.items}));c.parent.appendChild(h)}}else c.classList.contains("hidden")||PDFView.switchSidebarView("thumbs")};
function webViewerLoad(){PDFView.initialize();var a=PDFView.parseQueryString(document.location.search.substring(1)),a="file"in a?a.file:DEFAULT_URL,b=document.createElement("input");b.id="fileInput";b.className="fileInput";b.setAttribute("type","file");b.oncontextmenu=noContextMenuHandler;document.body.appendChild(b);!window.File||!window.FileReader||!window.FileList||!window.Blob?(document.getElementById("openFile").setAttribute("hidden","true"),document.getElementById("secondaryOpenFile").setAttribute("hidden",
"true")):document.getElementById("fileInput").value=null;b=document.location.hash.substring(1);b=PDFView.parseQueryString(b);"disableWorker"in b&&(PDFJS.disableWorker="true"===b.disableWorker);"disableRange"in b&&(PDFJS.disableRange="true"===b.disableRange);"disableAutoFetch"in b&&(PDFJS.disableAutoFetch="true"===b.disableAutoFetch);"disableFontFace"in b&&(PDFJS.disableFontFace="true"===b.disableFontFace);"disableHistory"in b&&(PDFJS.disableHistory="true"===b.disableHistory);"useOnlyCssZoom"in b&&
(USE_ONLY_CSS_ZOOM="true"===b.useOnlyCssZoom);"verbosity"in b&&(PDFJS.verbosity=b.verbosity|0);"ignoreCurrentPositionOnZoom"in b&&(IGNORE_CURRENT_POSITION_ON_ZOOM="true"===b.ignoreCurrentPositionOnZoom);var c=PDFJS.locale||navigator.language;"locale"in b&&(c=b.locale);mozL10n.setLanguage(c);if("textLayer"in b)switch(b.textLayer){case "off":PDFJS.disableTextLayer=!0;break;case "visible":case "shadow":case "hover":document.getElementById("viewer").classList.add("textLayer-"+b.textLayer)}"pdfBug"in b&&
(PDFJS.pdfBug=!0,b=b.pdfBug.split(","),PDFBug.enable(b),PDFBug.init());PDFView.supportsPrinting||(document.getElementById("print").classList.add("hidden"),document.getElementById("secondaryPrint").classList.add("hidden"));PDFView.supportsFullscreen||(document.getElementById("presentationMode").classList.add("hidden"),document.getElementById("secondaryPresentationMode").classList.add("hidden"));PDFView.supportsIntegratedFind&&document.getElementById("viewFind").classList.add("hidden");PDFJS.UnsupportedManager.listen(PDFView.fallback.bind(PDFView));
document.getElementById("scaleSelect").oncontextmenu=noContextMenuHandler;var e=document.getElementById("mainContainer"),d=document.getElementById("outerContainer");e.addEventListener("transitionend",function(a){a.target==e&&(a=document.createEvent("UIEvents"),a.initUIEvent("resize",!1,!1,window,0),window.dispatchEvent(a),d.classList.remove("sidebarMoving"))},!0);document.getElementById("sidebarToggle").addEventListener("click",function(){this.classList.toggle("toggled");d.classList.add("sidebarMoving");
d.classList.toggle("sidebarOpen");PDFView.sidebarOpen=d.classList.contains("sidebarOpen");PDFView.renderHighestPriority()});document.getElementById("viewThumbnail").addEventListener("click",function(){PDFView.switchSidebarView("thumbs")});document.getElementById("viewOutline").addEventListener("click",function(){PDFView.switchSidebarView("outline")});document.getElementById("previous").addEventListener("click",function(){PDFView.page--});document.getElementById("next").addEventListener("click",function(){PDFView.page++});
document.getElementById("zoomIn").addEventListener("click",function(){PDFView.zoomIn()});document.getElementById("zoomOut").addEventListener("click",function(){PDFView.zoomOut()});document.getElementById("pageNumber").addEventListener("click",function(){this.select()});document.getElementById("pageNumber").addEventListener("change",function(){PDFView.page=this.value|0;this.value!==(this.value|0).toString()&&(this.value=PDFView.page)});document.getElementById("scaleSelect").addEventListener("change",
function(){PDFView.setScale(this.value)});document.getElementById("presentationMode").addEventListener("click",SecondaryToolbar.presentationModeClick.bind(SecondaryToolbar));document.getElementById("openFile").addEventListener("click",SecondaryToolbar.openFileClick.bind(SecondaryToolbar));document.getElementById("print").addEventListener("click",SecondaryToolbar.printClick.bind(SecondaryToolbar));document.getElementById("download").addEventListener("click",SecondaryToolbar.downloadClick.bind(SecondaryToolbar));
a&&PDFView.open(a,0)}document.addEventListener("DOMContentLoaded",webViewerLoad,!0);
function updateViewarea(){if(PDFView.initialized){var a=PDFView.getVisiblePages(),b=a.views;if(0!==b.length){PDFView.renderHighestPriority();for(var c=PDFView.page,a=a.first,e=0,d=b.length,g=!1;e<d;++e){var h=b[e];if(100>h.percent)break;if(h.id===PDFView.page){g=!0;break}}g||(c=b[0].id);PresentationMode.active||(updateViewarea.inProgress=!0,PDFView.page=c,updateViewarea.inProgress=!1);var b=PDFView.currentScale,c=PDFView.currentScaleValue,f=parseFloat(c)===b?Math.round(1E4*b)/100:c,j=a.id,b="#page="+
j+("&zoom="+f),c=PDFView.container,a=PDFView.pages[j-1].getPagePoint(c.scrollLeft-a.x,c.scrollTop-a.y),o=Math.round(a[0]),l=Math.round(a[1]),b=b+(","+o+","+l);PDFView.currentPosition=PresentationMode.active||PresentationMode.switchInProgress?null:{page:j,left:o,top:l};var n=PDFView.store;n.initializedPromise.then(function(){n.set("exists",!0);n.set("page",j);n.set("zoom",f);n.set("scrollLeft",o);n.set("scrollTop",l)});a=PDFView.getAnchorUrl(b);document.getElementById("viewBookmark").href=a;document.getElementById("secondaryViewBookmark").href=
a;PDFHistory.updateCurrentBookmark(b,j)}}}window.addEventListener("resize",function(){PDFView.initialized&&(document.getElementById("pageWidthOption").selected||document.getElementById("pageFitOption").selected||document.getElementById("pageAutoOption").selected)&&PDFView.setScale(document.getElementById("scaleSelect").value);updateViewarea();SecondaryToolbar.setMaxHeight(PDFView.container)});window.addEventListener("hashchange",function(){PDFHistory.isHashChangeUnlocked&&PDFView.setHash(document.location.hash.substring(1))});
window.addEventListener("change",function(a){if((a=a.target.files)&&0!==a.length){a=a[0];if(!PDFJS.disableCreateObjectURL&&"undefined"!==typeof URL&&URL.createObjectURL)PDFView.open(URL.createObjectURL(a),0);else{var b=new FileReader;b.onload=function(a){a=new Uint8Array(a.target.result);PDFView.open(a,0)};b.readAsArrayBuffer(a)}PDFView.setTitleUsingUrl(a.name);document.getElementById("viewBookmark").setAttribute("hidden","true");document.getElementById("secondaryViewBookmark").setAttribute("hidden",
"true");document.getElementById("download").setAttribute("hidden","true");document.getElementById("secondaryDownload").setAttribute("hidden","true")}},!0);function selectScaleOption(a){for(var b=document.getElementById("scaleSelect").options,c=!1,e=0;e<b.length;e++){var d=b[e];d.value!=a?d.selected=!1:c=d.selected=!0}return c}
window.addEventListener("localized",function(){document.getElementsByTagName("html")[0].dir=mozL10n.getDirection();PDFView.animationStartedPromise.then(function(){var a=document.getElementById("scaleSelectContainer");if(0<a.clientWidth){var b=document.getElementById("scaleSelect");b.setAttribute("style","min-width: inherit;");var c=b.clientWidth+SCALE_SELECT_CONTAINER_PADDING;b.setAttribute("style","min-width: "+(c+SCALE_SELECT_PADDING)+"px;");a.setAttribute("style","min-width: "+c+"px; max-width: "+
c+"px;")}SecondaryToolbar.setMaxHeight(PDFView.container)})},!0);
window.addEventListener("scalechange",function(a){document.getElementById("zoomOut").disabled=a.scale===MIN_SCALE;document.getElementById("zoomIn").disabled=a.scale===MAX_SCALE;var b=document.getElementById("customScaleOption");b.selected=!1;if((a.resetAutoSettings||!document.getElementById("pageWidthOption").selected&&!document.getElementById("pageFitOption").selected&&!document.getElementById("pageAutoOption").selected)&&!selectScaleOption(""+a.scale))b.textContent=Math.round(1E4*a.scale)/100+"%",
b.selected=!0;updateViewarea()},!0);
window.addEventListener("pagechange",function(a){a=a.pageNumber;if(PDFView.previousPageNumber!==a){document.getElementById("pageNumber").value=a;var b=document.querySelector(".thumbnail.selected");b&&b.classList.remove("selected");b=document.getElementById("thumbnailContainer"+a);b.classList.add("selected");var c=PDFView.getVisibleThumbs(),e=c.views.length;if(0<e){var d=c.first.id,c=1<e?c.last.id:d;(a<=d||a>=c)&&scrollIntoView(b,{top:THUMBNAIL_SCROLL_MARGIN})}}document.getElementById("previous").disabled=1>=
a;document.getElementById("next").disabled=a>=PDFView.pages.length},!0);function handleMouseWheel(a){var b="DOMMouseScroll"===a.type?-a.detail:a.wheelDelta/40,c=0>b?"zoomOut":"zoomIn";a.ctrlKey?(a.preventDefault(),PDFView[c](Math.abs(b))):PresentationMode.active&&PDFView.mouseScroll(40*b)}window.addEventListener("DOMMouseScroll",handleMouseWheel);window.addEventListener("mousewheel",handleMouseWheel);
window.addEventListener("click",function(a){PresentationMode.active?0===a.button&&a.preventDefault():SecondaryToolbar.opened&&PDFView.container.contains(a.target)&&SecondaryToolbar.close()},!1);
window.addEventListener("keydown",function(a){if(!PasswordPrompt.visible){var b=!1,c=(a.ctrlKey?1:0)|(a.altKey?2:0)|(a.shiftKey?4:0)|(a.metaKey?8:0);if(1===c||8===c||5===c||12===c)switch(a.keyCode){case 70:PDFView.supportsIntegratedFind||(PDFFindBar.open(),b=!0);break;case 71:PDFView.supportsIntegratedFind||(PDFFindBar.dispatchEvent("again",5===c||12===c),b=!0);break;case 61:case 107:case 187:case 171:PDFView.zoomIn();b=!0;break;case 173:case 109:case 189:PDFView.zoomOut();b=!0;break;case 48:case 96:setTimeout(function(){PDFView.setScale(DEFAULT_SCALE,
!0)}),b=!1}if(1===c||8===c)switch(a.keyCode){case 83:PDFView.download(),b=!0}if(3===c||10===c)switch(a.keyCode){case 80:SecondaryToolbar.presentationModeClick();b=!0;break;case 71:document.getElementById("pageNumber").select(),b=!0}if(b)a.preventDefault();else{var e=document.activeElement||document.querySelector(":focus"),d=e&&e.tagName.toUpperCase();if(!(("INPUT"===d||"TEXTAREA"===d||"SELECT"===d)&&27!==a.keyCode)){if(0===c)switch(a.keyCode){case 38:case 33:case 8:if(!PresentationMode.active&&"page-fit"!==
PDFView.currentScaleValue)break;case 37:if(PDFView.isHorizontalScrollbarEnabled)break;case 75:case 80:PDFView.page--;b=!0;break;case 27:SecondaryToolbar.opened&&(SecondaryToolbar.close(),b=!0);!PDFView.supportsIntegratedFind&&PDFFindBar.opened&&(PDFFindBar.close(),b=!0);break;case 40:case 34:case 32:if(!PresentationMode.active&&"page-fit"!==PDFView.currentScaleValue)break;case 39:if(PDFView.isHorizontalScrollbarEnabled)break;case 74:case 78:PDFView.page++;b=!0;break;case 36:PresentationMode.active&&
(PDFView.page=1,b=!0);break;case 35:PresentationMode.active&&(PDFView.page=PDFView.pdfDocument.numPages,b=!0);break;case 72:PresentationMode.active||HandTool.toggle();break;case 82:PDFView.rotatePages(90)}if(4===c)switch(a.keyCode){case 32:if(!PresentationMode.active&&"page-fit"!==PDFView.currentScaleValue)break;PDFView.page--;b=!0;break;case 82:PDFView.rotatePages(-90)}!b&&!PresentationMode.active&&(33<=a.keyCode&&40>=a.keyCode&&!PDFView.container.contains(e)&&PDFView.container.focus(),32===a.keyCode&&
"BUTTON"!==d&&(PDFView.container.contains(e)||PDFView.container.focus()));if(2===c)switch(a.keyCode){case 37:PresentationMode.active&&(PDFHistory.back(),b=!0);break;case 39:PresentationMode.active&&(PDFHistory.forward(),b=!0)}b&&(a.preventDefault(),PDFView.clearMouseScrollState())}}}});window.addEventListener("beforeprint",function(){PDFView.beforePrint()});window.addEventListener("afterprint",function(){PDFView.afterPrint()});
(function(){var a=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){a()};PDFView.animationStartedPromise=new Promise(function(b){a(function(){b()})})})();
