#
# Manipulate.R
#
# Copyright (C) 2009-11 by RStudio, Inc.
#
# This program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

.rs.addFunction( "manipulator.createControl", function(type, value, min, max)
{
  # TODO: validate data types of value, min, and max

   # validate inputs
  if ( ! (type %in% c(0)) )
    stop(paste("invalid control type:", type))
  else if (value < min)
    stop(paste(type, "value", value, "is less than the specified minimum"))
  else if (value > max)
    stop(paste(type, "value", value, "is greater than the specified maximum"))
  else if (min > max)
    stop(paste(type, "maximum is greater than minimum"))
  
  # create control and return it
  control <- list(type = type,
                  value = value,
                  min = min,
                  max = max)
  class(control) <- "manipulator.control"
  return (control)
})

.rs.addGlobalFunction( "slider", function(value, min, max)
{
   .rs.manipulator.createControl(0, value, min, max)
})

.rs.addFunction( "manipulator.execute", function(manipulator)
{
  eval(manipulator$code, envir=manipulator, enclos=globalenv())
})

.rs.addFunction( "manipulator.save", function(manipulator, filename)
{
   save(manipulator, file=filename)
})

.rs.addFunction( "manipulator.load", function(filename)
{
   load(filename)
   return (manipulator)
})

.rs.addGlobalFunction( "manipulate", function(code, ...)
{
  # TODO: validate that all controls have variables in the expression

  # TODO: use special naming scheme to eliminate chance of internal vars
  # (e.g. "code") conflicting with user variables

  # create new list container for the manipulator
  manipulator <- list()
  class(manipulator) <- "manipulator"
  
  # save the unevaluated expression as the code
  manipulator$code <- substitute(code) 
  
  # save a human readable version of the code (specify control = NULL
  # to make the display as close to the original text as possible)
  manipulator$codeAsText <- deparse(substitute(code), control = NULL)

  # get the controls and their names, then save them into the env
  controls <- list(...)
  controlNames <- names(controls)
  manipulator$controls <- controls 
 
  # iterate over the names and controls, adding the default values to the env
  c = 1 
  for (control in controls)
  {
    # get the name and bump the control index
    name <- controlNames[c]
    if (name == "")
      stop("all controls passed to manipulate must be named")
    c = c + 1  
    
    # confirm that this is in fact a control
    if (class(control) != "manipulator.control")
      stop(paste("argument", name, "is not a control"))
    
    # assign the value
    manipulator[name] = control$value
  }

  # execute the manipulator -- will execute the code and attach it
  # to the first plot (if any) generated by the execution
  .Call("rs_executeAndAttachManipulator", manipulator)
  
  # return invisibly
  invisible(NULL)
})













