#!/usr/bin/env bash

#
# update-yarn
#
# Copyright (C) 2021 by RStudio, PBC
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e
cd $(dirname "${BASH_SOURCE[0]}")/..
source "../../../dependencies/tools/rstudio-tools.sh"

section Installing/updating components...
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 yarn
