#!/bin/sh
if [ -z "$1" ]
then
  F=version
else
  F=$1
fi

V=`svn info 2>/dev/null | fgrep Revision: | awk  '{ print $2; }'`
if [ $? -gt 0 -o -z "$V" ]
then
  V='?'
fi

TS=`date +%Y%m%d%H%M%S`

echo "0.0.$V.$TS" >$F
exit 0
