/*
 * Copyright 2010 Google Inc.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.gwt.requestfactory.client.impl;

/**
 * <p>
 * <span style="color:red">Experimental API: This class is still under rapid
 * development, and is very likely to be deleted. Use it at your own risk.
 * </span>
 * </p>
 * A class that can map the "TOKEN" generated by a JPA-savvy tool in every
 * Proxy class to its internal "type" representation.
 */
public interface ProxyToTypeMap {
  String getClassToken(Class<?> recordClass);
  <P extends ProxyImpl> ProxySchema<P> getType(Class<P> recordClass);
  ProxySchema<? extends ProxyImpl> getType(String token);
}
