#!/bin/bash

#
# install-dependencies-osx
#
# Copyright (C) 2009-11 by RStudio, Inc.
#
# This program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

cd ../common

# gwt
./install-gwt

# boost
./install-boost

# dictionaries
./install-dictionaries

cd ../osx

# enable PAM
sudo cp /etc/pam.d/ftpd /etc/pam.d/rstudio
