#!/usr/bin/env bash

#
# install-dependencies-osx
#
# Copyright (C) 2021 by RStudio, PBC
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

ARCH="$(arch)"

if [ "${ARCH}" = "arm64" ]; then

   # validate that Homebrew is installed in the expected locations
   if [ ! -f /usr/local/bin/brew ]; then
      echo "Error: Homebrew is not installed for x86_64 (missing /usr/local/bin/brew)"
      exit 1
   fi

   if [ ! -f /opt/homebrew/bin/brew ]; then
      echo "Error: Homebrew is not installed for arm64 (missing /opt/homebrew/bin/brew)"
      exit 1
   fi

   # save the PATH -- note that we munge this so that the correct
   # homebrew executable is found first on the PATH
   OLDPATH="${PATH}"

   # install x86_64 dependencies
   PATH="/usr/local/bin:${OLDPATH}"
   arch -x86_64 ./install-dependencies-osx-arch

   # install arm64 dependencies
   PATH="/opt/homebrew/bin:${OLDPATH}"
   arch -arm64 ./install-dependencies-osx-arch

   # restore path
   PATH="${OLDPATH}"

else

   # assume x86_64
   ./install-dependencies-osx-arch

   # desktop dependencies (qt; currently x86_64 only)
   if [ "$1" != "--exclude-qt-sdk" ]; then
      ./install-qt-macos
   fi

fi

# enable PAM
sudo cp /etc/pam.d/cups /etc/pam.d/rstudio
