#!/usr/bin/env bash

#
# install-dependencies-osx
#
# Copyright (C) 2021 by RStudio, PBC
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e
source ../tools/rstudio-tools.sh

set-default RSTUDIO_TOOLS_ROOT "/opt/rstudio-tools"
set-default BREW_X86           "/usr/local/bin/brew"
set-default BREW_ARM           "/opt/homebrew/bin/brew"

ARCH="$(arch)"

if [ "${ARCH}" = "arm64" ]; then

   # validate that Homebrew is installed in the expected locations
   if [ ! -f "${BREW_X86}" ]; then
      echo "Error: Homebrew is not installed for x86_64 (missing '${BREW_X86}')"
      exit 1
   fi

   if [ ! -f "${BREW_ARM}" ]; then
      echo "Error: Homebrew is not installed for arm64 (missing '${BREW_ARM}')"
      exit 1
   fi

   # save the PATH -- note that we munge this so that the correct
   # homebrew executable is found first on the PATH
   OLDPATH="${PATH}"
   OLDROOT="${RSTUDIO_TOOLS_ROOT}"

   # install x86_64 dependencies
   PATH="$(dirname "${BREW_X86}"):${OLDPATH}"
   RSTUDIO_TOOLS_ROOT="${OLDROOT}/x86_64"
   mkdir -p "${RSTUDIO_TOOLS_ROOT}"
   arch -x86_64 ./install-dependencies-osx-arch

   # install arm64 dependencies
   PATH="$(dirname "${BREW_ARM}"):${OLDPATH}"
   RSTUDIO_TOOLS_ROOT="${OLDROOT}/arm64"
   mkdir -p "${RSTUDIO_TOOLS_ROOT}"
   arch -arm64 ./install-dependencies-osx-arch

   # restore path
   PATH="${OLDPATH}"
   RSTUDIO_TOOLS_ROOT="${OLDROOT}"

else

   # assume x86_64
   ./install-dependencies-osx-arch

   # desktop dependencies (qt; currently x86_64 only)
   if [ "$1" != "--exclude-qt-sdk" ]; then
      ./install-qt-macos
   fi

fi

# enable PAM
sudo cp /etc/pam.d/cups /etc/pam.d/rstudio

