#!/usr/bin/env bash

#
# make-package
#
# Copyright (C) 2021 by RStudio, PBC
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#
set -e
set +H

PKG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BUILD_DIR_X86_64="${PKG_DIR}/build"
BUILD_DIR_ARM64="${PKG_DIR}/build-arm64"

GWT_SRC_DIR="${PKG_DIR}/../../src/gwt"

if [ -n "${JENKINS_URL}" ]; then
   ADHOC=0
else
   ADHOC=1
fi

# determine architectures to build for
if [ "$(arch)" = "arm64" ]; then
   arch=x86_64,arm64
else
   arch=x86_64
fi

# default build options
build_gwt=1
build_package=1
clean=0
copy_gwt=1
install=0

# set CMake paths
if [ -z "${CMAKE_X86_64}" ]; then
   if [ -f "${HOME}/homebrew/x86_64/bin/cmake" ]; then
      CMAKE_X86_64="${HOME}/homebrew/x86_64/bin/cmake"
   fi
fi

if [ -z "${CMAKE_ARM64}" ]; then
   if [ -f "${HOME}/homebrew/arm64/bin/cmake" ]; then
      CMAKE_ARM64="${HOME}/homebrew/arm64/bin/cmake"
   fi
fi

# set tools directory
if [ -z "${RSTUDIO_TOOLS_ROOT}" ]; then
   if [ -d "${HOME}/opt/rstudio-tools" ]; then
      RSTUDIO_TOOLS_ROOT="${HOME}/opt/rstudio-tools"
   else
      RSTUDIO_TOOLS_ROOT="/opt/rstudio-tools"
   fi
fi

echo "Using RStudio tools at '${RSTUDIO_TOOLS_ROOT}'"

# read command line arguments

for arg in "$@"; do

   case "$arg" in
   clean)             clean=1 ;;
   --arch=*)          arch=${arg#*=} ;;
   --clean)           clean=1 ;;
   --install)         install=1 ;;
   --build-gwt=*)     build_gwt=${arg#*=} ;;
   --copy-gwt=*)      copy_gwt=${arg#*=} ;;
   --build-package=*) build_package=${arg#*=} ;;
   esac

done

case "${arch}" in *arm64*)  build_arm64=1  ;; esac
case "${arch}" in *x86_64*) build_x86_64=1 ;; esac

if [ "${clean}" = "1" ]; then

   # remove existing build dir
   rm -rf "${BUILD_DIR_X86_64}"
   rm -rf "${BUILD_DIR_ARM64}"

   # clean out ant build if requested
   if [ -d "${GWT_SRC_DIR}" ]; then
      cd "${GWT_SRC_DIR}"
      ant clean
   fi

   # move back to package dir
   cd "${PKG_DIR}"

fi

# set up MAKEFLAGS
# don't use all CPUs on build machine (appears to cause hangs)
if [ -n "${JENKINS_URL}" ]; then
   MAKEFLAGS="${MAKEFLAGS} -j2"
else
   MAKEFLAGS="${MAKEFLAGS} -j$(sysctl -n hw.ncpu)"
fi


# perform an x86_64 build
if [ -n "${build_x86_64}" ]; then

   # prefer using x86_64 build of cmake
   CMAKE="${CMAKE_X86_64:-/usr/local/bin/cmake}"
   echo "Using CMake '${CMAKE}' for x86_64 build"

   mkdir -p "${BUILD_DIR_X86_64}"
   mkdir -p "${BUILD_DIR_X86_64}/gwt"

   cd "${BUILD_DIR_X86_64}"
   rm -f CMakeCache.txt
   rm -rf build/_CPack_Packages

   echo "Configuring for x86_64 ..."
   arch -x86_64 "${CMAKE}"                                \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo                   \
      -DCMAKE_OSX_DEPLOYMENT_TARGET="10.12"               \
      -DRSTUDIO_TARGET=Desktop                            \
      -DRSTUDIO_PACKAGE_BUILD=1                           \
      -DRSTUDIO_CRASHPAD_ENABLED=0                        \
      -DRSTUDIO_TOOLS_ROOT="${RSTUDIO_TOOLS_ROOT}/x86_64" \
      -DRSTUDIO_USE_ADHOC_SIGNATURE="${ADHOC}"            \
      -DGWT_BUILD="${build_gwt}"                          \
      -DGWT_COPY="${copy_gwt}"                            \
      -DGWT_BIN_DIR="${BUILD_DIR_X86_64}/gwt/bin"         \
      -DGWT_WWW_DIR="${BUILD_DIR_X86_64}/gwt/www"         \
      -DGWT_EXTRAS_DIR="${BUILD_DIR_X86_64}/gwt/extras"   \
      "${PKG_DIR}/../.."
   echo "Done!"

   echo "Building for x86_64 with flags '${MAKEFLAGS}' ..."
   arch -x86_64 "${CMAKE}" --build . --target all -- ${MAKEFLAGS}
   echo "Done!"

fi

# perform an arm64 build
if [ -n "${build_arm64}" ]; then

   # prefer using arm64 build of cmake
   CMAKE="${CMAKE_ARM64:-/opt/homebrew/bin/cmake}"
   echo "Using CMake '${CMAKE}' for arm64 build"

   mkdir -p "${BUILD_DIR_ARM64}"
   cd "${BUILD_DIR_ARM64}"
   rm -f CMakeCache.txt
   rm -rf build/_CPack_Packages

   echo "Configuring for arm64 ..."
   arch -arm64 "${CMAKE}"                                \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo                  \
      -DCMAKE_OSX_DEPLOYMENT_TARGET="10.12"              \
      -DRSESSION_ALTERNATE_BUILD=1                       \
      -DRSTUDIO_TARGET=Desktop                           \
      -DRSTUDIO_PACKAGE_BUILD=1                          \
      -DRSTUDIO_CRASHPAD_ENABLED=0                       \
      -DRSTUDIO_TOOLS_ROOT="${RSTUDIO_TOOLS_ROOT}/arm64" \
      -DGWT_BUILD=0                                      \
      -DGWT_COPY=0                                       \
      "${PKG_DIR}/../.."
   echo "Done!"

   echo "Building for arm64 with flags '${MAKEFLAGS}' ..."
   arch -arm64 "${CMAKE}" --build . --target all -- ${MAKEFLAGS}
   echo "Done!"

fi

if [ "${build_package}" = "1" ]; then

   if command -v cpack &> /dev/null; then
      CPACK=cpack
   else
      CPACK="${HOME}/homebrew/arm64/bin/cpack"
   fi

   echo "Building package ..."
   cd "${BUILD_DIR_X86_64}"
   "${CPACK}" -G DragNDrop
   echo "Done!"
fi

cd "${PKG_DIR}"

if [ "${install}" = "1" ]; then
   RSTUDIO_BUNDLE_PATH="${BUILD_DIR_X86_64}/_CPack_Packages/Darwin/DragNDrop/RStudio-99.9.9/RStudio.app"
   RSTUDIO_DEVEL_PATH="/Applications/RStudio-Devel.app"
   if [ -e "${RSTUDIO_BUNDLE_PATH}" ]; then
      rm -rf "${RSTUDIO_DEVEL_PATH}"
      cp -R "${RSTUDIO_BUNDLE_PATH}" "${RSTUDIO_DEVEL_PATH}"
      echo "RStudio installed to '${RSTUDIO_DEVEL_PATH}'"
   else
      echo "Error: '${RSTUDIO_BUNDLE_PATH}' does not exist; cannot install"
   fi
fi


