#!/bin/sh

# A pre-commit hook script to:
#  -  run linting and formatting on staged files based on the lint-staged,
#     prettier and eslint configurations in src/node/desktop.
#  -  run detect-secrets on staged files based on the ./git_hooks/.secrets.baseline file

color_error='\033[1;31m' # red
color_highlight='\033[1;95m' # magenta
color_none='\033[0m' # no color

# Linting and formatting on RStudio Desktop IDE files
if test -f ./src/node/desktop/.lintstagedrc
then
    if git diff --staged --name-only | grep -qE '^src/node/desktop/.*'
    then
        cd ./src/node/desktop && npx lint-staged
    fi
else
    echo >&2 "${color_highlight}Note: src/node/desktop linting pre-commit hook is not being run because ${color_none}.lintstagedrc${color_highlight} was not found.${color_none}"
fi

# Secret scanning on staged files
if ! command -v detect-secrets &> /dev/null
then
    echo >&2 "${color_highlight}Note: secret scanning pre-commit hook is not being run because detect-secrets is not installed.${color_none}"
    echo >&2 "\tInstall ${color_highlight}detect-secrets${color_none} with 'pip install detect-secrets' or 'brew install detect-secrets'."
else
    secrets_results=$(git diff --staged --name-only -z | xargs -0 detect-secrets-hook --no-verify --baseline ./git_hooks/secrets/.secrets.baseline --exclude-files 'src/cpp/ext/.*' --exclude-files 'dependencies/submodules/.*')
    if [ -n "$secrets_results" ]; then
        echo "${color_error}Uh oh! It looks like you have secrets in your code. Please remove them before committing.${color_none}"
        echo "${color_error}If you are certain that these are false positives, see 'git_hooks/secrets/README.md' for instructions on how to mark them as such.${color_none}\n"
        echo "$secrets_results"
        exit 1
    fi
fi

exit 0
