#!/bin/bash

# detect the script's directory
SCRIPT_DIR=`dirname $0`

# check whether we were launched by RStudio.app or by the user
if [ ! -z "$RSTUDIO_NODE_WEBKIT" ]
then
    # lauched by RStudio.app, delegate exec to node-webkit
    exec $SCRIPT_DIR/node-webkit "$@" 
else
     # launched by user (e.g. via the dock) redirect to RStudio.app
    APP_PATH=`cd $SCRIPT_DIR/../../../../../../RStudio.app;pwd`
    open -a $APP_PATH
fi

