#!/bin/sh

set -e

if [ ! -d "./revealjs" ]; then
   git clone https://github.com/hakimel/reveal.js.git revealjs
fi

cd revealjs

# Get the latest 
git checkout master
git pull
VERSION=`git rev-parse HEAD`

# record the version
echo "$VERSION" > ../revealjs-version

# copy files
TARGET_DIR=../../session/resources/presentation/revealjs
mkdir -p $TARGET_DIR
mkdir -p $TARGET_DIR/css/theme
mkdir -p $TARGET_DIR/js
mkdir -p $TARGET_DIR/lib/js

cp LICENSE $TARGET_DIR/LICENSE
cp css/reveal.css $TARGET_DIR/css
cp css/reveal.min.css $TARGET_DIR/css
cp css/theme/simple.css $TARGET_DIR/css/theme
cp -R css/shaders $TARGET_DIR/css
cp lib/js/head.min.js $TARGET_DIR/lib/js
cp js/reveal.js $TARGET_DIR/js
cp js/reveal.min.js $TARGET_DIR/js

# return to tools dir
cd ..
