#!/bin/sh

set -e

if [ ! -d "./highlight.js" ]; then
    git clone git@github.com:rstudio/highlight.js.git highlight.js
    cd highlight.js
    git remote add upstream git://github.com/isagalaev/highlight.js
    cd ..
fi

cd highlight.js

# get the version with the r highlight mode
git checkout r
git pull
VERSION=`git rev-parse HEAD`

# copy files
TARGET_DIR=../../session/resources
mkdir -p $TARGET_DIR
echo "$VERSION" > ../highlight-version
python tools/build.py r

cat <<'EOF' > $TARGET_DIR/r-highlight.js
/*
Copyright (c) 2006, Ivan Sagalaev
All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of highlight.js nor the names of its contributors 
      may be used to endorse or promote products derived from this software 
      without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
EOF

cat src/highlight.js >> $TARGET_DIR/r-highlight.js
cp src/highlight.pack.js $TARGET_DIR/r-highlight.min.js
 
# return to tools dir
cd ..
