#!/usr/bin/env bash

for FILE in *.css; do

	SOURCE="${FILE}"
	TARGET="${FILE%.css}.xxd"

	if [ "${SOURCE}" -nt "${TARGET}" ]; then
		echo "-- Compiling '${SOURCE}' -> '${TARGET}'"
		cat "${SOURCE}" | xxd -i > "${TARGET}"
	fi

done

