/*
 * DO NOT EDIT
 * Generated by com.google.gwt.util.tools.OophmHeaderFileGenerator
 * TODO(jat): update generator to handle modifications
 */

/* from BrowserChannel.BROWSERCHANNEL_PROTOCOL_VERSION */
#define BROWSERCHANNEL_PROTOCOL_VERSION 1

/* from com.google.gwt.dev.shell.BrowserChannel.SpecialDispatchId */
#define SPECIAL_HAS_METHOD 0
#define SPECIAL_HAS_PROPERTY 1
#define SPECIAL_GET_PROPERTY 2
#define SPECIAL_SET_PROPERTY 3

/* from com.google.gwt.dev.shell.BrowserChannel.MessageType */
#define MESSAGE_TYPE_INVOKE 0
#define MESSAGE_TYPE_RETURN 1
#define MESSAGE_TYPE_LOAD_MODULE 2
#define MESSAGE_TYPE_QUIT 3
#define MESSAGE_TYPE_LOADJSNI 4
#define MESSAGE_TYPE_INVOKESPECIAL 5
#define MESSAGE_TYPE_FREEVALUE 6

/* from com.google.gwt.dev.shell.BrowserChannel.Value.ValueType */
#define VALUE_TYPE_NULL 0
#define VALUE_TYPE_BOOLEAN 1
#define VALUE_TYPE_BYTE 2
#define VALUE_TYPE_CHAR 3
#define VALUE_TYPE_SHORT 4
#define VALUE_TYPE_INT 5
#define VALUE_TYPE_LONG 6
#define VALUE_TYPE_FLOAT 7
#define VALUE_TYPE_DOUBLE 8
#define VALUE_TYPE_STRING 9
#define VALUE_TYPE_JAVA_OBJECT 10
#define VALUE_TYPE_JS_OBJECT 11
#define VALUE_TYPE_UNDEFINED 12
