/*
 * Copyright 2010 Google Inc.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.gwt.sample.expenses.gwt.request;

import com.google.gwt.requestfactory.shared.EntityListRequest;
import com.google.gwt.requestfactory.shared.LongString;
import com.google.gwt.requestfactory.shared.RequestFactory;
import com.google.gwt.requestfactory.shared.ServerOperation;
import com.google.gwt.valuestore.shared.ValueRef;
import com.google.gwt.valuestore.shared.ValuesKey;

/**
 * "API generated" for the service methods of
 * com.google.gwt.sample.expenses.server.domain.
 * <p>
 * IRL this interface will be generated by a JPA-savvy tool run before
 * compilation.
 */
public interface ExpensesRequestFactory extends RequestFactory {

  /**
   * Request selector.
   */
  interface EmployeeRequest {

    /**
     * @return a request object
     */
    @ServerOperation("FIND_ALL_EMPLOYEES")
    EntityListRequest<EmployeeKey> findAllEmployees();
  }

  /**
   * Request selector.
   */
  interface ReportRequest {

    /**
     * @return a request object
     */
    @ServerOperation("FIND_REPORTS_BY_EMPLOYEE")
    EntityListRequest<ReportKey> findReportsByEmployee(
        @LongString ValueRef<EmployeeKey, String> id);

    /**
     * @return a request object
     */
    @ServerOperation("FIND_ALL_REPORTS")
    EntityListRequest<ReportKey> findAllReports();
  }

  /**
   * Represents the server side operation to be carried out. This enum will be
   * generated by the JPA-aware tool.
   *
   */
  public enum ServerSideOperation implements RequestDefinition {
    FIND_ALL_EMPLOYEES("com.google.gwt.sample.expenses.server.domain.Employee",
        "findAllEmployees", null,
        com.google.gwt.sample.expenses.gwt.request.EmployeeKey.class), //
    FIND_ALL_REPORTS("com.google.gwt.sample.expenses.server.domain.Report",
        "findAllReports", null,
        com.google.gwt.sample.expenses.gwt.request.ReportKey.class), //
    FIND_REPORTS_BY_EMPLOYEE(
        "com.google.gwt.sample.expenses.server.domain.Report",
        "findReportsByEmployee", new Class[] {java.lang.Long.class},
        com.google.gwt.sample.expenses.gwt.request.ReportKey.class); //

    /**
     * the server side domain class.
     */
    private final String domainClassName;

    /**
     * the methodName of the domain class that is to be invoked.
     */
    private final String domainMethodName;

    /**
     * the parameterTypes of the parameters the domain method requires.
     */
    private final Class<?>[] parameterTypes;

    /**
     * for "READ" methods, the methods return a List. This class denotes the types
     * of the elements of the list.
     */
    private final Class<? extends ValuesKey<?>> returnType;

    private ServerSideOperation(String domainClassName, String domainMethodName,
        Class<?> parameterTypes[], Class<? extends ValuesKey<?>> entryReturnType) {
      this.domainClassName = domainClassName;
      this.domainMethodName = domainMethodName;
      this.parameterTypes = parameterTypes;
      this.returnType = entryReturnType;
    }

    public String getDomainClassName() {
      return domainClassName;
    }

    public String getDomainMethodName() {
      return domainMethodName;
    }

    public Class<?>[] getParameterTypes() {
      return parameterTypes;
    }

    public Class<? extends ValuesKey<?>> getReturnType() {
      return returnType;
    }
  }

  /**
   * @return a request selector
   */
  EmployeeRequest employeeRequest();

  /**
   * @return a request selector
   */
  ReportRequest reportRequest();
  // todo: probably will also need something like this to support custom service methods
  // that do mutations, not just find:
//  public ReportRequest reportRequest(DeltaValueStore deltas) {
//    return new ReportRequestImpl(this);
//  }
}
