/*
 * Copyright 2010 Google Inc.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.gwt.sample.expenses.gwt.request;

import com.google.gwt.requestfactory.shared.DataTransferObject;
import com.google.gwt.requestfactory.shared.Property;
import com.google.gwt.requestfactory.shared.Record;

import java.util.Date;

/**
 * "API Generated" DTO interface based on
 * {@link com.google.gwt.sample.expenses.server.domain.Report}.
 * <p>
 * IRL this class will be generated by a JPA-savvy tool run before compilation.
 */
@DataTransferObject(com.google.gwt.sample.expenses.server.domain.Report.class)
public interface ReportRecord extends Record {

  Property<Boolean> approved = new Property<Boolean>("approved", "Approved",
      Boolean.class);
  Property<EmployeeRecord> approvedSupervisor = new Property<EmployeeRecord>(
      "approvedSupervisor", "Approved Supervisor Key", EmployeeRecord.class);
  Property<Date> created = new Property<Date>("created", "Created", Date.class);
  Property<String> department = new Property<String>("department",
      "Department", String.class);
  Property<String> notes = new Property<String>("notes", "Notes", String.class);
  Property<String> purpose = new Property<String>("purpose", "Purpose",
      String.class);
  Property<EmployeeRecord> reporter = new Property<EmployeeRecord>("reporter",
      "Reporter", EmployeeRecord.class);

  Boolean getApproved();

  EmployeeRecord getApprovedSupervisor();

  Date getCreated();

  String getDepartment();

  String getNotes();

  String getPurpose();

  EmployeeRecord getReporter();

  boolean isChanged();

  void setApproved(Boolean approved);

  void setApprovedSupervisor(EmployeeRecord approvedSupervisor);

  void setCreated(Date created);

  void setDepartment(String department);

  void setNotes(String notes);

  void setPurpose(String purpose);

  void setReporter(EmployeeRecord reporter);
}
