#!/bin/sh

set -e

command -v npm >/dev/null 2>&1 || { echo >&2 "npm required but not found: exiting."; exit 1; }

# minified js using closure
minify () {
  echo "Minifying $1 to $2"
  CC_OPTS="--compilation_level SIMPLE --language_in ECMASCRIPT6 --language_out ECMASCRIPT5 --warning_level QUIET"
  java -Xmx128M -jar "../compiler/compiler.jar" $CC_OPTS --js $1 --js_output_file $2
}

if [ -d "./xterm.js" ]; then
  rm -rf xterm.js
fi

mkdir xterm.js
cd xterm.js

npm install xterm@3.14.5

XTERM_DIST_DIR=./node_modules/xterm/dist
XTERM_ADDONS_DIR=${XTERM_DIST_DIR}/addons
XTERM_TARGET_DIR=../../src/org/rstudio/studio/client/workbench/views/terminal/xterm

cp ${XTERM_DIST_DIR}/xterm.css ${XTERM_TARGET_DIR}/xterm.css
minify ${XTERM_DIST_DIR}/xterm.js ${XTERM_TARGET_DIR}/xterm.js
minify ${XTERM_ADDONS_DIR}/fit/fit.js ${XTERM_TARGET_DIR}/fit.js

echo Done!
