#!/usr/bin/env bash
set -e

# Update this when starting on a new RStudio release; also requires corresponding update
# in ant's build.xml.
RSTUDIO_VER=rstudio-1.3

# This script is intended to run from the rstudio/gwt/tools folder
RUN_DIR=`pwd`

if [ ! -d gwt ] || [ ! -d gwt/gwt ] || [ ! -d gwt/tools ]; then
    echo Error: gwt sources not found, use "sync-gwt" script to clone
    exit 1
fi

# Build GWT disto with custom version
cd ${RUN_DIR}/gwt/gwt
ant clean elemental dist-dev -Dgwt.version="${RSTUDIO_VER}"

GWT_ZIP=${RUN_DIR}/gwt/gwt/build/dist/gwt-${RSTUDIO_VER}.zip
if [ ! -f ${GWT_ZIP} ]; then
    echo Error: GWT build unsuccessful
    exit 1
fi

# Delete existing distro, extract new one
GWT_DIR=${RUN_DIR}/../lib/gwt
rm -rf ${GWT_DIR}/gwt-${RSTUDIO_VER}
unzip -qd ${GWT_DIR} ${RUN_DIR}/gwt/gwt/build/dist/gwt-${RSTUDIO_VER}.zip

echo Success. GWT built and copied to ${GWT_DIR}.
