#!/bin/sh

# Install Google's inert-polyfill and copies into the source tree
# https://github.com/GoogleChrome/inert-polyfill

set -e

command -v npm >/dev/null 2>&1 || { echo >&2 "npm required but not found: exiting."; exit 1; }

LOCAL_FOLDER=inert-polyfill
if [ -d $LOCAL_FOLDER ]; then
  rm -rf $LOCAL_FOLDER
fi

mkdir $LOCAL_FOLDER
cd $LOCAL_FOLDER
npm install inert-polyfill@0.2.5

GWT_TARGET_DIR=../../www/js
cp ./node_modules/inert-polyfill//inert-polyfill.min.js ${GWT_TARGET_DIR}

echo Done!
