#!/usr/bin/ruby

require 'find'

OutDir = '../src/org/rstudio/studio/client/workbench/views/source/editors/text/themes'

Find.find('ace/lib/ace/theme/') do |file|
  next if FileTest.directory?(file)

  contents = File.read(file)
  next unless contents =~ /cssText = "(.*?)";/m
  rules = $1
  rules.gsub!(/\\$/, '')

  next unless contents =~ /exports\.cssClass = "(.*?)";/
  style_name = $1

  rules.gsub!(/\.#{style_name} ?/, '')

  newfile = "#{OutDir}/#{File.basename(file).gsub(/\.js$/, '.css')}"
  File.open(newfile, 'w') {|f| f.write(rules)}
end