#!/usr/bin/env bash
set -e

BRANCH=rstudio/cucumberleaf-sunflower

#
# RStudio fork of GWT started with BRANCH off of GWT 2.8.2 plus our changes.
# That is, started life with:
#
#   git branch rstudio/v1.3 tags/2.8.2
#   git checkout rstudio/v1.3
#   git push --set-upstream origin rstudio/v1.3
#
# GWT branches will use the RStudio release names: e.g. rstudio/chocolate-cosmos. Not all
# RStudio releases will have a corresponding GWT branch (we don't change GWT very often).
#
# To take a new release of GWT, merge new tag (e.g. tags/2.9.0) into our branch and rebuild with
# build-gwt (after resolving any merge conflicts). Once successful, be sure to make PR of changes
# to rstudio/gwt as well as to rstudio itself.
#
#   git fetch upstream --tags
#   git checkout rstudio/the-branch
#   git merge 2.10.0
#
# To start work on a new release of RStudio, manually create a new branch, e.g. rstudio/new-name
# from the desired starting commit (most likely the head of the prior rstudio/release-name branch),
# and update the BRANCH constant in this script. For example, assuming prior release was
# "rstudio/kousa-dogwood" and the new one is "rstudio/mariposa-orchid":
#
#   git fetch origin
#   git checkout rstudio/kousa-dogwood
#   git checkout -b rstudio/mariposa-orchid
#   git push -u origin rstudio/mariposa-orchid
#

# check out our copy of gwt and build tools
mkdir -p gwtproject
cd gwtproject

set +e

git clone git@github.com:rstudio/gwt.git
(cd gwt && git remote add upstream https://github.com/gwtproject/gwt)
(cd gwt && git pull)

git clone git@github.com:gwtproject/tools.git
(cd tools && git pull)

set -e

# move to gwt directory
cd gwt
git status
git diff --quiet

# get latest main from upstream
git fetch upstream
git checkout main
git merge upstream/main

cat <<EOF

The GWT sources have been checked out at 'gwtproject/gwt'.

If you're preparing to update the bundled version of GWT in RStudio,
you can take the following steps:

1. Find the branch associated with the most recent RStudio release;
2. Check out that release branch,
3. Create a new branch off that release,
4. Merge the appropriate upstream version of GWT into that branch.

As an example, when we updated from Kousa Dogwood to Cucumber Sunflower:

	cd gwtproject/gwt
	git fetch upstream
	git checkout rstudio/kousa-dogwood
	git checkout -B rstudio/cucumberleaf-sunflower
	git merge 2.12.2

Next, you can try building GWT using:

	ant dist

If the build succeeds, you can push your newly-created branch.

After you've confirmed that GWT has been updated and built successfully,
you can use the 'build-gwt' script to rebuild the GWT jars into the
RStudio source tree.

You may also need to update the files at:

	src/gwt/.classpath
	src/gwt/.project

as IDE tools will use these to resolve the Java libraries used by RStudio.

EOF

