#!/bin/sh

set -e

if [ ! -d "./pdfjs" ]; then
    git clone git://github.com/rstudio/pdf.js.git pdfjs
    cd pdfjs
    git remote add upstream git://github.com/mozilla/pdf.js.git
    cd ..
fi

cd pdfjs
git clean -dfx

# Use this commit
git checkout 196c81a02de2a8b0bc937a77b75b7e08d0aa4dda

make
cd ..

CC_OPTS="--compilation_level SIMPLE_OPTIMIZATIONS --language_in ECMASCRIPT5"
java -jar "compiler/compiler.jar" $CC_OPTS --js pdfjs/build/pdf.js --js_output_file pdfjs/build/pdf.min.js

cp pdfjs/build/pdf.js ../src/org/rstudio/studio/client/pdfviewer/pdfjs/pdf.js
cp pdfjs/build/pdf.min.js ../src/org/rstudio/studio/client/pdfviewer/pdfjs/pdf.min.js

cp pdfjs/web/compatibility.js ../src/org/rstudio/studio/client/pdfviewer/pdfjs/
cp pdfjs/web/debugger.js ../src/org/rstudio/studio/client/pdfviewer/pdfjs/
# viewer.js uses CustomStyle which is defined in util.js
cat pdfjs/src/util.js pdfjs/web/viewer.js > ../src/org/rstudio/studio/client/pdfviewer/pdfjs/viewer.js
cp pdfjs/web/viewer.css ../src/org/rstudio/studio/client/pdfviewer/pdfjs/
