#!/bin/sh

set -e

rm -rf ace
git clone git@github.com:rstudio/ace.git
cd ace
git checkout master

# Point this to the upstream commit that we've tested
git reset --hard 832707a82b3743243dfe

git submodule update --init --recursive

# Merge all the bugfix branches
git merge \
    origin/bugfix-webkit-paste2 \
    origin/bugfix-updatefontsize2 \
    origin/bugfix-ctrl-backspace \
    origin/bugfix-active-line-back \
    origin/bugfix-eclipse-print-margin \
    origin/patch-advanced-indent2 \
    origin/patch-invisible-colors \
    origin/patch-build-matchingbraceoutdent \
    origin/patch-normalizeinput \
    origin/bugfix/search-regexp \
    origin/bugfix/selected-word-colors \


git cherry-pick eb02e51

make clean
make
cp build/src/ace.js ../../src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/
cp build/src/ace-uncompressed.js ../../src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/
