#!/usr/bin/env bash

#
# install-dependencies-debian
#
# Copyright (C) 2009-12 by RStudio, Inc.
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

# build/development tools
apt-get -y install build-essential pkg-config fakeroot cmake

# core system libraries
apt-get -y install uuid-dev libssl-dev libbz2-dev zlib1g-dev libpam-dev

# needed for QtWebKit >= 5
apt-get -y install libxslt1-dev

# app armor dependencies no longer included in ubuntu >= 11.10
apt-get -y install libapparmor1 apparmor-utils

# boost
## This version of libboost-all-dev is now 1.55.0.2 in the current stable version of debian (jessie) [2015-12-04].
## This is further along than the version installed by the install-boost script also run by install-dependencies-debian.
## So comment this out to ensure only one version of boost is installed here and it is supported by rstudio.
#apt-get -y install libboost-all-dev

# pango cairo
apt-get -y install libpango1.0-dev

# gwt prereqs
## openjdk-6-jdk is no longer available in the current stable version of debian [2015-12-04]
## Also, ant no longer depends on openjdk-6-jdk
#apt-get -y install openjdk-6-jdk 
apt-get -y install ant

# overlay
if [ -e install-overlay-debian ]
then
  ./install-overlay-debian
fi

# common
apt-get -y install unzip
cd ../common
./install-common
cd ../linux

# desktop dependencies (qt)
if [ "$1" != "--exclude-qt-sdk" ]
then
   # ubuntu server doesn't include gstreamer by default so ensure that these
   # libs are always available for desktop builds (required by QtWebKit 2.2)
   apt-get -y install libgstreamer0.10-0 libgstreamer-plugins-base0.10-0

   # Ubuntu 12.04 doesn't include libjpeg62 (and it's required by Qt 4.8)
   apt-get -y install libjpeg62

   # Need the OpenGL development libraries to build QtGui
   apt-get -y install libgl1-mesa-dev

   # install Qt 4.8 SDK (into a private /opt/RStudio-QtSDK directory so as to 
   # not conflict with any other installed versions of Qt on the system)
   ./install-qt-sdk
fi






