#!/bin/bash

#
# install-pandoc-src
#
# Copyright (C) 2009-12 by RStudio, Inc.
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

# get pandoc
PANDOC_VERSION=1.12.1
PANDOC_NAME=pandoc-${PANDOC_VERSION}
PANDOC_INSTALL_DIR=${PANDOC_DIR}/${PANDOC_NAME}
if [ ! -d ${PANDOC_INSTALL_DIR} ]
then
  PANDOC_TARBALL=${PANDOC_NAME}.tar.gz
  wget http://pandoc.googlecode.com/files/${PANDOC_TARBALL} \
       -O ${PANDOC_TARBALL} 
  tar xf ${PANDOC_TARBALL}
  rm ${PANDOC_TARBALL}

  # build it
  PANDOC_SRC=${PANDOC_NAME}-src
  mv ${PANDOC_NAME} ${PANDOC_SRC}
  cd ${PANDOC_SRC}

  $CABAL update
  $CABAL install --only-dependencies
  $CABAL install hsb2hs
  $CABAL install --flags="embed_data_files" citeproc-hs
  $CABAL install alex happy
  $CABAL configure --flags="embed_data_files"
  $CABAL build
  mkdir -p ${PANDOC_INSTALL_DIR} 
  cp dist/build/pandoc/pandoc ${PANDOC_INSTALL_DIR}

  cd ..
  rm -rf ${PANDOC_SRC}
else
  echo "Pandoc ${PANDOC_VERSION} already installed"
fi


