#!/bin/bash

#
# install-dependencies-debian
#
# Copyright (C) 2009-12 by RStudio, Inc.
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

# build/development tools
sudo apt-get -y install build-essential
sudo apt-get -y install pkg-config
sudo apt-get -y install fakeroot
sudo apt-get -y install cmake

# core system libraries
sudo apt-get -y install uuid-dev
sudo apt-get -y install libssl-dev
sudo apt-get -y install libbz2-dev
sudo apt-get -y install zlib1g-dev
sudo apt-get -y install libpam-dev

# app armor dependencies no longer included in ubuntu >= 11.10
sudo apt-get -y install libapparmor1 
sudo apt-get -y install apparmor-utils

# boost
sudo apt-get -y install libboost-all-dev

# pango cairo
sudo apt-get -y install libpango1.0-dev

# gwt prereqs
sudo apt-get -y install openjdk-6-jdk 
sudo apt-get -y install ant

# overlay
if [ -e install-overlay-debian ]
then
  ./install-overlay-debian
fi

# common
sudo apt-get -y install unzip
cd ../common
./install-common
cd ../linux

# desktop dependencies (qt)
if [ "$1" != "--exclude-qt-sdk" ]
then
   # ubuntu server doesn't include gstreamer by default so ensure that these
   # libs are always available for desktop builds (required by QtWebKit 2.2)
   sudo apt-get -y install libgstreamer0.10-0
   sudo apt-get -y install libgstreamer-plugins-base0.10-0

   # Ubuntu 12.04 doesn't include libjpeg62 (and it's required by Qt 4.8)
   sudo apt-get -y install libjpeg62

   # install Qt 4.8 SDK (into a private /opt/RStudio-QtSDK directory so as to 
   # not conflict with any other installed versions of Qt on the system)
   ./install-qt-sdk
fi






