#!/usr/bin/env bash

#
# install-dependencies-yum
#
# Copyright (C) 2022 by Posit Software, PBC
#
# Unless you have received this program directly from Posit Software pursuant
# to the terms of a commercial license agreement with Posit Software, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

PACKAGES=(
	ant
	boost-devel
	bzip2-devel
	cmake
	fakeroot
	gcc
	gcc-c++
	java
	java-devel
	jq
	libffi
	libuser-devel
	libuuid-devel
	libXScrnSaver-devel
	libxslt-devel
	make
	mesa-libGL-devel
	openssl-devel
	pam-devel
	pango-devel
	postgresql-devel
	rpmdevtools
	sqlite-devel
	wget
	whois
	xml-commons-apis
	zlib-devel
)

sudo yum install -y "${PACKAGES[@]}"

# overlay
if [ -e install-overlay-yum ]; then
  ./install-overlay-yum
fi

# common
cd ../common
./install-common "$1"
cd ../linux

