#!/usr/bin/env bash

#
# install-qt-linux
#
# Copyright (C) 2009-20 by RStudio, PBC
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

# Install minimal Qt bits needed to build via command-line (e.g. Docker).
# For developer environments, better to install using Qt's online installer.
DEST=/opt/RStudio-QtSDK
mkdir -p ${DEST}
./install-qt.sh --version 5.12.6 --directory ${DEST}/Qt5.12.6 \
    qtbase \
    qtwebengine \
    qtwebchannel \
    qtquick \
    qtquickcontrols2 \
    qtdeclarative \
    qtsensors \
    qtlocation \
    qtsvg \
    qtxmlpatterns \
    qttools \
    icu

