#!/bin/bash

#
# install-pandoc-yum
#
# Copyright (C) 2009-12 by RStudio, Inc.
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

# install dir
INSTALL_DIR=`pwd`

# establish pandoc directory and work there
PANDOC_DIR=${INSTALL_DIR}/pandoc
mkdir -p ${PANDOC_DIR}
cd $PANDOC_DIR

# install haskell dependencies
sudo yum install -y gmp-devel
sudo yum install -y haskell-platform

# wipe out existing state
rm -rf ~/.cabal
rm -rf ~/.ghc

# install latest version of pandoc
cabal update
cabal install crypto-cipher-types-0.0.7
cabal install --flags="embed_data_files" pandoc pandoc-citeproc



