#!/usr/bin/env bash

#
# install-dependencies-linux
#
# Copyright (C) 2022 by Posit Software, PBC
#
# Unless you have received this program directly from Posit Software pursuant
# to the terms of a commercial license agreement with Posit Software, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

source /etc/os-release

if [ "${ID_LIKE}" = "debian" ]; then
    bash install-dependencies-debian
elif [ "${ID}" = "fedora" ]; then
    bash install-dependencies-yum
else
    echo "ERROR: install-dependencies-linux not yet implemented for this platform; perhaps you'd like to add it?"
    exit 1
fi
