/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c EvinceDaemon -p EvinceDaemon.h:EvinceDaemon.cpp org.gnome.evince.Daemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef EVINCEDAEMON_H_1335820976
#define EVINCEDAEMON_H_1335820976

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.gnome.evince.Daemon
 */
class EvinceDaemon: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.gnome.evince.Daemon"; }

public:
    EvinceDaemon(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~EvinceDaemon();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> FindDocument(const QString &uri, bool spawn)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(uri) << QVariant::fromValue(spawn);
        return asyncCallWithArgumentList(QLatin1String("FindDocument"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace gnome {
    namespace evince {
      typedef ::EvinceDaemon Daemon;
    }
  }
}
#endif
