#!/bin/sh
# Re-builds all the generated code in ../java/elemental/ from the scraped IDL files
# in w3c/. This will blow away all files labeled "generated code".
ROOT=`dirname $0`
python \
  ${ROOT}/css/generate-style.py \
  ${ROOT}/css/styles.txt \
  ${ROOT}/templates/java_interface_CSSStyleDeclaration.darttemplate \
  ${ROOT}/templates/jso_impl_CSSStyleDeclaration.darttemplate

python ${ROOT}/scripts/elemental_fremontcutbuilder.py
python ${ROOT}/scripts/elementaldomgenerator.py
# Keep compatibility with Google's internal build
if [ -d ${ROOT}/../java/elemental/ ]; then
  cp -R ${ROOT}/generated/src/elemental/* ${ROOT}/../java/elemental/
fi
