#!/usr/bin/env bash

: ${ASANFLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize=float-divide-by-zero"}
: ${CC="clang-4.0"}
: ${CXX="clang++-4.0"}
: ${MAKEFLAGS="-j8"}

mkdir -p asan-build
cd asan-build
rm CMakeCache.txt
cmake ../cpp                                   \
    -DCMAKE_C_COMPILER="${CC}"                 \
    -DCMAKE_C_FLAGS="${ASANFLAGS}"             \
    -DCMAKE_CXX_COMPILER="${CXX}"              \
    -DCMAKE_CXX_FLAGS="${ASANFLAGS}"           \
    -DRSTUDIO_USE_LIBCXX=Yes                   \
    -DRSTUDIO_USE_PRECOMPILED_BOOST=No         \
    -DRSTUDIO_BOOST_VERSION=1.56.0
cd ..

cmake --build asan-build -- ${MAKEFLAGS}
