#!/usr/bin/env sh

: ${ASANFLAGS="-fsanitize=address -fno-omit-frame-pointer -fno-sanitize=float-divide-by-zero"}
: ${CC="clang-4.0"}
: ${CXX="clang++-4.0"}
: ${MAKEFLAGS="-j8"}

mkdir -p asan-build
cd asan-build
rm CMakeCache.txt
cmake ../cpp                                   \
    -DCMAKE_C_COMPILER="${CC}"                 \
    -DCMAKE_C_FLAGS="${ASANFLAGS}"             \
    -DCMAKE_CXX_COMPILER="${CXX}"              \
    -DCMAKE_CXX_FLAGS="${ASANFLAGS}"           \
    -DCMAKE_LINKER="${CXX}"
cd ..

cmake --build asan-build -- ${MAKEFLAGS}
