#!/usr/bin/env bash

: ${ASANFLAGS="-fsanitize=address,undefined -fsanitize-recover=address,undefined -fno-omit-frame-pointer -fno-sanitize=float-divide-by-zero"}
: ${LDFLAGS=""}
: ${BUILD_DIR="clang-ubsan-build"}
: ${MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"}
: ${R_HOME="$(R RHOME)"}

mkdir -p "${BUILD_DIR}"
cd "${BUILD_DIR}"
cmake ../cpp                                    \
    -DLIBR_HOME="${R_HOME}"                     \
    -DCMAKE_BUILD_TYPE="Debug"                  \
    -DCMAKE_C_FLAGS="${ASANFLAGS} ${LDFLAGS}"   \
    -DCMAKE_CXX_FLAGS="${ASANFLAGS} ${LDFLAGS}" \
    "$@"
cd ..

cmake --build "${BUILD_DIR}" -- "${MAKEFLAGS}"
